### ISSUE TITLE
🐛 [Immich] Search bar and face recognition does not work

### ISSUE THREAD

**Issue by Blendi** [alexbelgium/hassio-addons#1027]
### Description

Hello,

I have installed immich on my homeassistant installation on a raspberry pi 4 with 4BG of RAM. 
So far the installation works with an external postngres 15 database. I had issues using Immich internal database, somehow it would fail to create and then immich wont start.

When I check the logs on Homeassistant I see a lot of error especially after running the job face recognition.

I was very interested to learn what was the issue, but I lack knowledge so it was not easy. 

I did a fresh installation of Immich on a debian 12 server, which happened to buy recently. I was thinking in moving everything to this small machine to have a better experience with homeassistant. It is a small pc with N100 intel cpu and 16GB of ram.

I noticed that the installation of Immich on debian had no issues. Everything seems to work fine and the face recognation works perfectly. There is "SEARCH" bar which for some reason does not appear in immich installed on HA.
There is a page showing people.
![image](https://github.com/alexbelgium/hassio-addons/assets/3333692/c64f3609-c7f9-4c11-bc51-c9735e8a1e89)

![image](https://github.com/alexbelgium/hassio-addons/assets/3333692/d15c8776-b42e-4f6f-bfa6-7405b874b80c)

But I don't see the search bar on the Immich addon in HA
![image](https://github.com/alexbelgium/hassio-addons/assets/3333692/c5bb5eee-2ae1-4bcb-9af0-e565fb264cea)

My initial suspicion was that [immich_machine_learning] container is not working in the instance installed in HA but when looking at the error loge seems to be more related to the immich_typesense container not starting.

Anyway I am no expert on this but clearly the error logs in the immich instance on HomeAssistant show some issues. Could you have a look at it? 

Also my request would be, could you add a configuration option especially for homeassistant installation on arm64 that can either include or disable the immich_machine_learning docker? It would help me a lot since I dont need machine learning docker to be running and eating RAM on homeassistant. I can configurare immich on HA to use an exteranal url for machine learning and run this container in a powerful machine. The powerful machine runs periodically every day 4-5 hours.
![image](https://github.com/alexbelgium/hassio-addons/assets/3333692/5bc83017-bdd1-481a-a09c-2c47e9433ae0)

### Reproduction steps

```bash
Start Immich on HomeAssistant.
Wait for it to start
Upload pictures.
Check Logs tab in HomeAssistant
```

### Addon Logs

```bash
}

[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Object:
{
  "id": "dd97319c-39d1-45b1-8fb1-55762d30362b"
}

[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Object:
{
  "id": "68ae7512-449a-4d3e-98e6-70a1cc5c8181"
}

[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Object:
{
  "id": "e1aab308-4ac6-49aa-996b-1c41258df3e4"
}

[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Object:
{
  "id": "83c676d2-315c-4247-8c84-06ec9b9f2ae4"
}

[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Object:
{
  "id": "a4410ee9-9ba8-462c-842f-19c56d3067cc"
}

[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:06 PM   ERROR [JobService] Object:
{
  "id": "65a8f2e5-5be2-4767-8ba2-09e982ebe368"
}

[Nest] 1275  - 10/14/2023, 4:24:07 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): Error: Typesense multi-search error: 404 - Not found.
[Nest] 1275  - 10/14/2023, 4:24:07 PM   ERROR [JobService] Error: Typesense multi-search error: 404 - Not found.
    at TypesenseRepository.asResponse (/app/immich/server/dist/infra/repositories/typesense.repository.js:253:19)
    at TypesenseRepository.searchFaces (/app/immich/server/dist/infra/repositories/typesense.repository.js:233:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleRecognizeFaces (/app/immich/server/dist/domain/person/person.service.js:210:38)
    at async /app/immich/server/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 1275  - 10/14/2023, 4:24:07 PM   ERROR [JobService] Object:
{
  "id": "41399858-f19f-4275-b72b-b4aa7b6525e7"
}
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi,

Wow thanks for all the infos !

Someone has everything set fine in this thread : https://github.com/alexbelgium/hassio-addons/issues/933

There is several options that you could try : 
    "DISABLE_MACHINE_LEARNING": true/false
    "MACHINE_LEARNING_WORKERS": number of workers should be low as uses lots of ram
    "MACHINE_LEARNING_WORKER_TIMEOUT": should be rather high
    "TYPESENSE_ENABLED": true/false

Perhaps one of these could help plus the other thread might help ?
In theory the first option should totally disable the function. Thanks !

**Comment by Blendi** [comment]
Many thanks @alexbelgium 

So solution was in front of my eyes but I did not see it. in the configuration part in HomeAssistant Addon I should have enabled first the option: **Show unused optional configuration options**

I was able

**Comment by alexbelgium** [comment]
Great! Thanks for all the details it will help other people too. Have a nice day
