### ISSUE TITLE
❓ [addon] Wger ssl support 

### ISSUE THREAD

**Issue by yoyomax80400** [alexbelgium/hassio-addons#1104]
**Which addon?**
Wger

**Addon or app?**
Addon

**Describe the solution you'd like**
I would like to use my ssl certificat from home assistant to the addon, but unfortaly i didn't see any information how to do 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alexbelgium** [comment]
Hi, the new way of working proposed by homeassistant is that you install the nginx proxy manager according to this very short guide on adding ssl to the addons : https://github.com/alexbelgium/hassio-addons/wiki/Add%E2%80%90ons-feature-:-ssl

I won't add anymore ssl to individual addons as it is just less optimal

**Comment by yoyomax80400** [comment]
Thanks for reply I will do it 

Do you have any idea why I'm always being logged-off and getting this in log : 

WARNING 2023-11-29 20:28:43,153 log The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.: /api/v2/exercisebaseinfo/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sessions/middleware.py", line 59, in process_response
    request.session.save()
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sessions/backends/cache.py", line 62, in save
    raise UpdateError
django.contrib.sessions.backends.base.UpdateError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sessions/middleware.py", line 61, in process_response
    raise SessionInterrupted(
django.contrib.sessions.exceptions.SessionInterrupted: The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
