### ISSUE TITLE
🐛 [MyElectricalData] update to 0.9.3 impossible

### ISSUE THREAD

**Issue by WarC0zes** [alexbelgium/hassio-addons#1137]
### Description

Hi,
Updating to version 0.9.3 of the addon on HAOS doesn't work.

### Reproduction steps

```bash
Update addon to 0.9.3.
```

### Addon Logs

```bash
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 04:01:34 (1 occurrences)
Last logged: 04:01:34

Failed to to call /store/addons/db21ed7f_enedisgateway2mqtt/update - Can't install ghcr.io/alexbelgium/myelectricaldata-aarch64:0.9.3: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.9.3&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
````

```
Détails du journal (ERREUR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 04:01:14 (1 occurrences)
Last logged: 04:01:14

[546984184640] Error updating MyElectricalData: Can't install ghcr.io/alexbelgium/myelectricaldata-aarch64:0.9.3: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.9.3&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/alexbelgium/myelectricaldata-aarch64:0.9.3: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.9.3&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating MyElectricalData: Can't install ghcr.io/alexbelgium/myelectricaldata-aarch64:0.9.3: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.9.3&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
```
```


### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Merci, la nouvelle nomenclature upstream avait changé de 0.9.3 a v0.9.3 sur dockerhub j'ai aligné et poussé une nouvelle image

**Comment by WarC0zes** [comment]
C'est bon, ca fonctionne. Mise a jour effectuer en 0.9.3. Merci pour la rapidité du fix ;)
