### ISSUE TITLE
🐛 [Qbittorrent] Unable to connect to Qbittorrent from Sonarr or Prowlarr

### ISSUE THREAD

**Issue by JohnnyPicnic** [alexbelgium/hassio-addons#1153]
### Description

Tried various combinations of localhost or IP and the port but I only get "Unable to connect to qBittorrent".
![Screenshot 2024-01-01 at 7 12 19 PM](https://github.com/alexbelgium/hassio-addons/assets/5553884/3b84eaab-2e10-4b26-b53d-bc7d39c1a557)

### Reproduction steps

```bash
Fresh install
```

### Addon Logs

```bash
2024-01-01 19:13:09.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to qBittorrent
2024-01-01 19:13:10.3|Error|X509CertificateValidationService|Certificate validation for 192.168.1.9 failed. RemoteCertificateNameMismatch
2024-01-01 19:13:10.3|Error|QBittorrent|Unable to test qBittorrent

[v4.0.0.740] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 36
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 84
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass7_0.<GetProxyCache>b__0() in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 79
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxyCache(QBittorrentSettings settings, Boolean force) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 79
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 62
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in ./api/hassio_ingress/0n2nL7mQdI93RMGttf4Fab1qpuBB4wipoPnmCdbezzc/sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 418

2024-01-01 19:13:10.3|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to qBittorrent
```

### Architecture

amd64

### OS

Virtual Machine

**Comment by hacshacdgacs** [comment]
Try disabling ssl?

**Comment by JohnnyPicnic** [comment]
> Try disabling ssl?

Yup that worked. Would be nice to get it working with ssl.

**Comment by JohnnyPicnic** [comment]
Ah ok that makes sense. I got everything working without https.
