### ISSUE TITLE
🐛 [NextCloud] wont start ???

### ISSUE THREAD

**Issue by ymurawski** [alexbelgium/hassio-addons#1171]
### Description

Hi, i just installed Nextcloud but it hangs on the loading screen. Am i missing something or is my MariaDB config wrong ?

![1](https://github.com/alexbelgium/hassio-addons/assets/46036625/2c2da2f4-7ba7-4a0e-8425-9bed6bbe5999)
![2](https://github.com/alexbelgium/hassio-addons/assets/46036625/1a7d7ee8-3463-48f6-aaf1-315b2653bc6c)
![3](https://github.com/alexbelgium/hassio-addons/assets/46036625/caa0b325-3129-410f-a556-a7227577018a)
![4](https://github.com/alexbelgium/hassio-addons/assets/46036625/06fc488b-e27a-4afa-a1fb-ef38b12a4991)

### Reproduction steps

```bash
Start just installed Nextcloud addon
```

### Addon Logs

```bash
/etc/cont-init.d/02-mariadb_discovery.sh: executing
/etc/cont-init.d/30-ssl.sh: executing
/etc/cont-init.d/99-add_packages.sh: executing
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] 02-default-location: executing...
[migrations] 02-default-location: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 4
generating self-signed keys in /data/config/keys, you can replace these with your own keys if required
.....+++++++++++++++++++++++++++++++++++++++*.+++++++++++++++++++++++++++++++++++++++*.....+......+..............+.+..+.+......+......+..+...+.........+....+..............+...+............+..........+...+..+...+....+...+..+.+.......................+....+..+......+...+.+...+..+....+.........+..+....+...........+....+.....+.+...........+.........+.+.........+......+........+............+...+....+...+...+..+...............+....+...+...............+...+...+......+...+...........+.+......+..+...+............+......+....+...+...............+............+..+..........+...........+...+.+..............+.........+...+....+......+.....+....+...+..+....+..+.............+...........+....+.........+.....+.......+.....+.+..+.............+..+...+......................+..+....+............+............+..+...+......+.+...+.....+...+....++++++
.+.+..+...+.........+++++++++++++++++++++++++++++++++++++++*...........+.+.....+.+..+.+..+....+......+.........+...+........+...+.......+..................+......+.........+++++++++++++++++++++++++++++++++++++++*......+...+......+......+......+.......+.....+..........+..+.........+....+.....+.+...........+.+.........+.....+....+....................+....+..+.+............+...+.........+...........+..........+.........+.....+...+......+.........+.+..+...+....+...+............+......+..+...+....+.....+.......+.........+............+..+.+..+.......+..+.+..+.+...........+.++++++
-----
Initializing nextcloud 28.0.1.1 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
Starting...
/etc/cont-init.d/02-init_steps.sh: executing
Setting logs
 
--------------------------------------------------------------------------------------------------------------
Nextcloud not installed, please wait for addon startup, login Webui, install Nextcloud, then restart the addon
--------------------------------------------------------------------------------------------------------------
 
/etc/cont-init.d/02-mariadb_discovery.sh: executing
---
MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : service bashio::log.blue Database user : service
Database password : ooghie1oangeexoefisi6foo6piwaht7Ohghaesoomooquiefei8ic9Chooqui5e
Database name : nextcloud
Host-name : core-mariadb:3306
---
/etc/cont-init.d/99-add_packages.sh: executing
Cloning into 'pdfannotate'...
warning: redirecting to https://gitlab.com/nextcloud-other/nextcloud-annotate.git/
Nextcloud annotate app added to Nextcloud app store
[15:42:41] INFO: Installing additional apps :
... inotify-tools
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
 
Starting the upstream container
 
[custom-init] No custom files found, skipping...
crond: crond (busybox 1.36.1) started, log level 8
[ls.io-init] done.
[11-Jan-2024 15:42:41] NOTICE: fpm is running, pid 1009
[11-Jan-2024 15:42:41] NOTICE: ready to handle connections
crond: USER abc pid 1278 cmd /usr/bin/php /app/www/public/cron.php 2>&1
crond: USER root pid 1279 cmd run-parts /etc/periodic/15min
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Please check for duplication, the previous issue has your exact title ;-) https://github.com/alexbelgium/hassio-addons/issues/1170 and the same description : on a first install it seems the system hands
