### ISSUE TITLE
[Request] Whoogle

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#122]
Awesome repo! Can I do a request for https://github.com/benbusby/whoogle-search ? Awesome selfhosted privacy friendly Google :)

**Comment by alexbelgium** [comment]
Hi, I've pushed a first version! Let me know if everything works

**Comment by bruvv** [comment]
Awesome! Will test this when I have more RAM installed will close for now :)

**Comment by MaxWinterstein** [comment]
First query failed, next one worked fine. 

```log
Starting...
/scripts/00-aaa_dockerfile_backup.sh: executing
/scripts/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Whoogle Search
 Self-hosted, ad-free, privacy-respecting metasearch engine
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.12.3
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/scripts/90-config_yaml.sh: executing
No config file, creating one from template
[12:23:08] FATAL: Config file not found, creating a new one. Please customize the file in /config/addons_config/whoogle_search/config.yaml before restarting.
Config file is a valid yaml
[12:23:09] INFO: Starting the app with the variables in in /config/addons_config/whoogle_search/config.yaml
/scripts/99-run.sh: executing
 * WARNING: tor is already starting
Serving on http://0.0.0.0:5000
ERROR:app:Exception on /search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/whoogle/app/routes.py", line 88, in decorated
    os.remove(invalid_session)
FileNotFoundError: [Errno 2] No such file or directory: '/data/session/b22d6e08aec585c85a60138af5e7d150'
WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by bruvv** [comment]
Known bug: https://github.com/benbusby/whoogle-search/issues/577

**Comment by alexbelgium** [comment]
Well it worked fine for me! Have a nice day
