### ISSUE TITLE
myelectricaldata_dev-amd64:0.12.0: 500 Server

### ISSUE THREAD

**Issue by Sonic62** [alexbelgium/hassio-addons#1263]
### Description

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 03:21:35 (4 occurrences)
Last logged: 03:31:24

[140053333805376] Error updating MyElectricalData Dev: Can't install ghcr.io/alexbelgium/myelectricaldata_dev-amd64:0.12.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.12.0&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata_dev-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
[140053592992320] Error updating MyElectricalData Dev: Can't install ghcr.io/alexbelgium/myelectricaldata_dev-amd64:0.12.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.12.0&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata_dev-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 55, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/alexbelgium/myelectricaldata_dev-amd64:0.12.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.12.0&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata_dev-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating MyElectricalData Dev: Can't install ghcr.io/alexbelgium/myelectricaldata_dev-amd64:0.12.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.12.0&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata_dev-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

### Reproduction steps

```bash
Upadate
```

### Addon Logs

```bash
update
```

### OS

Virtual Machine

**Comment by alexbelgium** [comment]
Some issues with github it seems... Hope it will be solved soon

**Comment by pedromfa** [comment]
Hi Alex. But some updates were successful. Sonarr and Prowlarr for example updated with no issues.
