### ISSUE TITLE
🐛 [Immich] The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases

### ISSUE THREAD

**Issue by blendrik** [alexbelgium/hassio-addons#1264]
### Description

There is another breaking change. Latest Immich now needs pgvecto.rs extension 0.2.0.

Thanks a lot for your work!

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Addon Logs

```bash
Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:137:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23
```

### Architecture

amd64

**Comment by blendrik** [comment]
Dirty workaround ;-)

I updated the vectors-pg15_0.2.0_amd64.deb package by hand:
`curl -L https://github.com/tensorchord/pgvecto.rs/releases/download/v0.2.0/vectors-pg15_0.2.0_amd64.deb -o vectors-pg15_0.2.0_amd64.deb`

And added 
`dpkg -i vectors-pg15_0.2.0_amd64.deb`
into
`postgres.sh`

Then restart Postgres-addon, then restart Immich-addon -> Read logs, and restart both again.

**Comment by ShonP40** [comment]
Made a PR to fix this https://github.com/alexbelgium/hassio-addons/pull/1265

**Comment by blendrik** [comment]
Perfect, thanks for the quick response!
