### ISSUE TITLE
🐛 [NextCloud] Can't connect through Nabu Casa?

### ISSUE THREAD

**Issue by purierca** [alexbelgium/hassio-addons#1276]
### Description

Hi
I had managed to install a working version of NextCloud in HA with MariaDB, using the homeassistant.local links.
However I'm working remotely as well and need to access NextCloud through https; I'm using Nabu Casa for this.
From the add on config page I can click "Web UI" and it gives me a Nabu Casa link (https://<id>.ui.nabu.casa:8099) but I simply can't connect to it; what am I doing wrong?

### Reproduction steps

```bash
1. Connect to HA through Nabu Casa
2. Go to 'hassio/addon/db21ed7f_nextcloud_ocr/info'
3. Click on 'Open Web UI'
4. See error
```

### Addon Logs

```bash
User UID:    1000
User GID:    1000
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 4
generating self-signed keys in /data/config/keys, you can replace these with your own keys if required
.........+..+......+....+...+......+.....+.........+...+...+......+.+........+.......+...+......+...+.....+...+...+.+...+...+........+....+..+....+.........+..+....+.....+++++++++++++++++++++++++++++++++++++++*...+....+.....+...............+...+.........+++++++++++++++++++++++++++++++++++++++*.......+..+.........+......+......+.......+......+..+...+.+...+.....+......+.+.....+.........+......................+..+............................+...+..+...............+....+...............+...+...+...+.....+.........+......+....+.....+...+.........+.........+..........+..+....+...+...........+.......+........+.+...+...+...+............+..+.....................+.+...+......+..+.......+..+......+....+...........+...+.+......+............+..+...+.+......+.....+....+..+.........+...++++++
.+......+.....+......+....+..............+...+....+...........+.......+......+..+.......+.....+.+..............+...+....+...+++++++++++++++++++++++++++++++++++++++*...+....+...+.........+...+..+.........+.......+...+......+.....+......+...+++++++++++++++++++++++++++++++++++++++*...+...........+................+...+............+...........+.......+......+......+...........+.........+......+...+....+..+.+...+.........+..+...+.......+.....+....+......+......+..+...+...+.........+......+.......+..+..........+...+.....+...+.+......+............+.............................................+...+........+.+......+..+...+....+.....+.+.........+.....+.........+......+..........+..............+......................+..+.+......+.....+..........+.....+......+..........+...+..+...+.........+.+......+...++++++
-----
Initializing nextcloud 28.0.2.5 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /data/config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
Starting...
/etc/cont-init.d/02-mariadb_discovery.sh: executing
---
MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : service bashio::log.blue Database user : service
Database password : zievoh1KeeGheeGoh4Je1ooghooR0ooti9aanguokahth7Loshohs0Eu5in1iePh
Database name : nextcloud
Host-name : core-mariadb:3306
---
/etc/cont-init.d/99-add_packages.sh: executing
Cloning into 'pdfannotate'...
warning: redirecting to https://gitlab.com/nextcloud-other/nextcloud-annotate.git/
Nextcloud annotate app added to Nextcloud app store
[17:06:49] INFO: Installing additional apps :
... inotify-tools
/etc/cont-init.d/99-elasticsearch.sh: executing
/etc/cont-init.d/99-ocr.sh: executing
/etc/cont-init.d/99-trusted_domains.sh: executing
[17:06:54] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available

                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   

[17:06:55] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[17:06:55] INFO: Trusted domains set in the configuration. Refreshing domains.
[17:06:55] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available

                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   

Error : /etc/cont-init.d/99-trusted_domains.sh exiting 1
 
Starting the upstream container
 
[custom-init] No custom files found, skipping...
crond: crond (busybox 1.36.1) started, log level 8
[ls.io-init] done.
crond: USER abc pid 1447 cmd /usr/bin/php /app/www/public/cron.php 2>&1
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
crond: USER abc pid 1865 cmd /usr/bin/php /app/www/public/cron.php 2>&1
crond: USER root pid 1866 cmd run-parts /etc/periodic/15min
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
crond: USER abc pid 2282 cmd /usr/bin/php /app/www/public/cron.php 2>&1
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, i'm sorry you should connect the support of nabu casa as it is a paid service... The addon simply exposes the port but if there is any specificity it would come from the nabu casa part, thanks

**Comment by a0zzy** [comment]
I would suggest a free reverse proxy service + freedns. Nextcloud is not going to be avaliable directly though nabu casa unfortunatley. 

[Localtunnel](https://theboroer.github.io/localtunnel-www/) is awesome and completley free. Also [Playit.gg](https://playit.gg/) but thats mostly for games...
and of course, [Freedns](https://freedns.afraid.org/) for a free subdomain to expose.

Using localtunnel would be finicky and you wouldn't be able to use a custom domain but playit.gg works really well and gives you an ip address that you might be able to assign a subdomain too (I have not tested.)

Effectively your best bet is to port forward nextcloud and use a subdomain from freedns and hide all of that behind cloudflare. Persoanlly, this is what I do. NetworkChuck on youtube has a great tutorial about cloudflare and port forwarding your local network. + I recommend NetworkChuck tutorials, he has a lot great content about self hosting and stuff in that ball park.

Cheers!

**Comment by a0zzy** [comment]
+ [NetworkChuck exposing tutorial](https://www.youtube.com/watch?v=ey4u7OUAF3c)
