### ISSUE TITLE
🐛 [Immich] Immich can't use NAS server, it can only access it in read mode

### ISSUE THREAD

**Issue by stefanuc111** [alexbelgium/hassio-addons#1279]
### Description

I have this configuration on home assistant but the plugin

DB_DATABASE_NAME: immich
DB_HOSTNAME: homeassistant.local
DB_PASSWORD: ****
DB_PORT: "5432"
DB_USERNAME: homeassistant
DISABLE_MACHINE_LEARNING: true
JWT_SECRET: ****
PGID: 0
PUID: 0
TZ: Europe/Paris
data_location: /mnt/HomeAssistantShare/immich
networkdisks: //192.168.5.1/FRITZ.NAS/TOSHIBA_EXT/HomeAssistantShare
cifspassword: ****
cifsusername: ****

### Reproduction steps

```bash
1. Go the web or mobile immich console
2. upload a photo
3. Photo is uploaded but no thumb is generated
```

### Addon Logs

```bash
[Nest] 1193  - 03/01/2024, 6:00:04 PM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-jpeg-thumbnail): Error: Input file contains unsupported image format
[Nest] 1193  - 03/01/2024, 6:00:04 PM   ERROR [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/app/immich/server/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.resize (/app/immich/server/dist/infra/repositories/media.repository.js:39:14)
    at MediaService.generateThumbnail (/app/immich/server/dist/domain/media/media.service.js:129:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGenerateJpegThumbnail (/app/immich/server/dist/domain/media/media.service.js:116:28)
    at async /app/immich/server/dist/domain/job/job.service.js:137:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 1193  - 03/01/2024, 6:00:04 PM   ERROR [JobService] Object:
{
  "id": "fc808f3f-fda9-4279-a7da-30ee8a8e4838",
  "source": "upload"
}
```

When trying to open the photos or download them I also have those log errors and photos are not displayed and download file is corrupted:

```
[Nest] 1137  - 03/01/2024, 6:00:07 PM     LOG [CommunicationRepository] Websocket Disconnect: Qjqu4yrBN_dNFmDdAAAD
[Nest] 1137  - 03/01/2024, 6:00:08 PM     LOG [CommunicationRepository] Websocket Connect:    -MAWu-C-EFu7ZNa1AAAF
[Nest] 1137  - 03/01/2024, 6:03:38 PM   ERROR [Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/library/admin/2020/2020-09-04/Portrait_6.jpg'] Failed to download file
[Nest] 1137  - 03/01/2024, 6:03:38 PM   ERROR [Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/library/admin/2020/2020-09-04/Portrait_6.jpg'] Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/library/admin/2020/2020-09-04/Portrait_6.jpg'
[Nest] 1137  - 03/01/2024, 6:03:38 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 1137  - 03/01/2024, 6:05:04 PM     LOG [CommunicationRepository] Websocket Connect:    RaQ56Tp2n-B0UGuIAAAH
[Nest] 1137  - 03/01/2024, 6:05:17 PM     LOG [CommunicationRepository] Websocket Disconnect: RaQ56Tp2n-B0UGuIAAAH
[Nest] 1137  - 03/01/2024, 6:05:18 PM     LOG [CommunicationRepository] Websocket Connect:    qTmYezbW7jacyzjgAAAJ
[Nest] 1193  - 03/01/2024, 6:05:21 PM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-jpeg-thumbnail): Error: /mnt/HomeAssistantShare/immich/library/admin/2023/2023-12-03/amigos-snap_2023-12-03_13-45-30.png: unable to open for read
unix error: Stale file handle
/mnt/HomeAssistantShare/immich/library/admin/2023/2023-12-03/amigos-snap_2023-12-03_13-45-30.png: unable to open for read
unix error: Stale file handle
pngload: stream error
[Nest] 1193  - 03/01/2024, 6:05:21 PM   ERROR [JobService] Error: /mnt/HomeAssistantShare/immich/library/admin/2023/2023-12-03/amigos-snap_2023-12-03_13-45-30.png: unable to open for read
unix error: Stale file handle
/mnt/HomeAssistantShare/immich/library/admin/2023/2023-12-03/amigos-snap_2023-12-03_13-45-30.png: unable to open for read
unix error: Stale file handle
pngload: stream error
    at Sharp.toFile (/app/immich/server/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.resize (/app/immich/server/dist/infra/repositories/media.repository.js:39:14)
    at MediaService.generateThumbnail (/app/immich/server/dist/domain/media/media.service.js:129:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGenerateJpegThumbnail (/app/immich/server/dist/domain/media/media.service.js:116:28)
    at async /app/immich/server/dist/domain/job/job.service.js:137:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 1193  - 03/01/2024, 6:05:21 PM   ERROR [JobService] Object:
{
  "id": "bf0415ef-7cd6-448c-abe2-bc653c163bf6",
  "source": "upload"
}

```

### Architecture

aarch64

### OS

HAos

**Comment by stefanuc111** [comment]
When checking from the NAS the photos are available and I can correctly view them

**Comment by blendrik** [comment]
My first guess would be something like this:

https://askubuntu.com/questions/1265164/stale-file-handler-when-mounting-cifs-smb-network-drive-from-fritz-router
https://debianforum.de/forum/viewtopic.php?t=176154

**Comment by blendrik** [comment]
From https://linux.die.net/man/8/mount.cifs

> noserverino
> Client generates inode numbers itself rather than using the actual ones from the server.

**Comment by stefanuc111** [comment]
<img width="1440" alt="image" src="https://github.com/alexbelgium/hassio-addons/assets/1716030/2f72c086-73e4-4365-8896-2479bc50e8af">
I've actually noticed that some times seem to work. But the other photos without the thumbnail  doesn't even open, even if the files is correctly stored on the HDD

**Comment by blendrik** [comment]
Did you try the "noserverino" mount option?

**Comment by stefanuc111** [comment]
> From https://linux.die.net/man/8/mount.cifs
> 
> > noserverino
> > Client generates inode numbers itself rather than using the actual ones from the server.

No, how can I try?

**Comment by blendrik** [comment]
Obviously, it is added to the script already:
https://github.com/alexbelgium/hassio-addons/issues?q=noserverino

Someone else had a similar issue: https://github.com/alexbelgium/hassio-addons/issues/813

Try this:

> Fortunately I could fix it by myself with a small hack: Just add ,noserverino as a suffix in the smb password field. This solution works, but is not elegant. I would recommend an own mountoption field in the advanced options, because I have no idea how to test reliably for server or client index nodes usage.

**Comment by stefanuc111** [comment]
Hi, 

> Obviously, it is added to the script already: https://github.com/alexbelgium/hassio-addons/issues?q=noserverino
> 
> Someone else had a similar issue: #813
> 
> Try this:
> 
> > Fortunately I could fix it by myself with a small hack: Just add ,noserverino as a suffix in the smb password field. This solution works, but is not elegant. I would recommend an own mountoption field in the advanced options, because I have no idea how to test reliably for server or client index nodes usage.

The trick is actually working now it's saving and generating thumb correctly, many thanks! 
Should be a  separate option for the mounting options be added in future ?

**Comment by blendrik** [comment]
Excellent! Glad I could help.

That's a question only @alexbelgium can answer.

**Comment by stefanuc111** [comment]
This is the log when I upload a photo
```
[Nest] 1273  - 03/04/2024, 6:40:52 PM   ERROR [Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/09/ae/09aed2dc-160a-42b4-a30b-afaca948557c.webp'] Failed to get asset thumbnail
[Nest] 1273  - 03/04/2024, 6:40:52 PM   ERROR [Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/09/ae/09aed2dc-160a-42b4-a30b-afaca948557c.webp'] Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/09/ae/09aed2dc-160a-42b4-a30b-afaca948557c.webp'
[Nest] 1273  - 03/04/2024, 6:40:52 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 1273  - 03/04/2024, 6:41:15 PM     LOG [CommunicationRepository] Websocket Disconnect: Dg0QcSP4ozx6ANIOAAAH
[Nest] 1273  - 03/04/2024, 6:41:18 PM     LOG [CommunicationRepository] Websocket Connect:    X3Ha9BoI3gl5mP4nAAAN
[Nest] 1321  - 03/04/2024, 6:41:19 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset b1db84aa-218b-4bac-84f4-dcfb1916bb2d
[Nest] 1321  - 03/04/2024, 6:41:19 PM   ERROR [JobService] Unable to run job handler (smartSearch/smart-search): Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.jpeg'
[Nest] 1321  - 03/04/2024, 6:41:19 PM   ERROR [JobService] Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.jpeg'
[Nest] 1321  - 03/04/2024, 6:41:19 PM   ERROR [JobService] Object:
{
  "id": "b1db84aa-218b-4bac-84f4-dcfb1916bb2d",
  "source": "upload"
}

[Nest] 1321  - 03/04/2024, 6:41:19 PM   ERROR [JobService] Unable to run job handler (faceDetection/face-detection): Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.jpeg'
[Nest] 1321  - 03/04/2024, 6:41:19 PM   ERROR [JobService] Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.jpeg'
[Nest] 1321  - 03/04/2024, 6:41:19 PM   ERROR [JobService] Object:
{
  "id": "b1db84aa-218b-4bac-84f4-dcfb1916bb2d",
  "source": "upload"
}

[Nest] 1321  - 03/04/2024, 6:41:20 PM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-thumbhash-thumbnail): Error: Input file contains unsupported image format
[Nest] 1321  - 03/04/2024, 6:41:20 PM   ERROR [JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/app/immich/server/node_modules/sharp/lib/output.js:161:17)
    at MediaRepository.generateThumbhash (/app/immich/server/dist/infra/repositories/media.repository.js:118:14)
    at MediaService.handleGenerateThumbhashThumbnail (/app/immich/server/dist/domain/media/media.service.js:166:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/job/job.service.js:137:37
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 1321  - 03/04/2024, 6:41:20 PM   ERROR [JobService] Object:
{
  "id": "b1db84aa-218b-4bac-84f4-dcfb1916bb2d",
  "source": "upload"
}

[Nest] 1321  - 03/04/2024, 6:41:20 PM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset b1db84aa-218b-4bac-84f4-dcfb1916bb2d
[Nest] 1273  - 03/04/2024, 6:41:22 PM   ERROR [Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.webp'] Failed to get asset thumbnail
[Nest] 1273  - 03/04/2024, 6:41:22 PM   ERROR [Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.webp'] Error: Unknown system error -116: Unknown system error -116, open '/mnt/HomeAssistantShare/immich/thumbs/6d90c831-1eac-4b75-a275-69c6a6e004a4/b1/db/b1db84aa-218b-4bac-84f4-dcfb1916bb2d.webp'
[Nest] 1273  - 03/04/2024, 6:41:22 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
```

**Comment by stefanuc111** [comment]
My PGID and PUID are set to 0, I think when they were  "1000" I had other issues

**Comment by stefanuc111** [comment]
> My PGID and PUID are set to 0, I think when they were "1000" I had other issues

Actually I've switched back the PGID and PUID to 1000 and it works normally (with the noserverino option)
