### ISSUE TITLE
🐛 [Scrutiny full access] update not possible

### ISSUE THREAD

**Issue by dm82m** [alexbelgium/hassio-addons#1305]
### Description

Update throws an error:
![IMG_6117](https://github.com/alexbelgium/hassio-addons/assets/736311/f83e06de-388b-4ff6-9114-ecdb4ff673ac)

### Reproduction steps

```bash
Just click on install
```

### Addon Logs

```bash
See screenshot
```

### Architecture

amd64

### OS

HAos

**Comment by dm82m** [comment]
Your last changes broke the build:

ERROR: failed to solve: process "/usr/bin/bash -c curl -f -L -s -S \"[https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/ha_automodules.sh\](https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/ha_automodules.sh/)" -o /ha_automodules.sh &&     chmod 744 /ha_automodules.sh && /ha_automodules.sh \"$MODULES\" && rm /ha_automodules.sh" did not complete successfully: exit code: 127

**Comment by alexbelgium** [comment]
Hi, it's super weird I change that because the previous code stopped working spe ifically for this addon, and not the others. I had a ADD command previously but it also resulted in a file not found error. Super weird why it works for all other addons

**Comment by chertvl** [comment]
Same for non-full-access version ;)

**Comment by alexbelgium** [comment]
Yes must be linked to the Scrutiny image and not my code as all the other addons build normally...

**Comment by davlaw** [comment]
FWIW, I have another device that has had its github messed up, I had read reports of malware being spread by unknowing github accounts.  So playing devil's advocate maybe there is something more at play here

**Comment by nepozs** [comment]
maybe this log can help? (fresh install also impossible)
````
 Can't install ghcr.io/alexbelgium/scrutiny-amd64:v0.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=v0.8.0&fromImage=ghcr.io%2Falexbelgium%2Fscrutiny-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown") 
```

**Comment by alexbelgium** [comment]
Hi, thanks I have the solution : the upstream maintainer is using debian slim which uses /usr/bin instead of /bin. I've corrected all my code to align with this situation and the images are now building

**Comment by AndrewNovikov** [comment]
Now the update is possible but the image cannot be started after the update with message "exec /init: too many levels of symbolic links"
![Screenshot_2024-03-17-10-17-45-085_io homeassistant companion android-edit](https://github.com/alexbelgium/hassio-addons/assets/508211/fec779fb-c211-427b-9f17-96971788a97f)

**Comment by dm82m** [comment]
yes, can confirm that, update works but add-on is not startable afterwards. reverted back to last working version.

**Comment by icovelev** [comment]
Same here.

exec /init: too many levels of symbolic links.

<img width="1470" alt="Screenshot 2024-03-17 at 12 32 29 PM" src="https://github.com/alexbelgium/hassio-addons/assets/31531311/7d63613d-06ba-45ea-b31f-6e36f9a2c3aa">

Log from Supervisor

```shell
24-03-17 12:24:41 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/scrutiny-fa-aarch64 with version v0.8.0
24-03-17 12:24:53 WARNING (MainThread) [supervisor.docker.addon] Scrutiny (Full Access) running with disabled protected mode!
24-03-17 12:24:53 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_db21ed7f_scrutiny_fa application
24-03-17 12:24:53 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-86982' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1387> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1401, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
24-03-17 12:24:53 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-86990' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1387> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1401, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```

**Comment by alexbelgium** [comment]
Thanks should be good in latest! At least tested on my system

**Comment by chertvl** [comment]
> Thanks should be good in latest! At least tested on my system

Seems ok from my side, thank you!

**Comment by dm82m** [comment]
Back working, thanks!

**Comment by icovelev** [comment]
Scrutiny (Full Access) is still on v0.8.0. Could you please push the update to it too.

<img width="1080" alt="Screenshot 2024-03-17 at 2 15 31 PM" src="https://github.com/alexbelgium/hassio-addons/assets/31531311/6f2ee878-b54a-410d-ba49-4243e8cbc786">
<img width="1057" alt="Screenshot 2024-03-17 at 2 15 23 PM" src="https://github.com/alexbelgium/hassio-addons/assets/31531311/1362789d-15f9-48f2-bffb-b7d907589e62">

**Comment by dm82m** [comment]
It is not, refresh your addons:
![IMG_6123](https://github.com/alexbelgium/hassio-addons/assets/736311/063796d1-300e-4f39-884e-16d1d68dd9ff)
