### ISSUE TITLE
[epicgamesfree]  Failed to lookup weekly free games

### ISSUE THREAD

**Issue by brashenfr** [alexbelgium/hassio-addons#1328]
### Description

Failed to lookup weekly free games

### Reproduction steps

```bash
Hi, installed and set up Epic Games free but i have an issue with it Current version: debian-2024-03-17 from alexbelgium repository
I spend hours looking for solutions but nothing yet...
any ideas ?
```

### Addon Logs

```bash
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory


Load environment variables from /config/addons_config/epicgamesfree/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/epicgamesfree/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
TZ='Europe/Paris'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /homeassistant/addons_config/epicgamesfree/epicgamesfree.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/99-run.sh: executing
[15:39:53] WARNING: The config.json file found in /config/addons_config/epicgamesfree will be used. Please customize according to https://github.com/claabs/epicgames-freegames-node#json-configuration and restart the add-on
 
[15:39:53] INFO: Starting the app
 
 
Starting the upstream container
 
Setting localtime: Europe/Paris
Setting timezone: Europe/Paris
Run on startup: true
[2024-03-30 15:40:12.170 +0100] INFO: Started epicgames-freegames-node
    COMMIT_SHA: "54c98a7c5e5d6b04d2be9f336a319be1b24c876d"
    BRANCH: "master"
    DISTRO: "alpine"
[2024-03-30 15:40:13.039 +0100] WARN: A newer version of epicgames-freegames-node is available! `docker pull` this image to update.
[2024-03-30 15:40:13.066 +0100] INFO: Checking free games for *****@gmail.com 
    user: "*****@gmail.com"
[2024-03-30 15:40:17.661 +0100] INFO: searchStrategy is `all`: searching for weekly and promotional games
    user: "*****@gmail.com"
[2024-03-30 15:41:26.349 +0100] ERROR: Encountered an error during browser automation. Saved a screenshot for debugging purposes.
    user: "*****@gmail.com"
    errorFile: "error-2024-03-30T14:40:58.156Z.png"
[2024-03-30 15:41:27.073 +0100] WARN: Failed to lookup weekly free games
    user: "*****@gmail.com"
    err: {
      "type": "TimeoutError",
      "message": "Navigation timeout of 30000 ms exceeded",
      "stack":
          TimeoutError: Navigation timeout of 30000 ms exceeded
              at Deferred (/usr/app/node_modules/puppeteer-core/src/util/Deferred.ts:73:28)
              at Function.create (/usr/app/node_modules/puppeteer-core/src/util/Deferred.ts:29:12)
              at LifecycleWatcher (/usr/app/node_modules/puppeteer-core/src/cdp/LifecycleWatcher.ts:170:42)
              at CdpFrame.goto (/usr/app/node_modules/puppeteer-core/src/cdp/Frame.ts:140:21)
              at CdpFrame.<anonymous> (/usr/app/node_modules/puppeteer-core/src/util/decorators.ts:63:21)
              at CdpPage.goto (/usr/app/node_modules/puppeteer-core/src/api/Page.ts:1581:35)
              at PuppetFreeGames.setupPage (/usr/app/src/puppet/base.ts:76:18)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at PuppetFreeGames.request (/usr/app/src/puppet/free-games.ts:35:19)
              at PuppetFreeGames.getWeeklyFreeGames (/usr/app/src/puppet/free-games.ts:148:18)
      "name": "TimeoutError"
    }
[2024-03-30 15:42:25.323 +0100] ERROR: Encountered an error during browser automation. Saved a screenshot for debugging purposes.
    user: "*****@gmail.com"
    errorFile: "error-2024-03-30T14:42:07.492Z.png"
[2024-03-30 15:42:26.000 +0100] WARN: Failed to lookup catalog free games
    user: "*****@gmail.com"
    err: {
      "type": "TimeoutError",
      "message": "Navigation timeout of 30000 ms exceeded",
      "stack":
          TimeoutError: Navigation timeout of 30000 ms exceeded
              at Deferred (/usr/app/node_modules/puppeteer-core/src/util/Deferred.ts:73:28)
              at Function.create (/usr/app/node_modules/puppeteer-core/src/util/Deferred.ts:29:12)
              at LifecycleWatcher (/usr/app/node_modules/puppeteer-core/src/cdp/LifecycleWatcher.ts:170:42)
              at CdpFrame.goto (/usr/app/node_modules/puppeteer-core/src/cdp/Frame.ts:140:21)
              at CdpFrame.<anonymous> (/usr/app/node_modules/puppeteer-core/src/util/decorators.ts:63:21)
              at CdpPage.goto (/usr/app/node_modules/puppeteer-core/src/api/Page.ts:1581:35)
              at PuppetFreeGames.setupPage (/usr/app/src/puppet/base.ts:76:18)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at PuppetFreeGames.request (/usr/app/src/puppet/free-games.ts:35:19)
              at PuppetFreeGames.getCatalogFreeGames (/usr/app/src/puppet/free-games.ts:98:28)
      "name": "TimeoutError"
    }
[2024-03-30 15:42:26.229 +0100] ERROR: Both free game API lookups failed
    user: "*****@gmail.com"
    err: {
      "type": "Error",
      "message": "Both free game API lookups failed",
      "stack":
          Error: Both free game API lookups failed
              at PuppetFreeGames.getAllFreeGames (/usr/app/src/puppet/free-games.ts:414:15)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at redeemAccount (/usr/app/src/index.ts:46:20)
              at async file:///usr/app/node_modules/p-queue/dist/index.js:187:36
    }
[2024-03-30 15:42:26.266 +0100] WARN: Current version
    COMMIT_SHA: "54c98a7c5e5d6b04d2be9f336a319be1b24c876d"
    BRANCH: "master"
    DISTRO: "alpine"
[2024-03-30 15:42:26.272 +0100] INFO: Exiting successfully
Run once: false
Setting cron schedule as 0 0,6,12,18 * * *
```

### Architecture

aarch64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, I've tried pushing the latest version fid it change anything?

**Comment by brashenfr** [comment]
Hi Alex, thank you i have seen it and installed but nothing changed

**Comment by alexbelgium** [comment]
Hi, I'm sorry it was the only error I was seeing on which I thought I could have an action. Would it be possible for you to create an issue on the upstream repo here : https://github.com/claabs/epicgames-freegames-node/issues ? Hopefully they will be able to better help you or identify which could be the issue - thanks very much

**Comment by brashenfr** [comment]
> Actually, could you please try this solution? Thanks!
> 
> [#675 (comment)](https://github.com/alexbelgium/hassio-addons/issues/675#issuecomment-1407675351)

This solution Works, thank you so much
