### ISSUE TITLE
🐛 Firefly III] Addon not starting

### ISSUE THREAD

**Issue by Ycer0n** [alexbelgium/hassio-addons#1343]
### Description

FireflyIII doesn't start anymore, everything used to be fine a couple days ago.
Getting the following errors when trying to start the fireflyIII addon.

After disabling watchdog, the logs changed to the following:

2024-04-11 22:08:35.544 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:08:39.799 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-3457' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-04-11 22:08:39.803 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:11:49.250 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:12:08.552 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-4433' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-04-11 22:12:08.555 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:13:16.681 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:13:31.744 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13

### Reproduction steps

```bash
1. Start fireflyIII
```

### Addon Logs

```bash
2024-04-11 22:02:08.333 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:02:08.335 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:02:08.338 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:02:39.749 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-04-11 22:03:02.699 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:03:02.702 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:03:02.706 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:03:20.769 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:03:20.772 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:03:20.776 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:03:28.154 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:03:28.157 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:03:28.161 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:03:48.825 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:03:48.829 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:03:48.833 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:03:59.892 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:03:59.895 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:03:59.899 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:04:02.301 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:04:02.304 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:04:02.308 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:04:14.275 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:04:14.278 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Firefly iii is stopped, restarting...
2024-04-11 22:04:14.284 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:04:22.568 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state startup
2024-04-11 22:04:22.568 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-11 22:04:23.704 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2043' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-04-11 22:04:23.712 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
```

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, could you please try disabling the watchdog and restarting? Thanks

**Comment by Ycer0n** [comment]
Hi

Without watchdog, I get the same issue, but the logs below instead.

`2024-04-11 22:08:35.544 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:08:39.799 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-3457' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
await self._restart_after_problem(event.state)
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-04-11 22:08:39.803 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:11:49.250 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:12:08.552 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-4433' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
await self._restart_after_problem(event.state)
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-04-11 22:12:08.555 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13
2024-04-11 22:13:16.681 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_db21ed7f_fireflyiii application
2024-04-11 22:13:31.744 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/alexbelgium/fireflyiii-aarch64 with version 6.1.13`

**Comment by alexbelgium** [comment]
This is supervisor's log but do you have anything also in the addon log of either Firefly III or Mariadb ?

I can't replicate this issue. If there is no addon logs at all, you might try : restarting mariadb addon first (in case it's dependency is not working) ; changing firefly iii port before restarting (if it is a port incompatibility) ; rebooting the device (in case of random issue); or running `ha su repair` in the Terminal addon (will repair all addon images)

Currently it's quite challenging to understand what would be the issue...

**Comment by Ycer0n** [comment]
Thanks
I can't seem to find a way to fix it, so I guess I'll wait for an update to fix it

**Comment by alexbelgium** [comment]
And you have no logs in either firefly iii nor mariadb?

**Comment by Ycer0n** [comment]
Firefly III logs say "No errors have been reported"
I'm using sqlite_internal instead of mariadb, not sure if there's any logs for that?

**Comment by alexbelgium** [comment]
> Firefly III logs say "No errors have been reported" I'm using sqlite_internal instead of mariadb, not sure if there's any logs for that?

Just for sake of leaving no stone unturned could you please post your log? Just to be sure thanks. In case there is an exit 1 in one of the startup script that firefly doesn't see

**Comment by Ycer0n** [comment]
This is the only thing I'm getting. If I download it, I just get an empty file.
![image](https://github.com/alexbelgium/hassio-addons/assets/37674033/2c5f2db6-4870-44c8-add6-6667ccf6d1c9)

Not sure if there's any other logs I'm missing?
