### ISSUE TITLE
🐛 [Sonarr/Radarr/Jellyfin] Jellyfin notifications broken

### ISSUE THREAD

**Issue by leokeba** [alexbelgium/hassio-addons#1348]
### Description

Hi, I'm trying to configure Radarr and Sonarr so they notify Jellyfin when something changes so I don't have to manually sync the library each time a download finishes.

Thankfully, it seems that this issue just got fixed in both latest releases, so I guess all you have to do is update the docker image. See [here](https://github.com/Sonarr/Sonarr/issues/6558)

### Reproduction steps

```bash
1. Add Jellyfin Connection to Radarr / Sonarr in the Settings/Connect tab.
2. Download something.
3. Check if Jellyfin gets updated.
```

### Addon Logs

```bash
2024-04-19 02:33:04.2|Error|EventAggregator|NotificationService failed while processing [ManualInteractionRequiredEvent]

[v4.0.3.1486] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./api/hassio_ingress/sWUvo1N8wuXaXPQJAAJWO8buuZ3InluvENx0QYs4Dgw/sonarr.Core/Notifications/NotificationService.cs:line 236
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

2024-04-19 02:33:04.8|Error|EventAggregator|NotificationService failed while processing [ManualInteractionRequiredEvent]

[v4.0.3.1486] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./api/hassio_ingress/sWUvo1N8wuXaXPQJAAJWO8buuZ3InluvENx0QYs4Dgw/sonarr.Core/Notifications/NotificationService.cs:line 236
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

2024-04-19 02:33:04.9|Error|EventAggregator|NotificationService failed while processing [ManualInteractionRequiredEvent]

[v4.0.3.1486] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./api/hassio_ingress/sWUvo1N8wuXaXPQJAAJWO8buuZ3InluvENx0QYs4Dgw/sonarr.Core/Notifications/NotificationService.cs:line 236
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```

### Architecture

armv7

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, thanks for reporting! Automatic updates are this night so we'll soon be able to check if it works again! If it foesn't update automatically i'll trigger it manually.

**Comment by leokeba** [comment]
Thanks, I just tried today after updating, but the error persists. I'm getting the same errors, but I'm not even sure these are really about the notifications supposed to go to Jellyfin. Does anybody else have a similar issue ?

**Comment by alexbelgium** [comment]
Hi, I'm not using directly the Sonarr image but one distributed by linuxserver (https://github.com/linuxserver/docker-sonarr) so perhaps there is a lag time between the moment where it is pushed in the initial repo and the moment where linuxserver updates it! Let's see next week ;-)
