### ISSUE TITLE
❓ [Immich] can not update from 1.105.1 to  1.106.4-2 

### ISSUE THREAD

**Issue by peeter22** [alexbelgium/hassio-addons#1448]
**Immich?**

I have trouble updating Immich to the latest version.

I get this error in the GUI of HA 
`Failed to call service update/install. Error updating Immich: Can't install ghcr.io/alexbelgium/immich-amd64:1.106.4-2: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/alexbelgium/immich-amd64:1.106.4-2/json: Not Found ("No such image: ghcr.io/alexbelgium/immich-amd64:1.106.4-2")
`

And not sure if that is related but this in the log of the addon itself

```
      '5'
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'immich_bull:facialRecognition:wait',
      'immich_bull:facialRecognition:active',
      '5'
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'immich_bull:faceDetection:wait',
      'immich_bull:faceDetection:active',
      '5'
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'immich_bull:metadataExtraction:wait',
      'immich_bull:metadataExtraction:active',
      '5'
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. script: b4cd4bbdf096cd8d06246080315ae81c56e05a46, on @user_script:222.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      'b4cd4bbdf096cd8d06246080315ae81c56e05a46',
      '10',
      'immich_bull:sidecar:wait',
      'immich_bull:sidecar:active',
      'immich_bull:sidecar:prioritized',
      'immich_bull:sidecar:events',
      'immich_bull:sidecar:stalled',
      'immich_bull:sidecar:limiter',
      'immich_bull:sidecar:delayed',
      'immich_bull:sidecar:paused',
      'immich_bull:sidecar:meta',
      'immich_bull:sidecar:pc',
      'immich_bull:sidecar:',
      '1719221664403',
      '',
      <Buffer de 00 03 a5 74 6f 6b 65 6e d9 2a 63 61 30 64 66 32 66 61 2d 34 33 38 37 2d 34 66 39 63 2d 62 32 34 61 2d 34 66 64 31 30 39 32 35 64 37 66 30 3a 31 32 ... 28 more bytes>
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'immich_bull:migration:wait',
      'immich_bull:migration:active',
      '5'
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'immich_bull:notifications:wait',
      'immich_bull:notifications:active',
      '5'
    ]
  }
}
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/immich/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/immich/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'immich_bull:videoConversion:wait',
      'immich_bull:videoConversion:active',
      '5'
    ]
  }
}
```

**Comment by alexbelgium** [comment]
Hi, mmh it is here so it exists : "https://github.com/alexbelgium/hassio-addons/pkgs/container/immich-amd64"

Perhaps try rebooting ?

**Comment by peeter22** [comment]
Hey.
Unfortunately reboot did not help. This issue persist for more than a week. In the meantime I have rebooted several times and also updated the HA OS and core but I end with this error all the time.

**Comment by alexbelgium** [comment]
Crazy... Well I can try to push a new version and we'll see how that goes

**Comment by peeter22** [comment]
Thanks for the new version but it still does not work
`
Failed to call service update/install. Error updating Immich: Can't install ghcr.io/alexbelgium/immich-amd64:1.106.4-3: 404 Client Error for http+docker://localhost/v1.45/images/ghcr.io/alexbelgium/immich-amd64:1.106.4-3/json: Not Found ("No such image: ghcr.io/alexbelgium/immich-amd64:1.106.4-3")`

Maybe tomorrow I will try to roll back to an older version from backup to see if that helps.

**Comment by peeter22** [comment]
Unfortunatelly I still was not able to get it working. Even when downgrading to an older version I get the same error.
I would not mind the old version, but as  iOs can not roll back to older versions of the app I can not use Immich on my phone.
What would be you suggestion to do ? How could I reinstall Immich most effectively, without having to reupload all the phtos again ?

**Comment by alexbelgium** [comment]
All should be good now hopefully
