### ISSUE TITLE
[Issue] Jellyfin transcoding transcoding rights?

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#145]
Hi Alex,

I notice when restarting the jellyfin addon that there might be issue with rights on transcoding perhaps?
Or is it executed?

```
creating link for /jellyfin/root
[cont-init.d] 20-folders: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
**[cont-init.d] 40-gid-video: executing... 
**** The device /dev/dri/card1 does not have group read/write permissions, which might prevent hardware transcode from functioning correctly. To fix it, you can run the following on your docker host: ****
sudo chmod g+rw /dev/dri/card1
**** The device /dev/dri/renderD128 does not have group read/write permissions, which might prevent hardware transcode from functioning correctly. To fix it, you can run the following on your docker host: ****
sudo chmod g+rw /dev/dri/renderD128
**** The device /dev/dri/card0 does not have group read/write permissions, which might prevent hardware transcode from functioning correctly. To fix it, you can run the following on your docker host: ****
sudo chmod g+rw /dev/dri/card0**
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 92-smb_mounts.sh: executing... 
[11:46:13] INFO: Mounting smb share(s)...
```

**Comment by alexbelgium** [comment]
Hi, I've pushed a new version that should solve it thanks to https://github.com/linuxserver/docker-jellyfin/pull/134/commits/39d6a2091e39f822cbc41fe122861239003e4f8a

**Comment by alexbelgium** [comment]
I'll close it as it seems directly linked to the linuxserver issue solved in this version

**Comment by deku-m** [comment]
After yesterday update i can't login anymore server is broken.

```
[cont-init.d] 00-ha-env.sh: executing... 
/var/run/s6/etc/cont-init.d/00-ha-env.sh: line 3: __BASHIO_ADDON_CONFIG: unbound variable

```
and:

```
[23:54:12] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[23:54:13] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:13] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:13] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[23:54:15] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:15] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:15] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[23:55:17] [ERR] [28] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:55:17] [INF] [28] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for mklcln has been denied (IP: 192.168.1.36).
[23:55:17] [ERR] [28] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/AuthenticateByName.
[23:55:21] [ERR] [23] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:55:21] [INF] [23] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for mklcln has been denied (IP: 192.168.1.36).
[23:55:21] [ERR] [23] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/AuthenticateByName.
[23:57:12] [ERR] [41] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:57:12] [INF] [41] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for mklcln has been denied (IP: 192.168.1.48).
[23:57:12] [ERR] [41] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
[23:57:20] [ERR] [41] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:57:20] [INF] [41] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for Patricia has been denied (IP: 192.168.1.48).
[23:57:20] [ERR] [41] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
```

**Comment by alexbelgium** [comment]
Actually it won't solve the issue directly : linuxserver has pushed the solution in their nightly and not their latest tag, so it will take a few days for it to arrives on latest
