### ISSUE TITLE
🐛 [Immich] <Folder creation error>

### ISSUE THREAD

**Issue by YugiFanGX** [alexbelgium/hassio-addons#1481]
### Description

No library folder gets created when installing immich on HA Supervised.

### Reproduction steps

```bash
On clean system

1. Install Postgres (after configuration)
2. Install Immich (after configuration)
3. Check the logs
4. See error: 'EACCES: permission denied' for config/share/immich/libary folder
```

### Addon Logs

```bash
Error: EACCES: permission denied, mkdir '/share/immich/library'
    at mkdirSync (node:fs:1372:26)
    at StorageRepository.mkdirSync (/app/immich/server/dist/repositories/storage.repository.js:122:37)
    at StorageService.onBootstrapEvent (/app/immich/server/dist/services/storage.service.js:32:32)
    at EventRepository.emit (/app/immich/server/dist/repositories/event.repository.js:73:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApiModule.onModuleInit (/app/immich/server/dist/app.module.js:68:9)
    at async callModuleInitHook (/app/immich/server/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/app/immich/server/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/app/immich/server/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/app/immich/server/node_modules/@nestjs/core/nest-application.js:169:33) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/share/immich/library'
}
```

### Architecture

amd64

### OS

HAos

**Comment by YugiFanGX** [comment]
Workaround - easy.

'mkdir library' as default user.

**Comment by YugiFanGX** [comment]
Workaround currently is to use root users' PGID and PUID

**Comment by PrathikGopal** [comment]
Had to run chown -R 1000:1000 /Immich/ 

on the media folder as a Manual fix.

**Comment by alexbelgium** [comment]
hi, thanks for reporting and the solutions !

I don't remember, can we run immich with PUID 0 and PGID 0? It would be even easier
Otherwise I'll look if I can implement your solution in the code.

**Comment by kool2zero** [comment]
@PrathikGopal , what is your setup.  I have Windows as a host and HAOS in a Hyper-V machine.  My files are stored on an attached USB drive (Windows, exFAT).  I can see that the owner for the immich directory is hassio when it is created within the VM. But it is created as root when accessing on a network location (in this case the USB drive).  When I try to chown it stays as root.  Is this because it is a windows based disk?  @alexbelgium , is there a way to get around this?

**Comment by kool2zero** [comment]
Nevermind:  followed this... https://github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-mounting-drives
