### ISSUE TITLE
[Issue] Jellyfin login problem after new update

### ISSUE THREAD

**Issue by deku-m** [alexbelgium/hassio-addons#151]
After yesterday update i can't login anymore server looks broken.
 Notice on thing in run:
```
[cont-init.d] 00-ha-env.sh: executing... 
/var/run/s6/etc/cont-init.d/00-ha-env.sh: line 3: __BASHIO_ADDON_CONFIG: unbound variable

```
and in jellyfin build from linuxserver could also be in there.:

```
[23:54:12] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[23:54:13] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:13] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:13] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[23:54:15] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:15] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[23:54:15] [INF] [4] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[23:55:17] [ERR] [28] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:55:17] [INF] [28] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for mklcln has been denied (IP: 192.168.1.36).
[23:55:17] [ERR] [28] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/AuthenticateByName.
[23:55:21] [ERR] [23] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:55:21] [INF] [23] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for mklcln has been denied (IP: 192.168.1.36).
[23:55:21] [ERR] [23] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/AuthenticateByName.
[23:57:12] [ERR] [41] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:57:12] [INF] [41] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for mklcln has been denied (IP: 192.168.1.48).
[23:57:12] [ERR] [41] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
[23:57:20] [ERR] [41] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[23:57:20] [INF] [41] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for Patricia has been denied (IP: 192.168.1.48).
[23:57:20] [ERR] [41] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
```

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. Could you please post your full addon log? Thanks

**Comment by alexbelgium** [comment]
Well it works on my system... It boots without issues... I'll push a new version to see if it helps

**Comment by alexbelgium** [comment]
There was a typo, you should copy your /config/jellyfin folder to /config/addons_config/jellyfin (for example using my addon filebrowser). Or just restore your more recent copy of your /config folder.

**Comment by deku-m** [comment]
Thanks that did the trick. 
Might it have been caused by migrating to addons_config right?

**Comment by alexbelgium** [comment]
Yes indeed there was a typo and it did not copy properly the config :) thanks!
