### ISSUE TITLE
[Feature Request] TandoorRecipes

### ISSUE THREAD

**Issue by davoloko** [alexbelgium/hassio-addons#153]
Hi @alexbelgium, first thank you for the excellent work and for your addons!
I have tested mealy and I think that some functions are missing.... I found this other docker and I think it would be perfect. is there a possibility to add it?

[TandoorRecipes](https://github.com/TandoorRecipes/recipes)

Thanks!!!

**Comment by alexbelgium** [comment]
Hi, I'll look at it in the coming days

**Comment by alexbelgium** [comment]
I've pushed a new version could you please test? thanks

**Comment by davoloko** [comment]
Hi!
Thank you very much for the addon! When I try to start it I get this error. I have tried with the mariaDB addon and with slqlite and it shows the same error:

[20:51:53] INFO: Defining database
[20:51:53] INFO: Using a local sqlite database
Moving data directory
ln: opt/recipes/media: No such file or directory
/scripts/99-run.sh: exiting 1

**Comment by alexbelgium** [comment]
OK! I've pushed a version 1.0.4 and it fully works :) sqlite database and images are stored in /config/addons_config/tandoor_recipes

**Comment by deku-m** [comment]
Installing fails at my side:

`The command '/bin/sh -c if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash); fi &&     if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl); fi &&     mkdir -p /tmpscripts /etc/cont-init.d &&     for scripts in $MODULES; do curl -L -f -s "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/zzz_templates/$scripts" -o /tmpscripts/"$scripts"; done  &&     if [ -d /etc/cont-init.d ]; then /bin/cp -rf /tmpscripts/* /etc/cont-init.d/ && chmod -R 755 /etc/cont-init.d; fi &&     if [ -d /scripts ]; then /bin/cp -rf /tmpscripts/* /scripts/ && chmod -R 755 /scripts; fi &&     rm -rf /tmpscripts || printf '%s\n' "${MODULES:-}" > /MODULESFILE' returned a non-zero code: 2`

**Comment by alexbelgium** [comment]
Thanks! I did an automated change that makes all addon fail to install ;) I'll push a new version with correction in 2 hours

**Comment by alexbelgium** [comment]
Should be corrected in 1.0.4-2

**Comment by alexbelgium** [comment]
Testing it now

**Comment by alexbelgium** [comment]
Weirdest issue ever. Vscode online gave me non compliant blank characters. Should be fixed for this addon

**Comment by alexbelgium** [comment]
Thanks for the feedback! should I remove mariadb and psgsql functions if they are not needed? No use to complexify the addon it is only a source of error :-)

**Comment by alexbelgium** [comment]
Mariadb should work in 1.0.4-4 that I have just pushed ; there was a typo

**Comment by davoloko** [comment]
hi!
I have updated and when configuring the mariadb I get the following error. I think it is a good idea to leave only sqlite as bbdd, this way, when backup is done, it is done of the complete addon.
I used to use mariadb for HA but in the end I stopped using it for sqlite as well.

File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
Done
[2022-01-14 11:27:33 +0100] [176] [INFO] Starting gunicorn 20.1.0
[2022-01-14 11:27:33 +0100] [176] [INFO] Listening at: http://0.0.0.0:8080 (176)
[2022-01-14 11:27:33 +0100] [176] [INFO] Using worker: sync
[2022-01-14 11:27:33 +0100] [181] [INFO] Booting worker with pid: 181
[2022-01-14 11:27:33 +0100] [181] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/recipes/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/recipes/recipes/wsgi.py", line 15, in <module>
    _application = get_wsgi_application()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
[2022-01-14 11:27:33 +0100] [181] [INFO] Worker exiting (pid: 181)
[2022-01-14 11:27:33 +0100] [176] [INFO] Shutting down: Master
[2022-01-14 11:27:33 +0100] [176] [INFO] Reason: Worker failed to boot.

**Comment by davoloko** [comment]
Thanks to you!

Now appears this error:

Collecting mysqlclient
  Downloading mysqlclient-2.1.0.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nzv2izt3/mysqlclient_978113a32d174dce81e84f83ff463473/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nzv2izt3/mysqlclient_978113a32d174dce81e84f83ff463473/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uby34cg3
         cwd: /tmp/pip-install-nzv2izt3/mysqlclient_978113a32d174dce81e84f83ff463473/
    Complete output (15 lines):
    mysql_config --version
    /bin/sh: mysql_config: not found
    mariadb_config --version
    /bin/sh: mariadb_config: not found
    mysql_config --libs
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nzv2izt3/mysqlclient_978113a32d174dce81e84f83ff463473/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-nzv2izt3/mysqlclient_978113a32d174dce81e84f83ff463473/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-nzv2izt3/mysqlclient_978113a32d174dce81e84f83ff463473/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.3.tar.gz (88 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nzv2izt3/mysqlclient_92793900dd414e82873d8010d0f87d88/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nzv2izt3/mysqlclient_92793900dd414e82873d8010d0f87d88/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pxwv6vcr
         cwd: /tmp/pip-install-nzv2izt3/mysqlclient_92793900dd414e82873d8010d0f87d88/
    Complete output (15 lines):
    mysql_config --version
    /bin/sh: mysql_config: not found
    mariadb_config --version
    /bin/sh: mariadb_config: not found
    mysql_config --libs
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nzv2izt3/mysqlclient_92793900dd414e82873d8010d0f87d88/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-nzv2izt3/mysqlclient_92793900dd414e82873d8010d0f87d88/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-nzv2izt3/mysqlclient_92793900dd414e82873d8010d0f87d88/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz#sha256=f6ebea7c008f155baeefe16c56cd3ee6239f7a5a9ae42396c2f1860f08a7c432 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.2.tar.gz (88 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nzv2izt3/mysqlclient_e66e854b8eed458e98426bd49b32aa9c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nzv2izt3/mysqlclient_e66e854b8eed458e98426bd49b32aa9c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o4pwqoih
         cwd: /tmp/pip-install-nzv2izt3/mysqlclient_e66e854b8eed458e98426bd49b32aa9c/
    Complete output (12 lines):
    /bin/sh: mysql_config: not found
    /bin/sh: mariadb_config: not found
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nzv2izt3/mysqlclient_e66e854b8eed458e98426bd49b32aa9c/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-nzv2izt3/mysqlclient_e66e854b8eed458e98426bd49b32aa9c/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-nzv2izt3/mysqlclient_e66e854b8eed458e98426bd49b32aa9c/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0e/68/f79de0e0fcdb041783124b825771e0ba6a3d0893b7b4c4735f130e42af47/mysqlclient-2.0.2.tar.gz#sha256=8df057b08fc27d8f7106bfa997d0a21e2acef017f905f06d6fb0aa6a20d4d2b2 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.1.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nzv2izt3/mysqlclient_63b1580ba6dd49f4bb678262c3aa1013/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nzv2izt3/mysqlclient_63b1580ba6dd49f4bb678262c3aa1013/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k2igxskl
         cwd: /tmp/pip-install-nzv2izt3/mysqlclient_63b1580ba6dd49f4bb678262c3aa1013/
    Complete output (12 lines):
    /bin/sh: mysql_config: not found
    /bin/sh: mariadb_config: not found
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nzv2izt3/mysqlclient_63b1580ba6dd49f4bb678262c3aa1013/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-nzv2izt3/mysqlclient_63b1580ba6dd49f4bb678262c3aa1013/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-nzv2izt3/mysqlclient_63b1580ba6dd49f4bb678262c3aa1013/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz#sha256=fb2f75aea14722390d2d8ddf384ad99da708c707a96656210a7be8af20a2c5e5 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-2.0.0.tar.gz (87 kB)

*************

WARNING: Discarding https://files.pythonhosted.org/packages/82/ea/336daf6c7baa564d0c434ab748218d1a7dc61dfc7066e98b72afd24fd2b9/mysqlclient-1.3.5.tar.gz#sha256=80ea68f6f3c2cfbf35c91adde2b40de1f2c31132118d2dcee048c72423f678bf (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.4.tar.gz (77 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-awzbbbv0/mysqlclient_f4168471abef44d4bfa64a0ac67c8f40/setup.py'"'"'; __file__='"'"'/tmp/pip-install-awzbbbv0/mysqlclient_f4168471abef44d4bfa64a0ac67c8f40/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ze5lk8nm
         cwd: /tmp/pip-install-awzbbbv0/mysqlclient_f4168471abef44d4bfa64a0ac67c8f40/
    Complete output (10 lines):
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-awzbbbv0/mysqlclient_f4168471abef44d4bfa64a0ac67c8f40/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-awzbbbv0/mysqlclient_f4168471abef44d4bfa64a0ac67c8f40/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-awzbbbv0/mysqlclient_f4168471abef44d4bfa64a0ac67c8f40/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/17/d9/03b08e6a033401335b720806b87596aee8d7f7aa87539713238905c4a8d1/mysqlclient-1.3.4.tar.gz#sha256=a0263383f8ac33ad12d68dc61fa8ccbee41244ce916287c6cee71bf8aea82c5c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.3.tar.gz (77 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-awzbbbv0/mysqlclient_3cd03b7bc01248cb9b20eccb38d537bb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-awzbbbv0/mysqlclient_3cd03b7bc01248cb9b20eccb38d537bb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kz8w0og3
         cwd: /tmp/pip-install-awzbbbv0/mysqlclient_3cd03b7bc01248cb9b20eccb38d537bb/
    Complete output (10 lines):
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-awzbbbv0/mysqlclient_3cd03b7bc01248cb9b20eccb38d537bb/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-awzbbbv0/mysqlclient_3cd03b7bc01248cb9b20eccb38d537bb/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-awzbbbv0/mysqlclient_3cd03b7bc01248cb9b20eccb38d537bb/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/26/53/c575db342bfca0213c9243ed2642bfadcd420b18d2f477dc812543e3d83a/mysqlclient-1.3.3.tar.gz#sha256=0f0887882d71bf2a079d9724d9323053cfbee8ab2dcfc989daf97d7ce5be9af9 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.2.tar.gz (77 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-awzbbbv0/mysqlclient_a89c6216cce84f278cc34826d503f992/setup.py'"'"'; __file__='"'"'/tmp/pip-install-awzbbbv0/mysqlclient_a89c6216cce84f278cc34826d503f992/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-opbkg9s6
         cwd: /tmp/pip-install-awzbbbv0/mysqlclient_a89c6216cce84f278cc34826d503f992/
    Complete output (10 lines):
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-awzbbbv0/mysqlclient_a89c6216cce84f278cc34826d503f992/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-awzbbbv0/mysqlclient_a89c6216cce84f278cc34826d503f992/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-awzbbbv0/mysqlclient_a89c6216cce84f278cc34826d503f992/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.1.tar.gz (76 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-awzbbbv0/mysqlclient_247a2b0dfdf747b2831cb5159b6520d0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-awzbbbv0/mysqlclient_247a2b0dfdf747b2831cb5159b6520d0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vlylp0mi
         cwd: /tmp/pip-install-awzbbbv0/mysqlclient_247a2b0dfdf747b2831cb5159b6520d0/
    Complete output (10 lines):
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-awzbbbv0/mysqlclient_247a2b0dfdf747b2831cb5159b6520d0/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-awzbbbv0/mysqlclient_247a2b0dfdf747b2831cb5159b6520d0/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-awzbbbv0/mysqlclient_247a2b0dfdf747b2831cb5159b6520d0/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysqlclient-1.3.0.tar.gz (76 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-awzbbbv0/mysqlclient_f5153a75e38348f5a018e5ac425cbb09/setup.py'"'"'; __file__='"'"'/tmp/pip-install-awzbbbv0/mysqlclient_f5153a75e38348f5a018e5ac425cbb09/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c_gjpvj5
         cwd: /tmp/pip-install-awzbbbv0/mysqlclient_f5153a75e38348f5a018e5ac425cbb09/
    Complete output (10 lines):
    /bin/sh: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-awzbbbv0/mysqlclient_f5153a75e38348f5a018e5ac425cbb09/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-awzbbbv0/mysqlclient_f5153a75e38348f5a018e5ac425cbb09/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-awzbbbv0/mysqlclient_f5153a75e38348f5a018e5ac425cbb09/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mysqlclient (from versions: 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11rc1, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.4.0rc1, 1.4.0rc2, 1.4.0rc3, 1.4.0, 1.4.1, 1.4.2, 1.4.2.post1, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc1, 2.1.0)
ERROR: No matching distribution found for mysqlclient
WARNING: You are using pip version 21.1.2; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
/etc/cont-init.d/99-run.sh: exiting 1

**Comment by alexbelgium** [comment]
Thanks I'll investigate a bit more :)

**Comment by davoloko** [comment]
I'm checking and in systems options appears the next warnings:

Media serving  -> using gunicorn. in this case I understand that the "problem" is that only one instance is running so it is not a real problem.

Secret key -> I have looked in the official documentation and it seems that the variable "SECRET_KEY=" is missing in the .env file.

Debug -> as in the previous case, indicates that the variable "DEBUG=" must be defined with a value of 0

I have tried to look in the addon code you have created but I can't find a way to solve it, I have no programming knowledge but sometimes by looking and comparing I have been able to solve some issues :'(

Thanks again for your work!
![tandoor](https://user-images.githubusercontent.com/21021364/149521380-10d32dc7-31ec-4369-b8f0-e4d6d5b1b3e1.png)

**Comment by alexbelgium** [comment]
Perfect, thanks for the input! I've set the export of the SECRET_KEY variable, and DEBUG to 0 in the new version I'll push in a couple minutes.

For mariadb it doesn't seem to accept the installation of mysqlclient ; anyway it's not a core feature ;-)

About the first one... no idea what I could do to solve it :-)

**Comment by alexbelgium** [comment]
OK, the addon is considered as complete! It doesn't seem to support mysql so I removed the option. Thanks for the testing and support! Let me know if anything goes wrong :) have a nice weekend

**Comment by davoloko** [comment]
Thanks!!! All ok good weekend!!
