### ISSUE TITLE
🐛 [mealie] How fix mealie?

### ISSUE THREAD

**Issue by jdeath** [alexbelgium/hassio-addons#1550]
### Description

I completely uninstalled 1.12. Restored 1.11 from a backup, but it will not start up. I get errors like:
`alembic.util.exc.CommandError: Can't locate revision identified by 'feecc8ffb956'`

Complete uninstall and reinstall of 1.12-1 still errors.

It looks like database is stored in the docker container, so not sure how the old database is still around. 

### Reproduction steps

```bash
1. Delete mealie
2. Restore 1.11 version from backup
1. Run mealie
```

### Addon Logs

```bash
hard to capture it all

-----------------------------------------------------------
 Add-on version: v1.11.0
 There is an update available for this add-on!
 Latest add-on version: v1.12.0-2
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 13.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.8.2
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
ALLOW_SIGNUP='true'
DATA_DIR='/config/addons_config/mealie_data'
PGID='1000'
PUID='1000'
certfile='fullchain.pem'
keyfile='privkey.pem'
ssl='false'
Timezone set from Etc/UTC to America/XXXX
/etc/cont-init.d/01-config_yaml.sh: executing

...
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/mealie/app.py", line 55, in lifespan_fn
    init_db.main()
  File "/app/mealie/db/init_db.py", line 101, in main
    command.upgrade(alembic_cfg, "head")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/alembic/env.py", line 81, in <module>
    run_migrations_online()
  File "/app/alembic/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
ERROR    2024-08-25T17:17:48 - Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 250, in _catch_revision_errors
    yield
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 458, in _upgrade_revs
    for script in reversed(list(revs))
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 616, in run_migrations
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 814, in iterate_revisions
    for step in self._migrations_fn(heads, self):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 395, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 446, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 282, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'feecc8ffb956'

ERROR    2024-08-25T17:17:48 - Application startup failed. Exiting.
    revisions, heads = fn(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 1475, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 542, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 542, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 565, in get_revisions
    return tuple(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 637, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'feecc8ffb956'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/mealie/app.py", line 55, in lifespan_fn
    init_db.main()
  File "/app/mealie/db/init_db.py", line 101, in main
    command.upgrade(alembic_cfg, "head")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/alembic/env.py", line 81, in <module>
    run_migrations_online()
  File "/app/alembic/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 616, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 395, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 446, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 282, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'feecc8ffb956'

ERROR    2024-08-25T17:17:48 - Application startup failed. Exiting.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, this issue initially saw that v2 was being pulled instead of v1. https://github.com/alexbelgium/hassio-addons/issues/1548

Alas with your comment I'm realizing that the database is stored in /config (therefore the homeassistant container) and not mealie's...

As it is much less frequent to backup this one I wonder if I won't go back again to v2 to avoid breaking everyone's install. Your data is safe in a v2 version, so if I just push v2 it should work straight out of the box again

**Comment by jdeath** [comment]
Ok. I'll standby. In `\config\addons_config\mealie` only contains a yaml config file, not any data. Luckily I have a backup from the mealie, so hopefully that will restore once this is fixed.

**Comment by alexbelgium** [comment]
And in /config/addons_config/mealie_data?

**Comment by markaccplus** [comment]
This issue affects me as well, please fix soon.

**Comment by jdeath** [comment]
> And in /config/addons_config/mealie_data?

Yup, it is there. Didn't see that.

**Comment by alexbelgium** [comment]
> This issue affects me as well, please fix soon.

Alas there is no easy solution to move back from Mealie 2.0 to 1.2.
- If you had a backup from mealie : 
  - 1. make a clean install (rename folder `/homeassistant/addons_config/mealie_data` to mealie_data.bak)
  - 2. restart the latest version of the addon (which will fully reset) and restore your backup
- If you have a backup from homeassistant of the /config folder : 
  - 1. you should rename the folder `/homeassistant/addons_config/mealie_data` to mealie_data.bak
  - 2. extract your backup 
  - 3. Copy the `/homeassistant/addons_config/mealie_data` folder from your backup to the same path in homeassistant
- Wait for the addon to move back to 2.0 to use your database that was upgraded...

If you have neither, alas Mealie has no way to way back from the upgrade that occurred... For info, I've improved the system to make sure that the data is backuped in the future (this function did not exist when I created the addon) but this doesn't help for this specific issue.

**Comment by jdeath** [comment]
My latest Mealie backup was a few months old, but I had a home assistant backup from just a few days before the bad update. But it was encrypted. It is so silly there is not a simple way to extract the unencrypted backup.

Luckily I found this thread: `https://community.home-assistant.io/t/get-files-from-password-protected-snapshot/245066/16` . There were a bunch of old threads, with older ways to decrypt backups which no longer worked! Copy @Burningstone's code into `decrypt.py`

Grab your latest home assistant backup (look for a big backup with recent date in \backups)

decrypt: `python decrypt.py -i xxx.tar -p YourBackupPassword`
Give it time. You need to wait until it finishes, do not grab homeassistant.tar.gz once it shows up!

stop mealie addon
Then get the config\addons_config\mealie_data directory from inside homeassitant folder that is created. Copy that over to your \config\addons_config\mealie_data
restart mealie

My extraction got hung up on one of my addon backups. So I changed line 138 of decrypt.py to homeassitant.tar.gz instead of *.tar.gz so it skipped the other files.

**Comment by broyuken** [comment]
So if I am on 1.12 which is the nightly build, and I've added stuff to my database I'm kinda stuck here until the addon pulls from the 2.0 database? Is my understanding correct?

**Comment by alexbelgium** [comment]
Alas yes I think I'll push a separate add-on with a v2 version specifically for people stuck like you

**Comment by remb0** [comment]
great news alex :)

**Comment by gschmidl** [comment]
Sorry, I'm very confused here. I removed all mealie data (I have a backup from August 14), but v1.12.0-2 puts the config into /**addon_configs**, not /homeassistant/**addons_config**. My backup has the latter but not, as far as I can tell, the former, how do I proceed?
