### ISSUE TITLE
❓ [BattyBirdNET-Pi] Can't get add-on to launch properly

### ISSUE THREAD

**Issue by TheRealFalseReality** [alexbelgium/hassio-addons#1553]
**BattyBirdNET-Pi**

---
Cannot get this add-on to launch on HA instance. 
I recently got into birdNET-Pi, and loving it! It's really neat to detect what's nearby,  and I wanna thank you for making this an add-on for Home Assistant. I recently saw you made it into an add-on, and got really excited to try it out, as I do see some bats around!
But I can't seems to get the add-on to launch properly. I had to change the port from 8081 to 8082 becasue I have birdNET-pi using 8081. I thought it was because I had birdNET installed that may be an issue, so I uninstalled that add-on, still same issue. The log error is below. What could be the issue? Thank you!

```
touch: cannot touch '/home/pi/BirdSongs/StreamData/analyzing_now.txt': No such file or directory
Starting service: throttlerecording
```

**Comment by alexbelgium** [comment]
Hi, I'll look at that thanks

**Comment by alexbelgium** [comment]
I'm trying some things ;)

**Comment by TheRealFalseReality** [comment]
Currently getting this issue when trying to update
![Screenshot 2024-08-28 172353](https://github.com/user-attachments/assets/0b72bca0-b9d5-4590-9de3-1822784c98c1)

**Comment by TheRealFalseReality** [comment]
lol! ok! Thank you very much! I graduated from Biology a while ago and always had an interest with wildlife Bio, and when I saw birdNET-Pi, I got hooked! I'm now watching and identifying birds around, the house, setting up feeders and bird boxes soon! Then I noticed some bats and this add-on!

**Comment by alexbelgium** [comment]
ahah I see your enthuisiasm and fully share it ! I've spent WEEKS trying and selecting the best microphones to be able to improve recognition ; review daily the new species to understand if they are real birds or flukes (and discovered I had incredible birds that I didn't even suspect near me!) and install bird boxes (I initially built them in wood and moved to wood-concrete ones that are more robust)

For bats, I think you need another very specific microphone that might make it a bit harder to implement! but good luck !

It has succeeded building, I'll look if it launches :-)

**Comment by TheRealFalseReality** [comment]
Thanks to the discussions, I picked up that BOYA mic that everyone recommends. I dunno if it can catch higher frequencies, but I don't mind trying. 
I got it to update to 0.3, but having an NGINX error, I haven't looked at the logs just yet.

**Comment by alexbelgium** [comment]
Should be good now!

**Comment by TheRealFalseReality** [comment]
> Should be good now!

Alrighty, I'll take a look this evening!

**Comment by alexbelgium** [comment]
Well isn't that good the issues just came a bit later ;) but I'll look again

**Comment by TheRealFalseReality** [comment]
yep, seems like `birdnet_server.service`

relevant logs (but you may already know this):
```
tcp        0      0 127.0.0.1:7667          0.0.0.0:*               LISTEN      -                   
+ status=0
+ ((  status != 0  ))
+ systemctl is-active --quiet birdnet_server.service
+ status=3
+ ((  status != 0  ))
+ logger '[/home/pi/BirdNET-Pi/scripts/restart_services.sh] Unable to start birdnet_server.service... Looping until it start properly'
+ grep 5050 /dev/fd/63
++ netstat -tulpn
+ sudo systemctl restart birdnet_server.service
Traceback (most recent call last):
  File "/usr/local/bin/server.py", line 60, in <module>
    audiofmt = "." + str(str(str([i for i in this_run if i.startswith('AUDIOFMT')]).split('=')[1]).split('\\')[0])
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
+ sleep 45
+ grep 5050 /dev/fd/63
++ netstat -tulpn
+ sudo systemctl restart birdnet_server.service
Traceback (most recent call last):
  File "/usr/local/bin/server.py", line 60, in <module>
    audiofmt = "." + str(str(str([i for i in this_run if i.startswith('AUDIOFMT')]).split('=')[1]).split('\\')[0])
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
+ sleep 45
```

**Comment by alexbelgium** [comment]
Should be good now
