### ISSUE TITLE
🐛 [Spotweb] Trying to update (1.5.4-10) to recent release 1.5.5 - Internal Server Error ("manifest unknown")

### ISSUE THREAD

**Issue by JBakers** [alexbelgium/hassio-addons#1619]
### Description

Updating Spotweb results in an error.

![Schermafbeelding 2024-10-26 195119](https://github.com/user-attachments/assets/9aef408f-df77-4f5f-b1fd-a942290bf73b)

### Reproduction steps

```bash
Update de addon.
```

### Addon Logs

```bash
Logger: homeassistant.components.websocket_api.http.connection
Bron: components/websocket_api/commands.py:245
integratie: Home Assistant WebSocket API (documentatie, problemen)
Eerst voorgekomen: 09:12:45 (4 gebeurtenissen)
Laatst gelogd: 19:45:23

[140585686239552] Unexpected exception
[140585536330992] Unexpected exception
[140585561811856] Unexpected exception
[140585559522128] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 168, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 58, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 112, in async_update_addon
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 541, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/alexbelgium/spotweb-amd64:1.5.5: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=1.5.5&fromImage=ghcr.io%2Falexbelgium%2Fspotweb-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 463, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Spotweb: Can't install ghcr.io/alexbelgium/spotweb-amd64:1.5.5: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=1.5.5&fromImage=ghcr.io%2Falexbelgium%2Fspotweb-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

### Architecture

amd64

### OS

HAos

**Comment by DomBoJan** [comment]
Same problem with installen.

**Comment by alexbelgium** [comment]
Thanks, build is done now

**Comment by DomBoJan** [comment]
![Schermafbeelding 2024-10-27 222228](https://github.com/user-attachments/assets/f4d344fa-24e0-4789-9d19-5535b8b58e6c)
New problem?

**Comment by alexbelgium** [comment]
Argh I see. I'll think about something

**Comment by alexbelgium** [comment]
Could you please try 1.5.5-3 once it has finished building? Thanks

**Comment by DomBoJan** [comment]
![Schermafbeelding 2024-10-27 230948](https://github.com/user-attachments/assets/b3b6b626-fcaf-483f-9211-938bf9ccc8b5)

No good.

**Comment by DomBoJan** [comment]
Version 1.5.5-4 same result.
![Schermafbeelding 2024-10-27 235136](https://github.com/user-attachments/assets/5c4cbd8e-700d-4a46-9c91-2702e4a994d6)

**Comment by DomBoJan** [comment]
Version 1.5.5-5 same result.

**Comment by alexbelgium** [comment]
All good now with v6

**Comment by DomBoJan** [comment]
Thans, running again.

**Comment by JBakers** [comment]
Dank u Alex!
