### ISSUE TITLE
IMMICH- photos not loading after changing file location

### ISSUE THREAD

**Issue by samiibnjamil** [alexbelgium/hassio-addons#1663]
HI i love your Immich addon. thank you for your contribution, but Recently I changed me backup location from /media/Backup/immich to /media/4TB_BACKUP/immich now I cant access my photos anymore. when i CLick on it it still tries to load from  /media/Backup/immich . I did change the  data_location in config but still same. The Server shows online .

here is the of the log :
`[Nest] 1116  - 12/10/2024, 2:22:42 PM   ERROR [Api:GlobalExceptionFilter~npw5xgvd] Unknown error: Error: ENOENT: no such file or directory, access '/media/Backup/immich/thumbs/fdb4b3f4-e974-4ca4-b9e7-23b9ec384998/9a/86/9a867d8c-78ad-417a-aa66-8531507f047f-thumbnail.webp'
Error: ENOENT: no such file or directory, access '/media/Backup/immich/thumbs/fdb4b3f4-e974-4ca4-b9e7-23b9ec384998/9a/86/9a867d8c-78ad-417a-aa66-8531507f047f-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/app/immich/server/dist/utils/file.js:54:9)
    at async AssetMediaController.viewAsset (/app/immich/server/dist/controllers/asset-media.controller.js:58:9)
[Nest] 1116  - 12/10/2024, 2:22:42 PM   ERROR [Api:LoggerRepository~cq0as57i] Unable to send file: Error

**Comment by alexbelgium** [comment]
Mmh that's normal alas if you change the files location then the database can't find them anymore. You should check in the immich documentation how to do that I'm sorry that I can't help from the add-on point of view

**Comment by samiibnjamil** [comment]
Hey, thanks for your reply. I did check the documenttation , over there it said :
These are the steps I'm planning on taking:

stop the entire stack
mount the new drive
copy over the entire folder specified in UPLOAD_LOCATION
change the UPLOAD_LOCATION env variable to the new directory
start the immich stack again with docker-compose up -d --force-recreate
check whether all the images are still available via the web interface
delete the original folder

**Comment by alexbelgium** [comment]
Mmh the best is probably to use portainer to get console access within the add-on and execute the immich commands from within the add-on

**Comment by alexbelgium** [comment]
So the paths are within the postgres database. You'd likely need to gain access when postgres to modify. To avoid this, I've set up an option allowing to define the path for the library itself regardless of the data folder

**Comment by samiibnjamil** [comment]
Where can i find that option?

**Comment by alexbelgium** [comment]
Here it is! https://github.com/alexbelgium/hassio-addons/blob/master/immich/CHANGELOG.md#11261-7-16-02-2025 It is the new function line
