### ISSUE TITLE
🐛 Codex - Cannot add libraries

### ISSUE THREAD

**Issue by akaheisenberg** [alexbelgium/hassio-addons#1670]
### Description

Unable to add a library. When attempting to do so the screen closes and nothing happens. Looking at the logs it appears there are two errors possibly? These errors occur as soon as webui is launched.

I have tried uninstalling and reinstalled multiple times. Have tried adding many different libraries and that was also unsuccessful.

ValueError: No route found for path '/api/v3/ws'.

[2024-12-13 10:10:11 -0600] [417] [ERROR] Error in ASGI Framework

### Reproduction steps

```bash
1. Just opening webui causes the below log errors occur.
```

### Addon Logs

```bash
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Codex
 Web based comic archive browser and reader
-----------------------------------------------------------
 Add-on version: 1.7.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.11.2
 Home Assistant Supervisor: 2024.11.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 0
User GID : 0
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
PGID='0'
PUID='0'
csrf_allowed='http://homeassistant.local:8123,https://homeassistant.local:8123'
Timezone set from Etc/UTC to America/Chicago
/etc/cont-init.d/00-local_mounts.sh: executing
/etc/cont-init.d/00-smb_mounts.sh: executing
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory
Load environment variables from /config/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /addon_configs/db21ed7f_codex/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
... no env variables found, exiting
/etc/cont-init.d/01-custom_script.sh: executing
Execute /addon_configs/db21ed7f_codex/codex.sh if existing
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/91-csrf.sh: executing
[11:01:02] INFO: Setup manually defined ALLOWED_CSRF domains
PAPERLESS_CSRF_TRUSTED_ORIGINS is set to https://http://homeassistant.local:8123,https://homeassistant.local:8123:9810,http://http://homeassistant.local:8123,https://homeassistant.local:8123:9810,https://http://homeassistant.local:8123,https://homeassistant.local:8123:8123,http://http://homeassistant.local:8123,https://homeassistant.local:8123:8123,https://http://homeassistant.local:8123,https://homeassistant.local:8123,http://http://homeassistant.local:8123,https://homeassistant.local:8123,https://10.0.0.80:9810,http://10.0.0.80:9810,https://10.0.0.80:8123,http://10.0.0.80:8123,https://10.0.0.80,http://10.0.0.80,https://fe80::4b27:8599:3ef1:89c2:9810,http://fe80::4b27:8599:3ef1:89c2:9810,https://fe80::4b27:8599:3ef1:89c2:8123,http://fe80::4b27:8599:3ef1:89c2:8123,https://fe80::4b27:8599:3ef1:89c2,http://fe80::4b27:8599:3ef1:89c2,https://homeassistant:9810,http://homeassistant:9810,https://homeassistant:8123,http://homeassistant:8123,https://homeassistant,http://homeassistant,https://homeassistant.local:9810,http://homeassistant.local:9810,https://homeassistant.local:8123,http://homeassistant.local:8123,https://homeassistant.local,http://homeassistant.local
/etc/cont-init.d/99-run.sh: executing
[11:01:03] WARNING: Default password admin:admin...
[11:01:03] INFO: Starting...
2024-12-13 11:01:05 CST INFO    Starting Codex v1.7.10
2024-12-13 11:01:05 CST INFO    Ensuring database is correct and up to date...
2024-12-13 11:01:05 CST INFO    Database up to date.
2024-12-13 11:01:05 CST INFO    Database ready.
2024-12-13 11:01:07 CST INFO    root_path: /api/hassio_ingress/hWPNPegFCN20HQtIT4RMniHsGjZ7J_y20Rlfbmbsfvk
2024-12-13 11:01:07 CST INFO    Running Codex v1.7.10
2024-12-13 11:01:07 CST INFO    BroadcastListener started.
[2024-12-13 11:01:07 -0600] [415] [INFO] Running on http://0.0.0.0:9810 (CTRL + C to quit)
2024-12-13 11:01:07 CST INFO    LibrarianDaemon started all threads.
2024-12-13 11:01:07 CST INFO    LibrarianDaemon ready for tasks.
2024-12-13 11:01:07 CST INFO    Started watching library /config/custom-covers with poll
2024-12-13 11:01:07 CST INFO    Library /config/custom-covers waiting for manual poll.
2024-12-13 11:01:07 CST INFO    Looking for search entries to update since the fracturing of the multiverse...
[11:01:07] INFO: Started !
2024-12-13 11:01:07 CST INFO    No search entries to update.
2024-12-13 11:01:08 CST INFO    Looking for missing search entries to create...
2024-12-13 11:01:08 CST INFO    No search entries to create.
2024-12-13 11:01:08 CST INFO    Search index updated in a moment.
172.30.32.2 - - [13/Dec/2024:11:02:26 -0600] "GET / HTTP/1.1" 200 867 "http://0.0.0.0:8123/hassio" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
172.30.32.2 - - [13/Dec/2024:11:02:26 -0600] "GET /serviceworker-register.js HTTP/1.1" 200 378 "http://10.0.0.80:8123/api/hassio_ingress/hWPNPegFCN20HQtIT4RMniHsGjZ7J_y20Rlfbmbsfvk/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
[2024-12-13 11:02:26 -0600] [415] [ERROR] Error in ASGI Framework
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/usr/local/lib/python3.13/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/site-packages/channels/routing.py", line 48, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/channels/security/websocket.py", line 37, in __call__
    return await self.application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/channels/sessions.py", line 44, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/channels/sessions.py", line 261, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/channels/routing.py", line 102, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path '/api/v3/ws'.
```

### Architecture

amd64

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, your url are strange perhaps you should try without the :8123
