### ISSUE TITLE
[wger] no such table: core_language

### ISSUE THREAD

**Issue by b-0s** [alexbelgium/hassio-addons#191]
[wger 1.9]

First thanx for your repository.

I am trying to install wger but after installing I have the following log:

Traceback (most recent call last):
  File "/home/wger/.local/bin/wger", line 33, in <module>
    sys.exit(load_entry_point('wger', 'console_scripts', 'wger')())
  File "/home/wger/.local/bin/wger", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: wger
Using django's development server...
Watching for file changes with StatReloader
Performing system checks...
System check identified no issues (0 silenced).
You have 92 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, authtoken, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight.
Run 'python manage.py migrate' to apply them.
January 26, 2022 - 17:23:07
Django version 3.2.11, using settings 'settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

And when I open the web ui I am greeted with this:

OperationalError at /en/software/features
no such table: core_language
Request Method:	GET
Request URL:	http://my.site.address:8000/en/software/features
Django Version:	3.2.11
Exception Type:	OperationalError
Exception Value:	
no such table: core_language
Exception Location:	/usr/local/lib/python3.9/dist-packages/django/db/backends/sqlite3/base.py, line 423, in execute
Python Executable:	/usr/bin/python3
Python Version:	3.9.5
Python Path:	
['/home/wger/src',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/home/wger/src']

It is the latest HA version.

**Comment by alexbelgium** [comment]
Hi, thanks for reporting. I've pushed a new version which is confirmed to work
