### ISSUE TITLE
[Joplin Server] Not starting after installation

### ISSUE THREAD

**Issue by sti0** [alexbelgium/hassio-addons#214]
**Which addon?**

* Addon name : Joplin
* Addon version :  2.6.10

**Describe the bug**

After installing (building) the addon is not starting.

As you use the `florider89/joplin-server:latest` image in the `Dockerfile`, I think the build pulls the latest version 2.7.4 which is not compatible with the build config?!

**To Reproduce**

```
Starting...
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: executing
Executing modules script
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs
script failed to install 00-banner.sh
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs
script failed to install 00-global_var.sh
Executing script
/etc/cont-init.d/00-aaa_dockerfile_backup.sh: exiting 77
/etc/cont-init.d/99-run.sh: executing
/usr/bin/env: 'bashio': No such file or directory
/etc/cont-init.d/99-run.sh: exiting 127
```

**Full addon config**

`APP_BASE_URL: https://joplin.mydoma.in`

**System**

* Supervisor version: `supervisor-2022.01.1`
* Host system version: `Home Assistant OS 7.4`
Raspberry Pi 4 4GB

**Comment by alexbelgium** [comment]
Thanks for reporting, it is indeed a documented issue from the upstream image. I've switched the upstream image to another provider and will test

**Comment by alexbelgium** [comment]
Solved in new version!

**Comment by sti0** [comment]
Thank you for the quick fix. 

I have a question for my understanding. If somewhen is 2.7.5 released and one builds the addon, will it build on v2.7.4 or 2.7.5 ? I think with the `latest`, which is 2.7.5 in that case. On the other hand a running instance doesn't becomes a notification about the update. If we have a running instance we must "rebuild" in Home Assistant?

In this case the addon version is not in line with the version of the Joplin server (2.6.10 vs 2.7.4).

Is my adoption right?

**Comment by sti0** [comment]
As I already installed the addon, I refreshed the repo and rebuild with `etechonomy/joplin-server:latest`. After I started the addon no logs will be printed out. After looking into the instance with `docker ps -a` that every X seconds new container try to be created .

In my case I could easily remove and reinstall but if one had a running instance this would break the whole Joplin instance.

**Comment by alexbelgium** [comment]
Hi! Actually you don't need to rebuild. I link indeed the build to the latest tag, however I have an automated script that runs every two days and check if a new version was released. If yes, then it updates the addon version number, which triggers the request for update in  your HA instance. In this cas, if you just wait for the supervisor to refresh the repositories (couple hours)or refresh them manually, you'll see a new version of the addon named 2.7.4

I want to implement auto builds on my addons, to,avoid the issue you mention, but for that I need this bug fixes : https://github.com/home-assistant/supervisor/issues/3414

Don't hesitate to go and like this issue :) once it is solved, I'll implement auto builds on all my addons and we'll avoid this issue of versions mismatch

**Comment by alexbelgium** [comment]
> As I already installed the addon, I refreshed the repo and rebuild with `etechonomy/joplin-server:latest`. After I started the addon no logs will be printed out. After looking into the instance with `docker ps -a` that every X seconds new container try to be created .
> 
> In my case I could easily remove and reinstall but if one had a running instance this would break the whole Joplin instance.

Looks like a bug in supervisor... On my system ipthe update worked. Perhaps try to go in system and reload supervisor? Or perhaps once the new addon version will be out and updated it will work?

**Comment by sti0** [comment]
After I restart the addon the whole configuration was deleted. Data is not persistant.

**Comment by alexbelgium** [comment]
Mmh perhaps changing the upstream image was a bad idea because the internal config structure was different. I'll restore the old upstream image hopefully it will restore persisance. I'll do some tests. i'm really sorry that you lost data. Normally indeed it should use sqlite if postgress is not enabled, but probably the sqlite file differs in location between the previous and the new upstream images

**Comment by alexbelgium** [comment]
Mmh actually there is no config for sqlite, that's why it doesn't work... It is only set for postgress. I'll have a look to enable persistence for sqlite

**Comment by alexbelgium** [comment]
OK, I've put back the old image, it installs and boots (at least on my rpi aarch64), and set the databse variable so normally your sqlite should be stored in /config/addons_config/joplin/database.sqlite 

I'll do,some tests but I'm optimistic

**Comment by alexbelgium** [comment]
Hopefully 2.7.4-3 could have a persistent sqlite

**Comment by sti0** [comment]
I've updated to 2.7.4-3 but sqlite doesnt work for me:

```
2022-02-14 00:10:23: App: Log dir: /home/joplin/packages/server/logs
2022-02-14 00:10:23: App: DB Config: {
  client: 'sqlite3',
  name: '/config/addons_config/joplin/database.sqlite',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 1000,
  autoMigration: true,
  asyncStackTraces: true
}
2022-02-14 00:10:23: App: Mailer Config: {
  enabled: false,
  host: '',
  port: 465,
  security: 'tls',
  authUser: '',
  authPassword: '********',
  noReplyName: '',
  noReplyEmail: ''
}
2022-02-14 00:10:23: App: Content driver: { type: 1 }
2022-02-14 00:10:23: App: Content driver (fallback): null
2022-02-14 00:10:23: App: Trying to connect to database...
2022-02-14 00:10:23: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:24: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:25: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:26: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:27: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:28: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:29: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:30: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:31: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:32: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:33: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:34: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:35: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:36: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:37: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:38: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:39: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:40: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:41: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:42: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:43: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:44: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:45: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:46: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:47: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:48: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:49: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:50: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:51: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:52: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:53: db: Could not connect. Will try again. SQLITE_CANTOPEN: unable to open database file
2022-02-14 00:10:53: [error] db: Timeout trying to connect to database: Error: SQLITE_CANTOPEN: unable to open database file
    at createQueryBuilder (/home/joplin/packages/server/node_modules/knex/lib/knex-builder/make-knex.js:313:26)
    at knex (/home/joplin/packages/server/node_modules/knex/lib/knex-builder/make-knex.js:100:12)
    at /home/joplin/packages/server/src/db.ts:401:24
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/db.js:8:71
    at new Promise (<anonymous>) {
  errno: 14,
  code: 'SQLITE_CANTOPEN',
  originalStack: 'Error: SQLITE_CANTOPEN: unable to open database file'
}
Error: Timeout trying to connect to database. Last error was: SQLITE_CANTOPEN: unable to open database file
    at Object.<anonymous> (/home/joplin/packages/server/src/db.ts:113:10)
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/db.js:5:58)
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.0>
npm notice Run `npm install -g npm@8.5.0` to update!
npm notice 
/etc/cont-init.d/99-run.sh: exiting 1
```

**Comment by alexbelgium** [comment]
Ok, I've found the issue and can confirm it works on the latest build 2.7.4-5 :-)
At least, it starts, allows connections to WebUI when the URL is set in addon options, and if I change the password it remembers it after restart

**Comment by alexbelgium** [comment]
Data location (to save the database) is configurable through the data_location addon config

**Comment by sti0** [comment]
Thank you. Now it works. Could you add the `/share` directory? Currently it's only allowed to add a app path within the `/config` dir.

Second thought: The `MAILER_AUTH_PASSWORD` variable is logged in clear text.

**Comment by alexbelgium** [comment]
Thanks, adding share now. For the clear text I can remove the log but anyway only someone with access to your HA machine could access this log, and if they can access it they can read your variables... So security wise I don't think hiding it from the log would help. If you think it's needed though i can just add stars

**Comment by sti0** [comment]
You may could remove it. The Mail config is already logged by Joplin.
![image](https://user-images.githubusercontent.com/18382402/153925951-01c38b03-aa64-4689-bcb3-b2a908984605.png)

**Comment by alexbelgium** [comment]
OK, done !

**Comment by sti0** [comment]
Thank you very much. Now I use the `/data` dir so the database should be backuped if I run a partial HA backup for the Joplin addon right?

Other question: Do you know how I could host a Postgres within HA? I didn't found any addon yet.

**Comment by alexbelgium** [comment]
Hi, yes! /data is backupped with the addon, it is persistent with restarts and updates, but if you fully uninstall and reinstall it will be removed.

I usually prefer to use /config myself so I can have all my addons data backupped and can unusual then reinstall without issues as I do lits of testing.

For postgres, no idea... I'm using mariadb myself but not supported by joplin

**Comment by sti0** [comment]
So you use SQLite for Joplin?

**Comment by alexbelgium** [comment]
I use Google keep :) Joplin was initially setup with the collaboration of another dev who wanted it. But sqlite should be fine enough for a normal usage!

**Comment by sti0** [comment]
Ok, thank you. I think we can close this one :)

**Comment by alexbelgium** [comment]
Thanks! Have fun. Btw nextcloud also has a nice notes app with dedicated phone apps, and the addon supports mariadb

**Comment by sti0** [comment]
Thanks. I will look into this. Currently I evaluate multiple options.
