### ISSUE TITLE
[paperless_ngx] Unable to find zbar shared library

### ISSUE THREAD

**Issue by bruvv** [alexbelgium/hassio-addons#306]
**Which addon?**

- Addon name : paperless_ngx
- Addon version : latest

**Describe the bug**

When uploading, an error comes up: `Unable to find zbar shared library`. When checking here: https://github.com/paperless-ngx/paperless-ngx/blob/main/docs/setup.rst#bare-metal-route it looks like some dependencies are missing

**To Reproduce**

1. Upload a document from the home page
2. See error

**Full addon log**
```
[2022-04-30 22:09:54 +0000] [1069] [WARNING] Worker with pid 1102 was terminated due to signal 9
22:11:02 [Q] INFO Enqueued 1
22:11:02 [Q] INFO Process-1:8 processing [***.pdf]
Process Process-1:8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/app/paperless/src/documents/tasks.py", line 25, in <module>
    from pyzbar import pyzbar
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')
ImportError: Unable to find zbar shared library
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 424, in worker
    f = pydoc.locate(f)
  File "/usr/lib/python3.8/pydoc.py", line 1632, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.8/pydoc.py", line 362, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in documents.tasks - ImportError: Unable to find zbar shared library
22:11:03 [Q] ERROR reincarnated worker Process-1:8 after death
22:11:03 [Q] INFO Process-1:10 ready for work at 1263
```

**Full addon config**
Default config nothing changed

**System**

- Supervisor version: supervisor-2022.04.0
- Host system version: Home Assistant OS 7.6

**Comment by alexbelgium** [comment]
Hi thanks for the report. This issue is identified in the upstream image and the change will be merged here as soon as it is done : https://github.com/linuxserver/docker-paperless-ngx/issues/10

**Comment by bruvv** [comment]
Awesome thanks

**Comment by alexbelgium** [comment]
They have merged the PR but no release yet we need to wait a bit more
