### ISSUE TITLE
[lidarr] Lidarr won't start.

### ISSUE THREAD

**Issue by sambarlick** [alexbelgium/hassio-addons#400]
**Which addon?**

- Addon name : Lidarr
- Addon version : 1.0.2.2592-ls90

**Describe the bug**

The add-on won't start. I have uninstalled it and reinstalled it and it won't start. All my settings are correct.

**To Reproduce**

**Full addon log

Configuration
Log
Lidarr NAS
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Lidarr: https://opencollective.com/lidarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    0
User gid:    0
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-folders.sh: executing... 
[cont-init.d] 20-folders.sh: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 92-local_mounts.sh: executing... 
[cont-init.d] 92-local_mounts.sh: exited 0.
[cont-init.d] 92-smb_mounts.sh: executing... 
Mounting smb share(s)...
[21:33:39] INFO: ... //192.168.8.140/Media successfully mounted to /mnt/Media with options 
[cont-init.d] 92-smb_mounts.sh: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Lidarr - /app/lidarr/bin/Lidarr.dll - Version 1.0.2.2592 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/lidarr] 
[Fatal] ConsoleApp: EPIC FAIL! 
[v1.0.2.2592] System.IO.InvalidDataException: Failed to load configuration from file '/config/addons_config/lidarr/config.xml'.
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor.CreateDecryptingXmlReader(Stream input, XmlReaderSettings settings)
   at Microsoft.Extensions.Configuration.Xml.XmlStreamConfigurationProvider.Read(Stream stream, XmlDocumentDecryptor decryptor)
   at Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NzbDrone.Host.Bootstrap.GetConfiguration(StartupContext context) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 202
   at NzbDrone.Host.Bootstrap.CreateConsoleHostBuilder(String[] args, StartupContext context) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 109
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 68
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 45
Press enter to exit...
[Info] Bootstrap: Starting Lidarr - /app/lidarr/bin/Lidarr.dll - Version 1.0.2.2592 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config/addons_config/lidarr] 
[Fatal] ConsoleApp: EPIC FAIL! 
[v1.0.2.2592] System.IO.InvalidDataException: Failed to load configuration from file '/config/addons_config/lidarr/config.xml'.
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at Microsoft.Extensions.Configuration.Xml.XmlDocumentDecryptor.CreateDecryptingXmlReader(Stream input, XmlReaderSettings settings)
   at Microsoft.Extensions.Configuration.Xml.XmlStreamConfigurationProvider.Read(Stream stream, XmlDocumentDecryptor decryptor)
   at Microsoft.Extensions.Configuration.Xml.XmlConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NzbDrone.Host.Bootstrap.GetConfiguration(StartupContext context) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 202
   at NzbDrone.Host.Bootstrap.CreateConsoleHostBuilder(String[] args, StartupContext context) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 109
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 68
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 45
Press enter to exit...

**Full addon config**

**System**

- Supervisor version: 2022.07.0
- Host system version: 8.3

**Comment by alexbelgium** [comment]
Hi, as noted in your log your config file is invalid. Please remove it and a new one will be generated `/config/addons_config/lidarr/config.xml'.
---> System.Xml.XmlException: Root element is missing.`

**Comment by sambarlick** [comment]
Wow thanks. I didn't realise it was such an easy fix.
Also, Thanks for the super quick response!
