### ISSUE TITLE
🐛 [Enedisgateway2mqtt] Issue description

### ISSUE THREAD

**Issue by foXaCe** [alexbelgium/hassio-addons#426]
bonjour Alex,

 depuis la mise a jour d'aout de home assistant j'ai l'addon enedisway2mqtt qui plante de façon aléatoire.

 HTTPSConnectionPool(host='enedisgateway.tech', port=443): Read timed out. (read timeout=240)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='enedisgateway.tech', port=443): Read timed out. (read timeout=240)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/daily.py", line 206, in dailyBeetwen
    daily = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 145, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='enedisgateway.tech', port=443): Read timed out. (read timeout=240)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 292, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 39, in getDaily
    data = dailyBeetwen(headers, cur, con, url, pdl, mode, dateBegin, dateEnded, last_activation_date)
  File "/app/daily.py", line 342, in dailyBeetwen
    for error_key, error_msg in daily.items():
UnboundLocalError: local variable 'daily' referenced before assignment

**Comment by alexbelgium** [comment]
Bonjour, au vu du rapport il ne me semble pas que ce soit du a l'addon et il est préférable de poster la question dans le github de l'app mère. Merci d'avance

**Comment by foXaCe** [comment]
bonjour, ok merci je vais regarder ca
