### ISSUE TITLE
🐛 [Transmission Openvpn] Error starting the UI

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#438]
**Which addon?**

- Addon name : Transmission Openvpn
- Addon version : 4.0-v15

**Describe the bug**

A few hours ago, I upgraded the add-on, but interacted with it just now. Unfortunately, the UI was useless:
![image](https://user-images.githubusercontent.com/15247405/186157215-89d1adf5-e741-436d-be68-3b845210069f.png)

thus, I went to see the logs, and noticed some error.

**To Reproduce**

1. Start the add-on.

**Full addon log**

The relevant logs should be this:
```
Tue Aug 23 11:08:03 2022 TUN/TAP device tun0 opened
Tue Aug 23 11:08:03 2022 TUN/TAP TX queue length set to 100
Tue Aug 23 11:08:03 2022 /sbin/ip link set dev tun0 up mtu 1500
Tue Aug 23 11:08:03 2022 /sbin/ip addr add dev tun0 10.8.1.6/24 broadcast 10.8.1.255
Tue Aug 23 11:08:03 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.8.1.6 255.255.255.0 init
Up script executed with tun0 1500 1585 10.8.1.6 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.1.6
Using Transmission Web Control UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /config/addons_config/transmission/settings.json
Traceback (most recent call last):
  File "/etc/transmission/updateSettings.py", line 45, in <module>
    settings_dict = json.load(input_file)
  File "/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 69 column 1 (char 2335)
Tue Aug 23 11:08:03 2022 /sbin/ip route add [redacted]/32 via 172.30.32.1
Tue Aug 23 11:08:03 2022 /sbin/ip route add 0.0.0.0/1 via 10.8.1.1
Tue Aug 23 11:08:03 2022 /sbin/ip route add 128.0.0.0/1 via 10.8.1.1
Tue Aug 23 11:08:03 2022 Initialization Sequence Completed
[11:22:56] INFO: Ingress ready
```

**Full addon config**

```
DEBUG: false
DNS_server: 8.8.8.8,1.1.1.1
LOCAL_NETWORK: 192.168.0.0/16
OPENVPN_PASSWORD: [redacted]
OPENVPN_USERNAME: [redacted]
PGID: "1000"
PUID: "1000"
TRANSMISSION_DOWNLOAD_DIR: /mnt/shared/transmission/downloads
TRANSMISSION_HOME: /config/addons_config/transmission
TRANSMISSION_INCOMPLETE_DIR: /mnt/shared/transmission/incomplete
TRANSMISSION_WATCH_DIR: /mnt/shared/transmission/watch_dir
TRANSMISSION_WEB_UI: transmission-web-control
OPENVPN_CUSTOM_PROVIDER: true
OPENVPN_CUSTOM_PROVIDER_OVPN_LOCATION: /config/openvpn/xyz.somevpn.ovpn
TRANSMISSION_V3_UPDATE: true
cifsusername: [redacted]
cifspassword: [redacted]
networkdisks: //192.168.16.18/shared
```

**System**

- Supervisor version: 2022.08.3
- Host system version: 8.4

**Comment by alexbelgium** [comment]
Hi,

Have you tried restarting ? When I did my tests the UI loaded fine (but I was using flood and not web control)

**Comment by alexbelgium** [comment]
Ah - I understand there is an error on line 69 of your transmission settings.json. Ins't watch-dir your last parameter in your settings.json ?

**Comment by alexbelgium** [comment]
My code inferred it was the last parameter. The code just pushed should help avoid that

**Comment by almico** [comment]
> Have you tried restarting ?

Yes. Same error

**Comment by alexbelgium** [comment]
Indeed, the error is due to the code used to change the default folders that modified the settings.json. I've pushed a new version that should help that. I did not have this issue as watch-dir was my last parameter

**Comment by alexbelgium** [comment]
The version v16 works on my system

**Comment by almico** [comment]
On mine too :-)
