### ISSUE TITLE
🐛 [Addon name] Issue description

### ISSUE THREAD

**Issue by skank01** [alexbelgium/hassio-addons#441]
- Addon name : bazarr
- Addon version : latest

**Describe the bug**

Addon not starting
Running on raspberry pi
HA OS
First time i started , i could get into the web ui
After an hour, it stopped working

When i try to start now, i get this in logging:

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/waitress/adjustments.py", line 374, in __init__
    for s in socket.getaddrinfo(
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 27, in <module>
    from app.server import webserver  # noqa E402
  File "/app/bazarr/bin/bazarr/app/server.py", line 86, in <module>
    webserver = Server()
  File "/app/bazarr/bin/bazarr/app/server.py", line 34, in __init__
    self.server = create_server(app,
  File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 49, in create_server
    adj = Adjustments(**kw)
  File "/app/bazarr/bin/bazarr/../libs/waitress/adjustments.py", line 401, in __init__
    raise ValueError("Invalid host/port specified.")
ValueError: Invalid host/port specified.

**Comment by alexbelgium** [comment]
Hi, based on this "Invalid host/port specified" I would say you changed something from the ui that shouldn't have? Could you please try a full uninstall and reinstall? Thanks!

**Comment by skank01** [comment]
Hi sorry, yes its fixed now.
I uninstalled and installed back, then it still wouldnt load. I manually deleted everything and reinstalled then and everythings ok now :)

**Comment by alexbelgium** [comment]
Thanks for the feedback, glad it works!
