### ISSUE TITLE
🐛 [Addon name] Issue description

### ISSUE THREAD

**Issue by icemanxbe** [alexbelgium/hassio-addons#487]
**Which addon?**
- Addon name : Overseerr
- Addon version : 1.30.0

**Describe the bug**

After latest update:
`Error: EACCES: permission denied, open '/config/.config/yarn'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at /usr/share/node_modules/yarn/lib/cli.js:101466:58
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/share/node_modules/yarn/lib/cli.js:101464:78)
    at Object.findRc (/usr/share/node_modules/yarn/lib/cli.js:101478:10)
    at getRcConfigForCwd (/usr/share/node_modules/yarn/lib/cli.js:56957:74)
    at /usr/share/node_modules/yarn/lib/cli.js:92827:56
    at Generator.next (<anonymous>)
    at step (/usr/share/node_modules/yarn/lib/cli.js:310:30)`
    
even after removing and readding the addon, same story.

**System**
Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend-version: 20220907.2 - latest

**Comment by alexbelgium** [comment]
Hi, please try to reset the addons options, it might help by removing the PUID/PGID options that must be at 0:0 to allow it to access config. I've pushed a new version now that should help that

**Comment by icemanxbe** [comment]
that actually solved every issue. Thanks for the speedy solution!

**Comment by alexbelgium** [comment]
Thanks for the feedback! It actually identified a key issue in all my addons so it was very useful
