### ISSUE TITLE
🐛 [Joplin Server] time drift to large

### ISSUE THREAD

**Issue by NODeeJay** [alexbelgium/hassio-addons#564]
**Which addon?**

- Addon name : Joplin Server
- Addon version : 2.9.7

**Describe the bug**

When starting the container it reports the error and exits

**To Reproduce**

1. Install addon
2. Configure (see below)
3. Start
4. Change admin credentials
5. Create user
6. Connect Windows 10 client with user and import ~200 text only notes in ~2.5 MB (from Tomboy export)
7. Connect Android client and synchronize notes
8. Restart the Add-on
9. Add-on does not start anymore with `Error: The device time drift is 15486ms (Max allowed: 2000ms) - cannot continue as it could cause data loss and conflicts on the sync clients. You may increase env var MAX_TIME_DRIFT to pass the check, or set to 0 to disabled the check.`

**Full addon log**
```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Joplin Server
 Self-hosted open source note-taking application
-----------------------------------------------------------
 Add-on version: 2.9.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
APP_BASE_URL='http://hass.<beep>.net:22300'
MAILER_ENABLED='1'
MAILER_HOST='mail.<beep>.net'
MAILER_NOREPLY_EMAIL='joplin@<beep>.net'
MAILER_NOREPLY_NAME='Joplin'
MAILER_PORT='25'
MAILER_SECURE='1'
data_location='/config/addons_config/joplin'
Timezone set from Etc/UTC to Europe/Prague
/etc/cont-init.d/01-custom_script.sh: executing
[22:39:37] INFO: Execute /config/joplin.sh if existing
[22:39:37] INFO: ... no script found
/etc/cont-init.d/99-run.sh: executing
[22:39:37] WARNING: Warning - minimum configuration recommended : 2 cpu cores and 4 GB of memory. Otherwise the system will become unresponsive and crash.
[22:39:37] WARNING: Warning : a custom data location was selected, but the previous folder will NOT be copied. You need to do it manually
[22:39:38] INFO: Using sqlite
[22:39:38] INFO: Mailer Host set
[22:39:39] INFO: Mailer Port set
[22:39:39] INFO: Mailer Secure set
[22:39:40] INFO: Mailer Noreply Name set
[22:39:40] INFO: Mailer Noreply Email set
[22:39:41] INFO: Mailer Enabled set
[22:39:41] INFO: Starting Joplin. Initial user is "admin@localhost" with password "admin"
> @joplin/server@2.9.7 start
> node dist/app.js
2022-11-18 22:39:56: App: Starting server v2.9.7 (prod) on port 22300 and PID 313...
Error: The device time drift is 15424ms (Max allowed: 2000ms) - cannot continue as it could cause data loss and conflicts on the sync clients. You may increase env var MAX_TIME_DRIFT to pass the check, or set to 0 to disabled the check.
    at /home/joplin/packages/server/src/app.ts:260:11
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/app.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.1.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.1.2>
npm notice Run `npm install -g npm@9.1.2` to update!
npm notice 
/etc/cont-init.d/99-run.sh: exiting 1
```

**Full addon config**

```
APP_BASE_URL: http://hass.<beep>.net:22300
data_location: /config/addons_config/joplin
MAILER_ENABLED: 1
MAILER_HOST: mail.<beep>.net
MAILER_NOREPLY_EMAIL: joplin@<beep>.net
MAILER_NOREPLY_NAME: Joplin
MAILER_PORT: 25
MAILER_SECURE: 1
```

I tried adding as requested by joplin server but it did not make a difference
MAX_TIME_DRIFT: 0

**System**

 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.10.2

**Comment by alexbelgium** [comment]
Please try this version

**Comment by NODeeJay** [comment]
Puh, that was quick, it fixed it. Thanks!
But I am not sure if it should be permanently set to 0, there is a reason to warn for the time drift?

**Comment by alexbelgium** [comment]
You could set an ntp server

**Comment by alexbelgium** [comment]
I've added access to HA server time
