### ISSUE TITLE
🐛 [All addons] Can't update (manifest unknown)

### ISSUE THREAD

**Issue by hugoKs3** [alexbelgium/hassio-addons#579]
**Which addon?**

- Addon name : Jefflyfin
- Addon version : 10.8.7-1-ls189

**Describe the bug**

AI have a notification for a new version to install.
When clicking on it, I get the below logs.

**Full addon log**

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:36:40 PM (5 occurrences)
Last logged: 10:19:49 PM

[547622927328] Error updating Jellyfin NAS: Can't install ghcr.io/alexbelgium/jellyfin-aarch64:10.8.7-1-ls189: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=10.8.7-1-ls189&fromImage=ghcr.io%2Falexbelgium%2Fjellyfin-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
[547844184272] Error updating Jellyfin NAS: Can't install ghcr.io/alexbelgium/jellyfin-aarch64:10.8.7-1-ls189: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=10.8.7-1-ls189&fromImage=ghcr.io%2Falexbelgium%2Fjellyfin-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
[547561939072] Error updating Jellyfin NAS: Can't install ghcr.io/alexbelgium/jellyfin-aarch64:10.8.7-1-ls189: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=10.8.7-1-ls189&fromImage=ghcr.io%2Falexbelgium%2Fjellyfin-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
[547529205376] Error updating Jellyfin NAS: Can't install ghcr.io/alexbelgium/jellyfin-aarch64:10.8.7-1-ls189: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=10.8.7-1-ls189&fromImage=ghcr.io%2Falexbelgium%2Fjellyfin-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/alexbelgium/jellyfin-aarch64:10.8.7-1-ls189: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=10.8.7-1-ls189&fromImage=ghcr.io%2Falexbelgium%2Fjellyfin-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Jellyfin NAS: Can't install ghcr.io/alexbelgium/jellyfin-aarch64:10.8.7-1-ls189: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=10.8.7-1-ls189&fromImage=ghcr.io%2Falexbelgium%2Fjellyfin-aarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**System**

- Supervisor version: supervisor-2022.11.2
- Host system version: Home Assistant OS 9.3

**Comment by alexbelgium** [comment]
Hi, image is building, please try a bit later

**Comment by hugoKs3** [comment]
OK, thanks.
I'll try again tomorrow.

**Comment by alexbelgium** [comment]
Should be good now

**Comment by hugoKs3** [comment]
Confirmed!
Thank you.

**Comment by alexbelgium** [comment]
Great thanks
