### ISSUE TITLE
🐛 [NEXTCLOUD] Nextcloud not installed

### ISSUE THREAD

**Issue by malosaa** [alexbelgium/hassio-addons#595]
Netcloud add-on

HomeassistantOS 9.3 
version 2022.12

i can't get it installed, i did also delete whole container etc.. also started from stock.. still not working.
Probably an build issue on the last nextcloud? 

```
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/30-keygen.sh
[18:17:25] INFO: No ssl certificates set. Auto generating ones...
Generating a RSA private key
........................+++++
.................................................................................................+++++
writing new private key to '/ssl/nextcloud/keys/cert.key'
-----
... adding ssl certs in files
[18:17:26] INFO: ... done
cont-init: info: /etc/cont-init.d/30-keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-config.sh
Creating folders
Updating permissions
cont-init: info: /etc/cont-init.d/93-config.sh exited 0
cont-init: info: running /etc/cont-init.d/94-install.sh
cont-init: info: /etc/cont-init.d/94-install.sh exited 0
cont-init: info: running /etc/cont-init.d/94-memcache.sh
[18:17:30] INFO: Setting data diretory: /share/nextcloud
cont-init: info: /etc/cont-init.d/94-memcache.sh exited 0
cont-init: info: running /etc/cont-init.d/99-add_packages.sh
[18:17:30] INFO: Installing additional apps :
... inotify-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing inotify-tools (3.20.11.0-r0)
Executing busybox-1.34.1-r7.trigger
OK: 318 MiB in 228 packages
... nextcloud
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing nextcloud (22.2.10-r0)
Executing nextcloud-22.2.10-r0.pre-install
Executing busybox-1.34.1-r7.trigger
OK: 545 MiB in 229 packages
cont-init: info: /etc/cont-init.d/99-add_packages.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
cont-init: info: running /etc/cont-init.d/99-custom_scripts.sh
cont-init: info: /etc/cont-init.d/99-custom_scripts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-elasticsearch.sh
Nextcloud is not installed - only a limited number of commands are available
Full_Text_Search option not set
cont-init: info: /etc/cont-init.d/99-elasticsearch.sh exited 0
cont-init: info: running /etc/cont-init.d/99-mariadb_discovery.sh
cont-init: info: /etc/cont-init.d/99-mariadb_discovery.sh exited 0
cont-init: info: running /etc/cont-init.d/99-ocr.sh
Nextcloud is not installed - only a limited number of commands are available
cont-init: info: /etc/cont-init.d/99-ocr.sh exited 0
cont-init: info: running /etc/cont-init.d/99-trusted_domains.sh
Nextcloud is not installed - only a limited number of commands are available
[18:17:54] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
[18:17:55] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[18:17:55] INFO: Trusted domains set in the configuration. Refreshing domains.
[18:17:55] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 1
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Exception: Not installed in /data/config/www/nextcloud/lib/base.php:284
Stack trace:
#0 /data/config/www/nextcloud/lib/base.php(680): OC::checkInstalled()
#1 /data/config/www/nextcloud/lib/base.php(1144): OC::init()
#2 /data/config/www/nextcloud/cron.php(43): require_once('...')
#3 {main}
```

and on my other test system 

```
Generating a RSA private key
.+++++
...................+++++
writing new private key to '/ssl/nextcloud/keys/cert.key'
-----
... adding ssl certs in files
[18:21:13] INFO: ... done
cont-init: info: /etc/cont-init.d/30-keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/92-local_mounts.sh
cont-init: info: /etc/cont-init.d/92-local_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/92-smb_mounts.sh
Mounting smb share(s)...
Using PUID 1000 and PGID 1000
[18:21:17] INFO: ... //192.168.1.36/Nextcloud successfully mounted to /mnt/Nextcloud with options 
cont-init: info: /etc/cont-init.d/92-smb_mounts.sh exited 0
cont-init: info: running /etc/cont-init.d/93-config.sh
Creating folders
Updating permissions
cont-init: info: /etc/cont-init.d/93-config.sh exited 0
cont-init: info: running /etc/cont-init.d/94-install.sh
cont-init: info: /etc/cont-init.d/94-install.sh exited 0
cont-init: info: running /etc/cont-init.d/94-memcache.sh
[18:21:24] INFO: Setting data diretory: /mnt/Nextcloud
cont-init: info: /etc/cont-init.d/94-memcache.sh exited 0
cont-init: info: running /etc/cont-init.d/99-add_packages.sh
[18:21:25] INFO: Installing additional apps :
... inotify-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing inotify-tools (3.20.11.0-r0)
Executing busybox-1.34.1-r7.trigger
OK: 318 MiB in 228 packages
... vim
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
OK: 318 MiB in 228 packages
... nextcloud
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing nextcloud (22.2.10-r0)
Executing nextcloud-22.2.10-r0.pre-install
Executing busybox-1.34.1-r7.trigger
OK: 545 MiB in 229 packages
cont-init: info: /etc/cont-init.d/99-add_packages.sh exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
cont-init: info: running /etc/cont-init.d/99-custom_scripts.sh
cont-init: info: /etc/cont-init.d/99-custom_scripts.sh exited 0
cont-init: info: running /etc/cont-init.d/99-elasticsearch.sh
Nextcloud is not installed - only a limited number of commands are available
Full_Text_Search option not set
cont-init: info: /etc/cont-init.d/99-elasticsearch.sh exited 0
cont-init: info: running /etc/cont-init.d/99-mariadb_discovery.sh
cont-init: info: /etc/cont-init.d/99-mariadb_discovery.sh exited 0
cont-init: info: running /etc/cont-init.d/99-ocr.sh
Nextcloud is not installed - only a limited number of commands are available
... installing apps : fulltextsearch
Installing OCR
[18:22:26] INFO: OCR Language installed : eng
[18:22:40] INFO: OCR Language installed : nld
cont-init: info: /etc/cont-init.d/99-ocr.sh exited 0
cont-init: info: running /etc/cont-init.d/99-trusted_domains.sh
Nextcloud is not installed - only a limited number of commands are available
[18:22:46] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
[18:22:48] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[18:22:48] INFO: Trusted domains set in the configuration. Refreshing domains.
[18:22:48] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 1
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```

COnfig system 1

```
Full_Text_Search: false
OCR: true
OCRLANG: eng,nld
PGID: 1000
PUID: 1000
additional_apps: inotify-tools,vim,nextcloud
certfile: fullchain.pem
data_directory: /mnt/Nextcloud
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: your-domain, your-domain2
use_own_certs: false
cifsusername: ------
cifspassword: ------
networkdisks: //192.168.1.36/Nextcloud
```

config system 2 

```
Full_Text_Search: false
OCR: false
OCRLANG: fra
PGID: 1000
PUID: 1000
additional_apps: inotify-tools,nextcloud
certfile: fullchain.pem
data_directory: /share/nextcloud
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: your-domain, your-domain2
use_own_certs: false
```

**Comment by alexbelgium** [comment]
Hi, have you tried installing it? By logging in the webui and following the installation guide. It should solve it

**Comment by malosaa** [comment]
It did a really long time before i can access the webui 

when i check my the installation


Using my mounted drive as above config.
![image](https://user-images.githubusercontent.com/13116501/206774581-a4df2877-106b-4669-9068-bb1f85e62ec6.png)
i get this: 504 Gateway Time-out

**Comment by malosaa** [comment]
Weird is this, i did wait for a long time, and after some 10 minutes i pressed refresh, and it did ask me to setup again.
But after checking my mounted folder i see some files getting created, so after that was done, i did refresh again and i could login and it works..

i really don't know what happened there, my server is really fast, so is my hass system.. 
I will test a bit, but for now i can login and don't have to set it up again

**Comment by alexbelgium** [comment]
Could you please try to create the folder, and have the same permissions as in your config options?

I've tested on my system to install on /share/Nextcloud and it worked fine once I had created the directory

**Comment by alexbelgium** [comment]
> Weird is this, i did wait for a long time, and after some 10 minutes i pressed refresh, and it did ask me to setup again. But after checking my mounted folder i see some files getting created, so after that was done, i did refresh again and i could login and it works..
> 
> i really don't know what happened there, my server is really fast, so is my hass system.. I will test a bit, but for now i can login and don't have to set it up again

That's nice! On which system are you, amd64 ? armv7 ? At least happy it seems to work

**Comment by malosaa** [comment]
> > Weird is this, i did wait for a long time, and after some 10 minutes i pressed refresh, and it did ask me to setup again. But after checking my mounted folder i see some files getting created, so after that was done, i did refresh again and i could login and it works..
> > i really don't know what happened there, my server is really fast, so is my hass system.. I will test a bit, but for now i can login and don't have to set it up again
> 
> That's nice! On which system are you, amd64 ? armv7 ? At least happy it seems to work

Yeah i'm on amd64, and its still working :)
Many thanks for trying to help me, just starred the repo.

Love your add-ons use them daily :)

Regards

**Comment by alexbelgium** [comment]
Thanks! Have a nice day

**Comment by amaciuc** [comment]
Hey @alexbelgium 

How can I deal the installation with mysql ? There is a recommendation to use `mysql` instead of `sqlite`, but I have this error using webui:

![image](https://user-images.githubusercontent.com/19391765/207697645-75d4dda5-255d-4288-bd37-767ba5b22c11.png)

Here are some trace logs:

```
[21:25:42] INFO: Currently set trusted domains :
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
[21:25:42] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[21:25:42] INFO: Trusted domains set in the configuration. Refreshing domains.
[21:25:42] INFO: ... removing previously added trusted domain (except for first one created)
Nextcloud is not installed - only a limited number of commands are available
                                                                   
  There are no commands defined in the "config:system" namespace.  
                                                                   
cont-init: info: /etc/cont-init.d/99-trusted_domains.sh exited 1
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Exception: Not installed in /data/config/www/nextcloud/lib/base.php:284

Stack trace:
#0 /data/config/www/nextcloud/lib/base.php(680): OC::checkInstalled()
#1 /data/config/www/nextcloud/lib/base.php(1144): OC::init()
#2 /data/config/www/nextcloud/cron.php(43): require_once('...')

}
```

I tried to use `occ` tool ([installation from cmd line](https://docs.nextcloud.com/server/25/admin_manual/installation/command_line_installation.html#installing-from-command-line), [database conversion](https://docs.nextcloud.com/server/25/admin_manual/configuration_server/occ_command.html#database-conversion))directly from container, but I encountered many issues.

**Comment by alexbelgium** [comment]
Hi, if you use a custom db, you need to create a user account I think. Easier alternatives are SQLite for a small account, or if you install the mariadb add-on it will provide with the script 99-mariadb_discovery.sh all informations in the addon log that must be input to use it as database

**Comment by malosaa** [comment]
And what i did was at database host i used the ip of the database host.
for me example: 192.168.1.36:3306  

for me still works like a charm, using mariaDB

**Comment by amaciuc** [comment]
I succeeded to use `mariadb` in `nextcloud` through mariadb add-on, but it wasn't so straight forward.

Therefore, I will briefly describe which steps I had followed in order to accomplish this. @alexbelgium, you might use this doc in the `nextcloud` readme as a helper for the others.

## Use mariadb as the main database

If you notice the following warning at your first `webui` running:
```
Performance warning
You chose SQLite as database.

SQLite should only be used for minimal and development instances. For production we recommend a different database backend.

If you use clients for file syncing, the use of SQLite is highly discouraged.
```
and you want to overcome this, follow the below steps:

1. Install `mariadb` add-on, configure it with some random infos and start it. It is important to start it successfully in order to be seen by `nextcloud` in the network.
2. Install `nextcloud` add-on (or restart it if you have already installed), watch the logs until you will notice the following `warning`:
```
WARNING: MariaDB addon was found! It can't be configured automatically due to the way Nextcloud works, but you can configure it manually when running the web UI for the first time using those values :
Database user : service
Database password : Eangohyuchae6aif7saich2nies8xaivaejaNgaev6gi3yohy8ha2aexaetei6oh
Database name : nextcloud
Host-name : core-mariadb:3306
```
3. Go back at `mariadb` add-on, configure it with above credentials and restart it. Make sure the add-on is creating the `netxcloud` database.
4. Go in the webui and fill all required info. Here you can view an example:
![image](https://user-images.githubusercontent.com/19391765/207888717-50b43002-a5e2-4782-b5c9-1f582309df2b.png)

**Comment by alexbelgium** [comment]
You're the best, thanks
