### ISSUE TITLE
🐛 [MyElectricalData] sqlalchemy.orm.exc.FlushError starting from version 0.8.8

### ISSUE THREAD

**Issue by vortexua** [alexbelgium/hassio-addons#601]
**Which addon?**
- Addon name : MyElectricalData
- Addon version : 0.8.10

**Describe the bug**
Starting from version 0.8.8 addon fails with  an error:

sqlalchemy.orm.exc.FlushError: Instance <ConsumptionDetail at 0x7f96000070> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such as within a load() event.

**To Reproduce**
Update addon from version 0.8.7 to  0.8.8 or 0.8.10 and start it

**Full addon log**
```
Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.8.10
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.12.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/enedisgateway2mqtt/config.yaml'
TZ='Europe/Paris'
mqtt_autodiscover='true'
verbose='true'
/etc/cont-init.d/01-custom_script.sh: executing
[12:58:02] INFO: Execute /config/enedisgateway2mqtt.sh if existing
[12:58:02] INFO: ... no script found
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
[12:58:02] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery...
[12:58:03] INFO: ... MQTT service found, fetching server detail (you can enter those manually in your config file) ...
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 2
/etc/cont-init.d/99-run.sh: executing
[12:58:04] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
Config file is a valid yaml
creating symlink
[12:58:04] INFO: Using database file found in /config/enedisgateway2mqtt/enedisgateway.db
 
[12:58:04] INFO: Starting the app
 
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2022-12-13 12:58:07.519 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-13 12:58:07.519 -  WARNING :  MIGRATION DE L'ANCIENNE BASE DE DONNÉES VERS LA NOUVELLE STRUCTURE.
2022-12-13 12:58:07.519 -  WARNING : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ▲ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-12-13 12:58:07.522 -  WARNING :  Migration des "consumption_daily"
2022-12-13 12:58:07.598 -  WARNING :   - 2021 => 0.74kW
2022-12-13 12:58:07.650 -  WARNING :   - 2022 => 1475.62kW
2022-12-13 12:58:07.671 -  WARNING :  Migration des "consumption_detail"
2022-12-13 12:58:07.852 -  WARNING :   - 2021-01 => 0.03kW
2022-12-13 12:58:08.043 -  WARNING :   - 2021-02 => 101.85kW
2022-12-13 12:58:08.261 -  WARNING :   - 2021-03 => 92.41kW
2022-12-13 12:58:08.515 -  WARNING :   - 2021-04 => 136.37kW
2022-12-13 12:58:08.761 -  WARNING :   - 2021-05 => 126.96kW
2022-12-13 12:58:08.976 -  WARNING :   - 2021-06 => 111.9kW
2022-12-13 12:58:09.222 -  WARNING :   - 2021-07 => 99.16kW
2022-12-13 12:58:09.474 -  WARNING :   - 2021-08 => 125.21kW
2022-12-13 12:58:09.725 -  WARNING :   - 2021-09 => 110.5kW
2022-12-13 12:58:09.970 -  WARNING :   - 2021-10 => 117.14kW
2022-12-13 12:58:10.340 -  WARNING :   - 2021-11 => 136.93kW
2022-12-13 12:58:10.588 -  WARNING :   - 2021-12 => 120.38kW
2022-12-13 12:58:10.807 -  WARNING :   - 2022-01 => 125.47kW
2022-12-13 12:58:11.666 -  WARNING :  Migration des "production_daily"
2022-12-13 12:58:11.670 -  WARNING :  Migration des "production_detail"
2022-12-13 12:58:11.680 -     INFO :  Configure Databases
/app/models/database.py:114: SAWarning: Column 'consumption_daily.id' is marked as a member of the primary key for table 'consumption_daily', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  day = self.session.scalars(query).one_or_none()
/app/models/database.py:114: SAWarning: Column 'consumption_detail.id' is marked as a member of the primary key for table 'consumption_detail', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  day = self.session.scalars(query).one_or_none()
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 3, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 6, in <module>
    from models.database import Database
  File "/app/models/database.py", line 1141, in <module>
    Database().init_database()
  File "/app/models/database.py", line 114, in init_database
    day = self.session.scalars(query).one_or_none()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3492, in _flush
    flush_context.finalize_flush_changes()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 477, in finalize_flush_changes
    self.session._register_persistent(other)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2518, in _register_persistent
    raise exc.FlushError(
sqlalchemy.orm.exc.FlushError: Instance <ConsumptionDetail at 0x7f96000070> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such as within a load() event.
[12:58:16] FATAL: The app has crashed. Are you sure you entered the correct config 
```

**Full addon config**
```
cycle: 14400
debug: true
wipe_influxdb: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: localhost
  port: 8086
  token: username:password
  org: "-"
  bucket: "enedis/autogen"
  asynchronous: 'false'
mqtt:
  enable: true
  hostname: localhost
  port: 1883
  username: 'username'
  password: 'password'
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "YYYYY":
    enable: 'true'
    token: XXXXX
    name: "Linky"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1582'
    consumption_price_hc: '0.1582'
    consumption_price_hp: '0.1582'
    consumption_max_date: "2021-01-01"
    consumption_detail_max_date: "2021-01-01"
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    refresh_addresse: 'false'
    refresh_contract: 'false'

```
**System**
- Supervisor version: 2022.11.2
- Host system version: Home Assistant 2022.12.4

**Comment by m4dm4rtig4n** [comment]
Le soucis est liée à un autre ticket que je viens de créer :
https://github.com/alexbelgium/hassio-addons/issues/600

**Comment by alexbelgium** [comment]
J'ai mis à jour le code pour refléter celà, et copier dans le dossier config les databases migrées (tant la nouvelle que le backup)

Est-ce que quelqu'un pourrait tester si ça fonctionne ? Je n'ai pas de compte Enedis ; merci

Ps : gardez des backups réguliers de /config et de l'addon, ça aide à garder les data en cas de soucis d'updates!

**Comment by alexbelgium** [comment]
Pourrais-tu tester la dernière version poussée? A priori les soucis de migrations sont résolus. Merci d'avance
