### ISSUE TITLE
🐛 [Joplin] Access-Control-Allow-Origin calls for Joplin URL instead of APP_BASE_URL

### ISSUE THREAD

**Issue by kayserlein** [alexbelgium/hassio-addons#617]
**Joplin**

- Addon name : Joplin
- Addon version : 2.10.4

1. Set up Joplin and Admin account
2. Receive a "Forbidden" Warning when trying to edit most elements (like creating new users).

Note: Personal app url below censored as "APPURL" 

`Timezone set from Etc/UTC to Europe/Berlin
/etc/cont-init.d/01-custom_script.sh: executing
[16:49:09] INFO: Execute /config/joplin.sh if existing
[16:49:09] INFO: ... no script found
/etc/cont-init.d/99-run.sh: executing
[16:49:09] WARNING: Warning - minimum configuration recommended : 2 cpu cores and 4 GB of memory. Otherwise the system will become unresponsive and crash.
[16:49:09] WARNING: Warning : a custom data location was selected, but the previous folder will NOT be copied. You need to do it manually
[16:49:09] INFO: Using sqlite
[16:49:09] INFO: Mailer Security set
[16:49:10] INFO: Starting Joplin. Initial user is "admin@localhost" with password "admin"
> @joplin/server@2.10.4 start
> node dist/app.js
2022-12-28 16:49:15: App: Starting server v2.10.4 (prod) on port 22300 and PID 232...
2022-12-28 16:49:15: App: Skipping NTP time check because MAX_TIME_DRIFT is 0.
2022-12-28 16:49:15: App: Running in Docker: true
2022-12-28 16:49:15: App: Public base URL: APPURL
2022-12-28 16:49:15: App: API base URL: APPURL
2022-12-28 16:49:15: App: User content base URL: APPURL
2022-12-28 16:49:15: App: Log dir: /home/joplin/packages/server/logs
2022-12-28 16:49:15: App: DB Config: {
  client: 'sqlite3',
  name: '/config/addons_config/joplin/database.sqlite',
  slowQueryLogEnabled: false,
  slowQueryLogMinDuration: 1000,
  autoMigration: true,
  asyncStackTraces: true
}
2022-12-28 16:49:15: App: Mailer Config: {
  enabled: false,
  host: '',
  port: 465,
  security: 'none',
  authUser: '',
  authPassword: '********',
  noReplyName: '',
  noReplyEmail: ''
}
2022-12-28 16:49:15: App: Content driver: { type: 1 }
2022-12-28 16:49:15: App: Content driver (fallback): null
2022-12-28 16:49:15: App: Trying to connect to database...
2022-12-28 16:49:15: App: Connection check: {
  latestMigration: { name: '20221020143305_task_states.js', done: true },
  isCreated: true,
  error: null
}
2022-12-28 16:49:15: App: Auto-migrating database...
2022-12-28 16:49:15: App: Latest migration: { name: '20221020143305_task_states.js', done: true }
2022-12-28 16:49:18: App: Performing main storage check...
2022-12-28 16:49:18: App: Database storage is special and cannot be checked this way. If the connection to the database was successful then the storage driver should work too.
2022-12-28 16:49:18: App: Starting services...
2022-12-28 16:49:18: ShareService: Starting maintenance...
2022-12-28 16:49:18: EmailService: Service will be disabled because mailer config is not set or is explicitly disabled
2022-12-28 16:49:18: TaskService: Scheduling #1 (Delete expired tokens): 0 */6 * * *
2022-12-28 16:49:18: TaskService: Scheduling #2 (Update total sizes): 0 * * * *
2022-12-28 16:49:18: TaskService: Scheduling #3 (Process oversized accounts): 30 */2 * * *
2022-12-28 16:49:18: TaskService: Scheduling #6 (Delete expired sessions): 0 */6 * * *
2022-12-28 16:49:18: TaskService: Scheduling #7 (Compress old changes): 0 0 */2 * *
2022-12-28 16:49:18: TaskService: Scheduling #8 (Process user deletions): 10 * * * *
2022-12-28 16:49:18: App: Call this for testing: `curl http://APPURL/api/ping`
2022-12-28 16:49:18: ShareService: Maintenance completed in 95ms
2022-12-28 16:50:33: App: GET /admin/user_deletions (200) (140ms)
2022-12-28 16:50:34: [error] App: 404: GET /css/index/user_deletions.css: qrfvScwPkEtUg9hKCCNwjo: Path not found: css/index/user_deletions.css
2022-12-28 16:50:34: App: GET /css/index/user_deletions.css (404) (6ms)
2022-12-28 16:50:34: [error] App: 404: GET /favicon.ico: qrfvScwPkEtUg9hKCCNwjo: Path not found: favicon.ico
2022-12-28 16:50:34: App: GET /favicon.ico (404) (3ms)
2022-12-28 16:50:35: App: GET /admin/dashboard (200) (4ms)
2022-12-28 16:51:14: [error] App: 404: GET /: ::ffff:192.168.178.34: Invalid origin: http://192.168.178.4:22300
2022-12-28 16:51:14: App: GET / (404) (2ms)
2022-12-28 16:51:14: [error] App: 404: GET /favicon.ico: ::ffff:192.168.178.34: Invalid origin: http://192.168.178.4:22300
2022-12-28 16:51:14: App: GET /favicon.ico (404) (1ms)
2022-12-28 16:51:19: App: GET / (302) (5ms)
2022-12-28 16:51:19: [error] App: 403: GET /home: ::ffff:172.30.32.1: Forbidden
2022-12-28 16:51:19: App: GET /home (403) (3ms)
2022-12-28 16:51:20: App: GET /login (200) (8ms)
2022-12-28 16:51:22: App: GET /users/me (200) (116ms)
2022-12-28 16:51:24: App: GET /home (200) (11ms)
2022-12-28 16:51:27: App: GET /items (200) (11ms)
2022-12-28 16:51:28: App: GET /admin/dashboard (200) (3ms)
2022-12-28 16:51:29: App: GET /admin/users (200) (104ms)
2022-12-28 16:51:32: [error] App: Middleware error on /admin/users/SbLgSkVx6ofgipM3ZeBpcg: ErrorForbidden: Forbidden
    at /home/joplin/packages/server/src/middleware/checkAdminHandler.ts:7:32
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/middleware/checkAdminHandler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/joplin/packages/server/dist/middleware/checkAdminHandler.js:4:12)
    at default_1 (/home/joplin/packages/server/dist/middleware/checkAdminHandler.js:15:12)
    at dispatch (/home/joplin/packages/server/node_modules/koa-compose/index.js:42:32)
    at /home/joplin/packages/server/src/middleware/ownerHandler.ts:8:9
    at Generator.next (<anonymous>)
    at /home/joplin/packages/server/dist/middleware/ownerHandler.js:8:71 {
  httpCode: 403,
  code: undefined,
  details: undefined,
  headers: {
    'Access-Control-Allow-Origin': 'https://joplinapp.org',
    vary: 'Origin'
  }
}`

Config File could not be found (neither through Studio Code Server nor File Manager nor Portainer)

System: Virtual Machine on Synology 1520+

- Supervisor version: 2022.12.1
- Host system version:  Home Assistant 2022.12.8,  Operating System 9.4, Frontend 20221213.1 - latest

**Comment by alexbelgium** [comment]
Hi, this is strange, as it is correctly passed through the addon. Not sure how to help. I've pushed a new version with `export ALLOWED_HOSTS="*"` in case this helps. Looks like you have defined a domain name but are accessing with a local ip?

**Comment by kayserlein** [comment]
No, I definitely accessed it via the domain. If I go via the IP, I only get "Invalid origin: http://192.168.178.4:22300"

Also, is the update live? My HA can't find it.
