### ISSUE TITLE
🐛 [Mealie] Server Error

### ISSUE THREAD

**Issue by chicknlil** [alexbelgium/hassio-addons#629]
Mealie

- Addon name : Mealie API / Mealie Frontend
- Addon version : v1.0.0-beta-1b-2

**Describe the bug**

Using "open webui" in front end after install brings up the following page.

![image](https://user-images.githubusercontent.com/100124187/210564920-ac1b9721-c454-4394-a807-c0bff1f5031e.png)

**To Reproduce**

After installing first Mealie API and then Mealie Frontend (and making only one small change to either configuration), started API first and then Frontend, and attempted to use "open webui" in frontend.  Then see bug report/image above.

**Full addon log**

```
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Mealie (frontend)
 A Self Hosted Recipe Manager (frontend)
-----------------------------------------------------------
 Add-on version: v1.0.0-beta-1b-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / odroid-n2)
 Home Assistant Core: 2023.1.0b5
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[13:21:46] INFO: Execute /config/addons_autoscripts/mealie-frontend.sh if existing
[13:21:46] INFO: ... no script found
[13:21:46] INFO: Exporting variables
API_URL=http://192.168.0.24:9000
PGID=1000
PUID=1000
certfile=fullchain.pem
keyfile=privkey.pem
ssl=false
[13:21:47] INFO: No config.yaml found in /config/addons_config/mealie_frontend/config.yaml, using default parameters
Permissions adapted
[13:21:47] INFO: Starting app
{"level":"info","ts":1672838507.7853074,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":""}
{"level":"warn","ts":1672838507.788314,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/app/Caddyfile","line":36}
{"level":"warn","ts":1672838507.7893357,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"warn","ts":1672838507.7896228,"logger":"http","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
{"level":"info","ts":1672838507.789756,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x400001d420"}
{"level":"info","ts":1672838507.7912557,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1672838507.7913954,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1672838507.791907,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1672838507.791939,"msg":"serving initial configuration"}
Successfully started Caddy (pid=203) - Caddy is running in the background
yarn run v1.22.19
$ nuxt start -p 3001
ℹ [HPM] Proxy created: api  -> http://192.168.0.24:9000
ℹ [HPM] Proxy rewrite rule created: "api" ~> "/api"
ℹ [HPM] Proxy created: /api  -> http://192.168.0.24:9000
ℹ Listening on: http://172.30.33.10:3001/
 ERROR  connect ECONNREFUSED 192.168.0.24:9000
  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
 ERROR  connect ECONNREFUSED 192.168.0.24:9000
  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

```
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Mealie (API)
 A Self Hosted Recipe Manager (API)
-----------------------------------------------------------
 Add-on version: v1.0.0-beta-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / odroid-n2)
 Home Assistant Core: 2023.1.0b5
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[08:18:11] INFO: Execute /config/addons_autoscripts/mealie-api.sh if existing
[08:18:11] INFO: ... no script found
[08:18:11] INFO: Exporting variables
PGID=1000
PUID=1000
certfile=fullchain.pem
keyfile=privkey.pem
ssl=false
Permissions adapted
[08:18:13] INFO: No config.yaml found in /config/addons_config/mealie_api/config.yaml, using default parameters
[08:18:13] INFO: Starting app
Production
Switching to dedicated user
Production
        User uid:    1000
        User gid:    1000
        
INFO: 04-Jan-23 08:18:19 	Database connection established.
INFO: 04-Jan-23 08:18:19 	Context impl SQLiteImpl.
INFO: 04-Jan-23 08:18:19 	Will assume non-transactional DDL.
INFO: 04-Jan-23 08:18:19 	Migration needed. Performing migration...
INFO: 04-Jan-23 08:18:19 	Context impl SQLiteImpl.
INFO: 04-Jan-23 08:18:19 	Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 233, in _catch_revision_errors
    yield
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 443, in _upgrade_revs
    for script in reversed(list(revs))
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 799, in iterate_revisions
    revisions, heads = fn(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 1454, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 527, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 527, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 552, in get_revisions
    return tuple(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 553, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 624, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '167eb69066ad'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 107, in <module>
    main()
  File "/app/mealie/db/init_db.py", line 93, in main
    command.upgrade(alembic_cfg, "head")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/alembic/env.py", line 77, in <module>
    run_migrations_online()
  File "/app/alembic/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 311, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 431, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 265, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '167eb69066ad'
```

**Full addon config**

I do not have a config.yaml file for either of these addons.

**System**

- Supervisor version:   Supervisor 2022.12.1
- Host system version:  Home Assistant 2023.1.0b5

**Comment by alexbelgium** [comment]
Please try the Mealie (Omni) addon

**Comment by chicknlil** [comment]
Is that the one labeled `Obsolete : Mealie` ? That's the only other Mealie addon I see in your repository.

Much obliged for your time and patience.

**Comment by alexbelgium** [comment]
I've just updated this addon with the name Mealie (Omni), please wait a couple hours it should appear on your installation

It's a quite complex app to support as the development seems to be very dynamic which means frequent changes to adapt to !

**Comment by alexbelgium** [comment]
Thanks!

Btw the reason I'm proposing you to go back to the "Mealie (Omni)" addon is that the dev is now proposing all-in-one images which avoids the usage of dual addons... So actually I'll very soon make obsolte the Mealie (API) and Mealie (Frontend) addons. It was really bad timing that just after I published those 2 addons he started to make this image ;-) but anyway still happy it exists ;-)

**Comment by chicknlil** [comment]
It's working fantastic!  I was able to easily login, change username/password/etc, import the database I had exported from the previous version and...perfection!  Thank you so very much!

**Comment by alexbelgium** [comment]
Perfect! Thanks for the feedback!
