### ISSUE TITLE
🐛 [Flaresolverr] Fails on startup

### ISSUE THREAD

**Issue by almico** [alexbelgium/hassio-addons#634]
**Which addon?**

- Addon name : FlareSolverr
- Addon version : 3.0.1

**Describe the bug**

On add-on startup, it fails and exits.
Reinstalling from scratch didn't change a thing.

**To Reproduce**

Install and start the add-on.

**Full addon log**

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: FlareSolverr
 Proxy server to bypass Cloudflare protection
-----------------------------------------------------------
 Add-on version: 3.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
/etc/cont-init.d/01-custom_script.sh: executing
-----------------------------------------------------------
[10:01:10] INFO: Execute /config/addons_autoscripts/flaresolverr.sh if existing
[10:01:10] INFO: ... no script found
/etc/cont-init.d/99-run.sh: executing
[10:01:10] WARNING: Warning - minimum configuration recommended : 2 cpu cores and 4 GB of memory. Otherwise the system will become unresponsive and crash.
/./etc/cont-init.d/99-run.sh: line 10: node: command not found
/etc/cont-init.d/99-run.sh: exiting 127
```

**Full addon config**

It has no config.

**System**

- Home Assistant 2023.1.1
- Supervisor 2022.12.1
- Operating System 9.4
- Frontend 20230104.0 - latest

**Comment by alexbelgium** [comment]
Hi, thanks indeed they have switched the command from node to python. I've aligned with the upstream image and at least on my system it works.

**Comment by almico** [comment]
Looks much more promising 😄

**Comment by almico** [comment]
I just discovered it crashed again:

```
2023-01-09 00:13:42 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://sample.test/latest/?order=age&sort=desc', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
2023-01-09 00:13:42 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
Traceback (most recent call last):
  File "/app/flaresolverr.py", line 95, in <module>
    run(app, host=server_host, port=server_port, quiet=True, server='waitress')
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 3172, in run
    server.run(app)
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 2853, in run
    serve(handler, host=self.host, port=self.port)
  File "/usr/local/lib/python3.11/site-packages/waitress/__init__.py", line 19, in serve
    server.run()
  File "/usr/local/lib/python3.11/site-packages/waitress/server.py", line 322, in run
    self.asyncore.loop(
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.11/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()
2023-01-09 00:13:44 ERROR    Error: Error solving the challenge. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-01-09 00:13:44 INFO     Response in 2.212 s
2023-01-09 00:13:44 INFO     172.30.32.1 POST http://192.168.1.2:8191/v1 500 Internal Server Error
/etc/cont-init.d/99-run.sh: exiting 1
```

But, I think it's a Flaresolverr issue, and not of the add-on. Right?

**Comment by alexbelgium** [comment]
It looks indeed as a specific issue for the app...
