### ISSUE TITLE
🐛 [Mealie] Issue description

### ISSUE THREAD

**Issue by JackSultan** [alexbelgium/hassio-addons#635]
**Which addon?**

- Addon name : Mealie (API)
- Addon version : v1.0.0-beta-2

**Describe the bug**

PermissionError: [Errno 13] Permission denied: '/config/addons_config/mealie_data/.secret' directly after start. I am on the HomeAssistant OS. Is this a problem?

**To Reproduce**

Installed and started the addon.

**Full addon log**

`/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Mealie (API)
 A Self Hosted Recipe Manager (API)
-----------------------------------------------------------
 Add-on version: v1.0.0-beta-2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.12.7
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/01-custom_script.sh: executing
[11:06:04] INFO: Execute /config/addons_autoscripts/mealie-api.sh if existing
[11:06:04] INFO: ... no script found
[11:06:04] INFO: Exporting variables
PGID=1000
PUID=1000
certfile=fullchain.pem
keyfile=privkey.pem
ssl=false
[11:06:05] INFO: No config.yaml found in /config/addons_config/mealie_api/config.yaml, using default parameters
Permissions adapted
[11:06:05] INFO: Starting app
Production
Switching to dedicated user
Production
        User uid:    1000
        User gid:    1000
        
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 10, in <module>
    from mealie.core import root_logger
  File "/app/mealie/core/root_logger.py", line 56, in <module>
    logger_config = get_logger_config()
  File "/app/mealie/core/root_logger.py", line 28, in get_logger_config
    settings = get_app_settings()
  File "/app/mealie/core/config.py", line 42, in get_app_settings
    return app_settings_constructor(env_file=ENV, production=PRODUCTION, data_dir=determine_data_dir())
  File "/app/mealie/core/settings/settings.py", line 154, in app_settings_constructor
    **{"SECRET": determine_secrets(data_dir, production)},
  File "/app/mealie/core/settings/settings.py", line 15, in determine_secrets
    if secrets_file.is_file():
  File "/usr/local/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/config/addons_config/mealie_data/.secret'`

**System**

- Supervisor version: Supervisor 2022.12.1
- Host system version: Operating System 9.4

**Comment by alexbelgium** [comment]
Hi, could you please install the Mealie (Omni) addon ? it's the two addons in one, and could perhaps avoid your issue. Thanks!

**Comment by JackSultan** [comment]
Hey, that other addon works for me. Perfect. Thank you very much for your work!
