### ISSUE TITLE
✨ [REQUEST] myelectricaldata / enedisgateway2mqtt : support for secrets.yaml

### ISSUE THREAD

**Issue by chrsc59** [alexbelgium/hassio-addons#667]
**Which addon?**

myelectricaldata / enedisgateway2mqtt

**Is your feature request related to a problem? Please describe.**

Cannot use secrets.yaml for tokens nor passwords

NOT tested for **InfluxDB token**

Using secrets.yaml for the **pdl token** generates "invalid pdl for this token" messages 

```
2023-01-25 10:26:38.762 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:26:38.762 -     INFO :  [19784XXX97026] STATUT DE LA PASSERELLE :
2023-01-25 10:26:38.762 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:26:38.963 -     INFO :  status: True
2023-01-25 10:26:38.963 -     INFO :  information: None
2023-01-25 10:26:38.963 -     INFO :  nb_client: 1192
2023-01-25 10:26:38.963 -     INFO :  waiting_estimation: 0.0s
2023-01-25 10:26:38.963 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:26:38.964 -     INFO :  [19784XXX97026] CHECK ACCOUNT STATUS :
2023-01-25 10:26:38.964 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:26:39.162 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-25 10:26:39.162 -    ERROR : 
2023-01-25 10:26:39.162 -    ERROR :  Le point de livraison ne correspond au token fournis, pour le réinitialiser il vous suffit de refaire un consentement
2023-01-25 10:26:39.162 -    ERROR : 
2023-01-25 10:26:39.162 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
```

using secrets.yaml for **mqtt password** generates errors during MQTT export, although connection was initially tested as successfull.

```
2023-01-25 10:21:31.773 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:31.773 -     INFO :  LOADING CONFIGURATION...
2023-01-25 10:21:31.773 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:31.773 -     INFO :  1978XXX797026
2023-01-25 10:21:31.847 -     INFO :    => Success
2023-01-25 10:21:31.847 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:31.847 -     INFO :  Connect to MQTT broker 192.168.8.81:1883
2023-01-25 10:21:31.849 -     INFO :   => Connection success
2023-01-25 10:21:31.990 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
then : 
```
2023-01-25 10:21:46.795 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:46.795 -     INFO :  EXPORTATION MQTT
2023-01-25 10:21:46.795 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:46.803 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:46.803 -     INFO :  [19784XXX97026] STATUT DU COMPTE.
2023-01-25 10:21:46.803 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/models/jobs.py", line 116, in job_import_data
    ExportMqtt(self.usage_point_id).status()
  File "/app/models/export_mqtt.py", line 67, in status
    app.MQTT.publish_multiple(consentement_expiration)
  File "/app/models/mqtt.py", line 82, in publish_multiple
    publish.multiple(payload, hostname=self.hostname, port=self.port, client_id=self.client_id, auth=auth)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/publish.py", line 168, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3029, in _handle_connack
    self.on_connect(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/publish.py", line 53, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
2023-01-25 10:21:46.810 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-25 10:21:46.810 -    ERROR : 
2023-01-25 10:21:46.810 -    ERROR :  Erreur lors de l'exportation des données dans MQTT
2023-01-25 10:21:46.810 -    ERROR :  Connection Refused: not authorised.
2023-01-25 10:21:46.810 -    ERROR : 
2023-01-25 10:21:46.810 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-01-25 10:21:46.811 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:46.811 -     INFO :  EXPORTATION HOME ASSISTANT
2023-01-25 10:21:46.811 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:46.818 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-01-25 10:21:46.819 -     INFO :  [19784XXX7026] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2023-01-25 10:21:46.819 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/models/jobs.py", line 171, in job_import_data
    HomeAssistant(self.usage_point_id).export()
  File "/app/models/export_home_assistant.py", line 86, in export
    self.myelectricaldata_usage_point_id("consumption")
  File "/app/models/export_home_assistant.py", line 201, in myelectricaldata_usage_point_id
    app.MQTT.publish_multiple(config, topic)
  File "/app/models/mqtt.py", line 82, in publish_multiple
    publish.multiple(payload, hostname=self.hostname, port=self.port, client_id=self.client_id, auth=auth)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/publish.py", line 168, in multiple
    client.loop_forever()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3029, in _handle_connack
    self.on_connect(
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/publish.py", line 53, in _on_connect
    raise mqtt.MQTTException(paho.connack_string(rc))
paho.mqtt.MQTTException: Connection Refused: not authorised.
2023-01-25 10:21:46.827 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-01-25 10:21:46.827 -    ERROR : 
2023-01-25 10:21:46.827 -    ERROR :  Erreur lors de l'exportation des données dans Home Assistant
2023-01-25 10:21:46.827 -    ERROR :  Connection Refused: not authorised.
2023-01-25 10:21:46.827 -    ERROR : 
2023-01-25 10:21:46.827 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
```

NOT tested with InfluxDB token

**Describe the solution you'd like**

Allow the use of secrets.yaml for passwords and tokens

**Describe alternatives you've considered**

**Additional context**

tested with 0.8.13-2 and 0.8.14-beta1

**Comment by alexbelgium** [comment]
Bonjour, j'ai poussé une version 0.8.13-4 et 0.8.14-beta1-2 ce matin qui devraient supporter les secrets. J'avais lié le push à https://github.com/m4dm4rtig4n/myelectricaldata/issues/288#event-8349451493

**Comment by chrsc59** [comment]
Same with :
MyElectricalData Dev
Current version: 0.8.14-beta1-2

**Comment by alexbelgium** [comment]
Thanks, I'll test when I have time

**Comment by alexbelgium** [comment]
Ok I understand. The app is not using my config.yaml system, but it's own. As such, the app directly reads the config.yaml. Implementation of the secrets.yaml feature is therefore linked to the app, not the addon and can't be implemented on my side.

**Comment by alexbelgium** [comment]
I'll close it as can't be solved from the addon side
