### ISSUE TITLE
🐛 [Paperless-NGX] Add network shares with nobrl option

### ISSUE THREAD

**Issue by chrikodo** [alexbelgium/hassio-addons#799]
**Which addon?**

- Addon name : Paperless NGX
- Addon version :  1.13.0-2

**Describe the bug**

When using a network share for the location of the paperless data folder, the sqlite db runs into an error, because the Database is locked. This is a similar problem as in https://github.com/alexbelgium/hassio-addons/issues/556 for the Calibre Addon

--> Possible solution: Add the smb shares in the 92-smb_mounts.sh file with option nobrl

**To Reproduce**

Install addon
Add network share that gets mounted on startup
set the data folder location on the network share and start the addon
sqlite throws databse is locked error message
**Full addon log**

Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/schema.py", line 40, in __exit__
    super().__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 166, in __exit__
    self.atomic.__exit__(exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.9/site-packages/django/db/transaction.py", line 262, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 330, in commit
    self._commit()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 72, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)
/etc/cont-init.d/99-run.sh: exiting 1

**Full addon config**

CONFIG_LOCATION: /config/addons_config/paperless_ng/config.yaml
OCRLANG: ENG GER
PAPERLESS_OCR_MODE: skip
PGID: 0
PUID: 0
certfile: fullchain.pem
keyfile: privkey.pem
ssl: true
networkdisks: //smbshare/paperless
cifspassword:****
cifsusername: ****
PAPERLESS_CONSUMPTION_DIR: /mnt/paperless/consumption
PAPERLESS_MEDIA_ROOT: /mnt/paperless/media
PAPERLESS_DATA_DIR: /mnt/paperless/data

**System**

- Supervisor version: Supervisor 2023.04.0
- Host system version: HassOS 9.5

**Comment by alexbelgium** [comment]
Hi, please let me know how it goes! Thanks for the detailed analysis.

**Comment by alexbelgium** [comment]
Confirmed working on my computer (after resaving the options)

**Comment by chrikodo** [comment]
Wow, was not expecting you to be that fast. Thank you so much for the quick implementation.

Works great now with the paperless data folder inside my smb share! 👍
