### ISSUE TITLE
🐛 [Guacamole] HTTP Status 404 - Not Found

### ISSUE THREAD

**Issue by svh1985** [alexbelgium/hassio-addons#859]
**Which addon?**

- Addon name : Guacamole
- Addon version : 1.5.2-pg15

**Describe the bug**
Every few weeks the Guacamole Add-On will give a 404 error. To solve it I need to completely uninstall the Add-On and remove the add-on directory in the Home Assistant config/addon_config/guacamole dir.

**To Reproduce**
No specific steps are known to me to reproduce.

**Full addon log**
```
03-Jun-2023 03:40:55.740 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
03-Jun-2023 03:40:55.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
03-Jun-2023 03:40:55.742 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
03-Jun-2023 03:40:55.742 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
03-Jun-2023 03:40:55.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
03-Jun-2023 03:40:55.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
03-Jun-2023 03:40:55.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
03-Jun-2023 03:40:55.745 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
03-Jun-2023 03:40:55.767 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.36] using APR version [1.7.0].
03-Jun-2023 03:40:55.769 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
03-Jun-2023 03:40:55.769 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
03-Jun-2023 03:40:55.787 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
03-Jun-2023 03:40:57.562 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
03-Jun-2023 03:40:57.704 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [3057] milliseconds
[03:40:57] INFO: Starting NGinx...
03-Jun-2023 03:40:57.992 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
03-Jun-2023 03:40:57.994 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.75]
03-Jun-2023 03:40:58.068 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
03-Jun-2023 03:41:04.090 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
03:41:05.795 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/addons_config/guacamole".
03:41:06.217 [main] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/config/addons_config/guacamole/guacamole.properties".
03:41:06.235 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
03:41:08.083 [main] INFO  o.a.g.extension.ExtensionModule - Multiple extensions are installed and will be loaded in order of decreasing priority:
03:41:08.084 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/config/addons_config/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.1.jar)
03:41:08.086 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/config/addons_config/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.2.jar)
03:41:08.087 [main] INFO  o.a.g.extension.ExtensionModule -  - [totp] "TOTP TFA Authentication Backend" (/config/addons_config/guacamole/extensions/guacamole-auth-totp-1.5.1.jar)
03:41:08.088 [main] INFO  o.a.g.extension.ExtensionModule -  - [totp] "TOTP TFA Authentication Backend" (/config/addons_config/guacamole/extensions/guacamole-auth-totp-1.5.2.jar)
03:41:08.089 [main] INFO  o.a.g.extension.ExtensionModule - To change this order, set the "extension-priority" property or rename the extension files. The default priority of extensions is dictated by the sort order of their filenames.
03:41:12.132 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
03:41:15.271 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
03:41:16.004 [main] INFO  o.a.g.extension.ExtensionModule - Extension "TOTP TFA Authentication Backend" (totp) loaded.
03:41:16.678 [main] INFO  o.a.g.extension.ExtensionModule - Extension "TOTP TFA Authentication Backend" (totp) loaded.
03:41:17.166 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
03-Jun-2023 03:41:17.524 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
03-Jun-2023 03:41:17.577 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
03-Jun-2023 03:41:17.708 INFO [AsyncFileHandlerWriter-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.google.common.collect.Sets$FilteredSet]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.google.common.collect.Sets$FilteredSet]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1432)
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1420)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1259)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
		at com.google.common.collect.Sets.filter(Sets.java:1077)
		at com.google.common.collect.Sets.filter(Sets.java:1038)
		at com.google.common.collect.Maps$FilteredKeyMap.createKeySet(Maps.java:3058)
		at com.google.common.collect.Maps$ViewCachingAbstractMap.keySet(Maps.java:3819)
		at com.google.inject.internal.PackageNameCompressor.buildClassNameLegend(PackageNameCompressor.java:161)
		at com.google.inject.internal.PackageNameCompressor.compressPackagesInMessage(PackageNameCompressor.java:114)
		at com.google.inject.internal.Messages.formatMessages(Messages.java:115)
		at com.google.inject.CreationException.getMessage(CreationException.java:50)
		at java.base/java.lang.Throwable.getLocalizedMessage(Unknown Source)
		at java.base/java.lang.Throwable.toString(Unknown Source)
		at java.base/java.lang.String.valueOf(Unknown Source)
		at java.base/java.io.PrintWriter.println(Unknown Source)
		at org.apache.juli.OneLineFormatter$IndentingPrintWriter.println(OneLineFormatter.java:283)
		at java.base/java.lang.Throwable$WrappedPrintWriter.println(Unknown Source)
		at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
		at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
		at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:159)
		at org.apache.juli.FileHandler.publish(FileHandler.java:233)
		at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:138)
		at org.apache.juli.AsyncFileHandler$1.run(AsyncFileHandler.java:131)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "AsyncFileHandlerWriter-1" java.lang.NoClassDefFoundError: com/google/common/collect/Sets$FilteredSet
	at com.google.common.collect.Sets.filter(Sets.java:1077)
	at com.google.common.collect.Sets.filter(Sets.java:1038)
	at com.google.common.collect.Maps$FilteredKeyMap.createKeySet(Maps.java:3058)
	at com.google.common.collect.Maps$ViewCachingAbstractMap.keySet(Maps.java:3819)
	at com.google.inject.internal.PackageNameCompressor.buildClassNameLegend(PackageNameCompressor.java:161)
	at com.google.inject.internal.PackageNameCompressor.compressPackagesInMessage(PackageNameCompressor.java:114)
	at com.google.inject.internal.Messages.formatMessages(Messages.java:115)
	at com.google.inject.CreationException.getMessage(CreationException.java:50)
	at java.base/java.lang.Throwable.getLocalizedMessage(Unknown Source)
	at java.base/java.lang.Throwable.toString(Unknown Source)
	at java.base/java.lang.String.valueOf(Unknown Source)
	at java.base/java.io.PrintWriter.println(Unknown Source)
	at org.apache.juli.OneLineFormatter$IndentingPrintWriter.println(OneLineFormatter.java:283)
	at java.base/java.lang.Throwable$WrappedPrintWriter.println(Unknown Source)
	at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
	at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
	at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:159)
	at org.apache.juli.FileHandler.publish(FileHandler.java:233)
	at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:138)
	at org.apache.juli.AsyncFileHandler$1.run(AsyncFileHandler.java:131)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [com.google.common.collect.Sets$FilteredSet]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1422)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1259)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
03-Jun-2023 03:41:17.750 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [19,680] ms
	... 23 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.google.common.collect.Sets$FilteredSet]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1432)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1420)
	... 25 more
03-Jun-2023 03:41:17.765 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
03-Jun-2023 03:41:17.811 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [20105] milliseconds
```
Log after uninstalling the Add-On while keeping config:
```
06-Jun-2023 17:31:45.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
06-Jun-2023 17:31:45.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
06-Jun-2023 17:31:45.759 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
06-Jun-2023 17:31:45.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
06-Jun-2023 17:31:45.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
06-Jun-2023 17:31:45.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
06-Jun-2023 17:31:45.763 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
06-Jun-2023 17:31:45.764 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
06-Jun-2023 17:31:45.765 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
06-Jun-2023 17:31:45.766 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
06-Jun-2023 17:31:45.767 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
06-Jun-2023 17:31:45.767 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
06-Jun-2023 17:31:45.795 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.36] using APR version [1.7.0].
06-Jun-2023 17:31:45.797 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
06-Jun-2023 17:31:45.798 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
06-Jun-2023 17:31:45.815 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.2 15 Mar 2022]
06-Jun-2023 17:31:47.350 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
06-Jun-2023 17:31:47.441 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [2772] milliseconds
[17:31:47] INFO: Starting NGinx...
06-Jun-2023 17:31:47.701 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
06-Jun-2023 17:31:47.702 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.75]
06-Jun-2023 17:31:47.774 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
06-Jun-2023 17:31:53.747 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17:31:55.568 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/addons_config/guacamole".
17:31:55.970 [main] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/config/addons_config/guacamole/guacamole.properties".
17:31:55.982 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
17:31:58.144 [main] INFO  o.a.g.extension.ExtensionModule - Multiple extensions are installed and will be loaded in order of decreasing priority:
17:31:58.145 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/config/addons_config/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.1.jar)
17:31:58.145 [main] INFO  o.a.g.extension.ExtensionModule -  - [postgresql] "PostgreSQL Authentication" (/config/addons_config/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.2.jar)
17:31:58.146 [main] INFO  o.a.g.extension.ExtensionModule -  - [totp] "TOTP TFA Authentication Backend" (/config/addons_config/guacamole/extensions/guacamole-auth-totp-1.5.1.jar)
17:31:58.147 [main] INFO  o.a.g.extension.ExtensionModule -  - [totp] "TOTP TFA Authentication Backend" (/config/addons_config/guacamole/extensions/guacamole-auth-totp-1.5.2.jar)
17:31:58.148 [main] INFO  o.a.g.extension.ExtensionModule - To change this order, set the "extension-priority" property or rename the extension files. The default priority of extensions is dictated by the sort order of their filenames.
17:32:02.695 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
17:32:06.173 [main] INFO  o.a.g.extension.ExtensionModule - Extension "PostgreSQL Authentication" (postgresql) loaded.
17:32:06.922 [main] INFO  o.a.g.extension.ExtensionModule - Extension "TOTP TFA Authentication Backend" (totp) loaded.
17:32:07.591 [main] INFO  o.a.g.extension.ExtensionModule - Extension "TOTP TFA Authentication Backend" (totp) loaded.
17:32:08.042 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
06-Jun-2023 17:32:08.477 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
06-Jun-2023 17:32:08.503 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
06-Jun-2023 17:32:08.623 INFO [AsyncFileHandlerWriter-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.google.common.base.Predicates$CompositionPredicate]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.google.common.base.Predicates$CompositionPredicate]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1432)
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1420)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1259)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
		at com.google.common.base.Predicates.compose(Predicates.java:227)
		at com.google.common.collect.Maps.keyPredicateOnEntries(Maps.java:2462)
		at com.google.common.collect.Maps.filterKeys(Maps.java:2496)
		at com.google.inject.internal.PackageNameCompressor.compressPackagesInMessage(PackageNameCompressor.java:114)
		at com.google.inject.internal.Messages.formatMessages(Messages.java:115)
		at com.google.inject.CreationException.getMessage(CreationException.java:50)
		at java.base/java.lang.Throwable.getLocalizedMessage(Unknown Source)
		at java.base/java.lang.Throwable.toString(Unknown Source)
		at java.base/java.lang.String.valueOf(Unknown Source)
		at java.base/java.io.PrintWriter.println(Unknown Source)
		at org.apache.juli.OneLineFormatter$IndentingPrintWriter.println(OneLineFormatter.java:283)
		at java.base/java.lang.Throwable$WrappedPrintWriter.println(Unknown Source)
		at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
		at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
		at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:159)
		at org.apache.juli.FileHandler.publish(FileHandler.java:233)
		at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:138)
		at org.apache.juli.AsyncFileHandler$1.run(AsyncFileHandler.java:131)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.base/java.lang.Thread.run(Unknown Source)
06-Jun-2023 17:32:08.634 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [20,858] ms
Exception in thread "AsyncFileHandlerWriter-1" java.lang.NoClassDefFoundError: com/google/common/base/Predicates$CompositionPredicate
	at com.google.common.base.Predicates.compose(Predicates.java:227)
	at com.google.common.collect.Maps.keyPredicateOnEntries(Maps.java:2462)
	at com.google.common.collect.Maps.filterKeys(Maps.java:2496)
	at com.google.inject.internal.PackageNameCompressor.compressPackagesInMessage(PackageNameCompressor.java:114)
	at com.google.inject.internal.Messages.formatMessages(Messages.java:115)
	at com.google.inject.CreationException.getMessage(CreationException.java:50)
	at java.base/java.lang.Throwable.getLocalizedMessage(Unknown Source)
	at java.base/java.lang.Throwable.toString(Unknown Source)
	at java.base/java.lang.String.valueOf(Unknown Source)
	at java.base/java.io.PrintWriter.println(Unknown Source)
	at org.apache.juli.OneLineFormatter$IndentingPrintWriter.println(OneLineFormatter.java:283)
	at java.base/java.lang.Throwable$WrappedPrintWriter.println(Unknown Source)
	at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
	at java.base/java.lang.Throwable.printStackTrace(Unknown Source)
	at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:159)
	at org.apache.juli.FileHandler.publish(FileHandler.java:233)
	at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:138)
	at org.apache.juli.AsyncFileHandler$1.run(AsyncFileHandler.java:131)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [com.google.common.base.Predicates$CompositionPredicate]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1422)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1259)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
	... 21 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.google.common.base.Predicates$CompositionPredicate]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1432)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1420)
	... 23 more
06-Jun-2023 17:32:08.665 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
06-Jun-2023 17:32:08.712 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [21270] milliseconds

```

**Full addon config**

```
EXTENSIONS: " auth-totp"
TZ: Europe/Amsterdam
```

**System**
- Supervisor version: 2023.04.1
- Host system version: HassOS 10.2

**Comment by alexbelgium** [comment]
Hi, this seems very difficult to troubleshoot if it occurs every couple weeks. Thanks for both logs, I've done a diff-check and nothing obvious is visible. Have you tried to see if the issue is with the internal data, or with the config data ? I mean by uninstalling/readding the addon and restarting it (without touching the data in `/config/addon_config/guacamole`); or by deleting the folder `/config/addon_config/guacamole` and restarting without touching the addon itself.

Thanks !
