### ISSUE TITLE
enedisgateway2mqtt : Invalid header value b'0.7.3\n'

### ISSUE THREAD

**Issue by lebrou34** [alexbelgium/hassio-addons#87]
Bonjour - merci pour le super job - tellement plus simple de l'avoir en add-on :=)

En revanche,, Je viens de mettre a jour la version 0.7.3 et j'ai l'erreur ci dessous.

2021-11-17 15:16:40.856044 - INFO  : =====> ERROR : Exception <======
2021-11-17 15:16:40.856111 - INFO  : Invalid header value b'0.7.3\n'
Traceback (most recent call last):
  File "/app/daily.py", line 201, in dailyBeetwen
    daily = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 132, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.3\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 619, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 219, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 34, in getDaily
    data = dailyBeetwen(headers, cur, con, url, pdl, mode, dateBegin, dateEnded, last_activation_date)
  File "/app/daily.py", line 337, in dailyBeetwen
    for error_key, error_msg in daily.items():
UnboundLocalError: local variable 'daily' referenced before assignment

**Comment by alexbelgium** [comment]
Bonjour,

Merci pour le feedback. @m4dm4rtig4n, une idée?

**Comment by vmar83** [comment]
Bonjour,

J'ai une erreur similaire 

```
2021-11-17 16:56:55.780601 - INFO  : Get contract :
2021-11-17 16:56:55.780838 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 619, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 185, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 132, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.3\n'
[16:56:56] FATAL: The app has crashed. Are you sure you entered the correct config options?
```

Voici mon fichier de config si cela peux vous aider :

```
debug: false

mqtt:
  host: homeassistant # MANDATORY
  port: 1883
  username: "user"
  password: "pass"
  prefix: enedis_gateway
  client_id: enedis_gateway
  retain: true
  qos: 0

home_assistant:
  discovery: false
  discovery_prefix: homeassistant
  card_myenedis: false

influxdb:
  host: 192.168.0.13
  port: 8086
  token: token
  org: home
  bucket: enedis_gateway

enedis_gateway:
  pdl_num:
    token: token
    plan: HP/HC
    consumption: true
    consumption_detail: true
    consumption_price_hc: 0.1453
    consumption_price_hp: 0.1909
    consumption_price_base: 0.1909
    production: false
    production_detail: false
    addresses: true
```

**Comment by lebrou34** [comment]
> @lebrou34 difficile à dire, tu peut nous post ton config.yaml "anonymisé" stp ?

voila
##########
# GLOBAL #
##########
debug: true
####################
##      MQTT      ##
####################
mqtt:
  host: 192.168.8.38
  port: 1883
  username: ""
  password: ""
  prefix: enedis_gateway
  client_id: enedis_gateway
  retain: true
  qos: 0
####################
## Home assistant ##
####################
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  card_myenedis: true
###############
## Influx DB ##
###############
influxdb:
  host: 192.168.8.36
  port: 8086
  token: 1234
  org: 1234
  bucket: 1234
####################
## ENEDIS GATEWAY ##
####################
enedis_gateway:
#  PDL_1:
  pdl_num:
    token: 1234
    plan: HP/HC
    consumption: true
    consumption_detail: true
    consumption_price_hc: 0.136
    consumption_price_hp: 0.1821
    consumption_price_base: 0.1781
    production: false
    production_detail: false
#    offpeak_hours: ""        # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-00h10;01h00-06h00
    addresses: true

**Comment by m4dm4rtig4n** [comment]
A 1ere vu le soucis viendrais du token que je set dans les header des query API.
Un caractére bidon que ce serait inséré ?

**Comment by lebrou34** [comment]
je viens de verifier a priori non.

**Comment by vmar83** [comment]
@m4dm4rtig4n : Quand je consulte les fichiers sources sur VSCODE, le fichier app/VERSION contient un retour à la ligne après le numéro de version sur la branche 0.7.3 qui n'est pas présent sur la branche 0.7.1 par exemple.

En vérifiant la construction du header dans le fichier main.py (ligne 176)

```
    headers = {
        'Content-Type': 'application/json',
        'Authorization': pdl_config['token'],
        'call-service': "enedisgateway2mqtt",
        'version': VERSION
    }
```

Et la source de la variable VERSION main.py ligne 32

```
fichier = open("/app/VERSION", "r")
VERSION = fichier.read()
fichier.close()
```

Il me semble que ce soit la source de ce bug.

**Comment by m4dm4rtig4n** [comment]
C'est fix, c'était effectivement une soucis \n en trop :p
