### ISSUE TITLE
enedisgateway2mqtt : Issues with mandatory config

### ISSUE THREAD

**Issue by LittleBigDev** [alexbelgium/hassio-addons#89]
I set all mandatory config, but still getting errors : 
```
[17:33:14] INFO: Starting the app
 
2021-11-17 17:33:14.537136 - ERROR : Some mandatory parameters are missing :
2021-11-17 17:33:14.537181 - ERROR : - PDL must be 14 characters (PDL_1 => 5)
2021-11-17 17:33:14.537193 - ERROR : - enedis_gateway.PDL_1.TOKEN
2021-11-17 17:33:14.537202 - ERROR : - PDL must be 14 characters (token => 5)
2021-11-17 17:33:14.537210 - ERROR : - enedis_gateway.token.TOKEN
2021-11-17 17:33:14.537217 - ERROR : - PDL must be 14 characters (plan => 4)
2021-11-17 17:33:14.537224 - ERROR : - enedis_gateway.plan.TOKEN
2021-11-17 17:33:14.537232 - ERROR : - PDL must be 14 characters (consumption => 11)
2021-11-17 17:33:14.537245 - ERROR : - enedis_gateway.consumption.TOKEN
2021-11-17 17:33:14.537261 - ERROR : - PDL must be 14 characters (consumption_detail => 18)
2021-11-17 17:33:14.537275 - ERROR : - enedis_gateway.consumption_detail.TOKEN
2021-11-17 17:33:14.537290 - ERROR : - PDL must be 14 characters (consumption_price_hc => 20)
2021-11-17 17:33:14.537302 - ERROR : - enedis_gateway.consumption_price_hc.TOKEN
2021-11-17 17:33:14.537313 - ERROR : - PDL must be 14 characters (consumption_price_hp => 20)
2021-11-17 17:33:14.537332 - ERROR : - enedis_gateway.consumption_price_hp.TOKEN
2021-11-17 17:33:14.537350 - ERROR : - PDL must be 14 characters (consumption_price_base => 22)
2021-11-17 17:33:14.537371 - ERROR : - enedis_gateway.consumption_price_base.TOKEN
2021-11-17 17:33:14.537386 - ERROR : - PDL must be 14 characters (production => 10)
2021-11-17 17:33:14.537404 - ERROR : - enedis_gateway.production.TOKEN
2021-11-17 17:33:14.537416 - ERROR : - PDL must be 14 characters (production_detail => 17)
2021-11-17 17:33:14.537431 - ERROR : - enedis_gateway.production_detail.TOKEN
2021-11-17 17:33:14.537446 - ERROR : - PDL must be 14 characters (addresses => 9)
2021-11-17 17:33:14.537462 - ERROR : - enedis_gateway.addresses.TOKEN
2021-11-17 17:33:14.537477 - ERROR : 
2021-11-17 17:33:14.537489 - ERROR : You can get list of parameters here :
2021-11-17 17:33:14.537503 - ERROR :  => https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file
2021-11-17 17:33:14.537519 - CRITICAL : -- Stop application --
```

I'm not sure about the syntax for InfluxDB token and bucket (influxDB v1).
Also, not sure if must surround data with double quotes or not.

Please help ? :)

**Comment by alexbelgium** [comment]
@m4dm4rtig4n a priori c'est pour l'app je te laisse la main

**Comment by m4dm4rtig4n** [comment]
Je pense que tu t'est planter dans l'indentation du Yaml et du coup il considére tt les champs dans enedisgateway comme des PDL.
```
enedis_gateway:
  TON_NUMERO_DE_PDL:
    token: TON_TOKEN
    ....
```

**Comment by LittleBigDev** [comment]
AH c'est ça que j'avais pas compris. J'ai cru que PDL_1 avait besoin d'être renseigné :
```
  PDL_1: <mon pdl>
  token: <ma-token>
  plan: BASE                 # BASE or HP/HC
  consumption: true                 
  consumption_detail: true         
  consumption_price_hc: 0.1360
  consumption_price_hp: 0.1821
  consumption_price_base: 0.1605
  production: false                 
  production_detail: false          
#    offpeak_hours: ""        # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-00h10;01h00-06h00
  addresses: true
  ```
  C'est plus clair maintenant (et du coup mon autre issue sur l'indentation est à fermer)

**Comment by LittleBigDev** [comment]
J'ai malgré tout un problème de config je pense.
```
2021-11-17 18:07:01.801100 - INFO  : Get contract :
2021-11-17 18:07:01.801225 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 619, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 185, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 108, in apiRequest
    query_result = json.loads(query_result[0][1])
IndexError: list index out of range
```
En remontant un peu le code, c'est la query `SELECT * FROM config WHERE key = 'config'` qui ne retourne probablement pas ce qui est attendu.  
J'ai essayé de trouver la table `config` mais je ne sais pas comment faire dans InfluxDB (@alexbelgium je peux la voir depuis le menu "Explore" d'InfluxDB ?)  
A mon avis j'ai mal saisi la token, le bucket, ou les deux... Un petit exemple serait bienvenu :)

**Comment by LittleBigDev** [comment]
Si j'ai bien compris, les tables ne sont pas créées dans InfluxDB, mais dans `/data/enedisgateway.db`. Malheureusement je n'y ai pas accès, donc pas pu vérifie rle contenu de la table `config`.

**Comment by foXaCe** [comment]
bonsoir
moi j'ai ca comme bug. je suis partie sur une install fresh

2021-11-17 19:34:43.686905 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 619, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 185, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 132, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.3\n'
[19:34:43] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by alexbelgium** [comment]
> Si j'ai bien compris, les tables ne sont pas créées dans InfluxDB, mais dans `/data/enedisgateway.db`. Malheureusement je n'y ai pas accès, donc pas pu vérifier le contenu de la table `config`.

Il y a moyen d'y accéder avec une app comme l'addon portainer qui promet d'ouvrir une console dans le container

**Comment by foXaCe** [comment]
pouvoir éditer le config.yaml dans la page configuration de l'addon tu pense que ce serait possible de l'ajouter ?

**Comment by foXaCe** [comment]
c bon j'ai rajouter
Europe/Paris
dans TZ
peut etre le mettre par défaut pour éviter les oublies

**Comment by alexbelgium** [comment]
> pouvoir éditer le config.yaml dans la page configuration de l'addon tu pense que ce serait possible de l'ajouter ?

C'est trop compliqué de par le nombre de paramètres, et ne permet pas la flexibilité d'évolution futures. Franchement la gestion via un fichier externe est plus simple... Au final on se retrouverais de toute manière avec le même contenu en yaml que dans le fichier externe de toute manière...

**Comment by foXaCe** [comment]
d'accord je comprends

**Comment by alexbelgium** [comment]
Par contre je pense pouvoir exposer la database en la mettant dans un fichier accessible si c'est utile

**Comment by foXaCe** [comment]
oui pourquoi pas

**Comment by alexbelgium** [comment]
Par contre je pense à un truc : comme il n'y a pas d'ui de ns cet addon je pourrais faire en sorte que le bouton pour ouvrir le webui ouvre le fichier config.yaml dans un éditeur qui inclus la validation yaml... C'est plus complexe à faire à voir si il y a un intérêt

**Comment by foXaCe** [comment]
Je voudrais pas te rajouter du travail mais oui je trouve que l'idée est
bonne

**Comment by m4dm4rtig4n** [comment]
@foXaCe soucis réglée dans la 0.7.4
@LittleBigDev soucis avec le cache, tente un reset du cache (rm du enedisgateway.db)

**Comment by LittleBigDev** [comment]
>  @LittleBigDev soucis avec le cache, tente un reset du cache (rm du enedisgateway.db)
@m4dm4rtig4n on n'a pas la main sur la DB dans HassOs supervisé :(

**Comment by alexbelgium** [comment]
> > @LittleBigDev soucis avec le cache, tente un reset du cache (rm du enedisgateway.db)
> 
> @m4dm4rtig4n on n'a pas la main sur la DB dans HassOs supervisé :(

si, depuis le dernière version il est exposé dans le même dossier que le fichier config

**Comment by foXaCe** [comment]
scripts/99-run.sh: executing
[13:04:06] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
Config file is a valid yaml
ln: failed to create symbolic link '/data/enedisgateway.db': File exists
scripts/99-run.sh: exiting 1

**Comment by foXaCe** [comment]
sur fresh install

**Comment by alexbelgium** [comment]
Tu peux faire un refresh repo et rebuild? Je pensais avoir corrigé ça ce matin... Merci

**Comment by foXaCe** [comment]
ok j'ai reussi

**Comment by foXaCe** [comment]
j'ai ca maintenant mais je pense que ca viens d'un probleme de demande api depasser pour aujourd'hui avec tout les test que j'ai fait

2021-11-18 12:08:04.130849 - INFO  : Get contract :
2021-11-18 12:08:04.131158 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 622, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 185, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 108, in apiRequest
    query_result = json.loads(query_result[0][1])
IndexError: list index out of range
[12:08:04] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by alexbelgium** [comment]
C'est bien possible...

**Comment by m4dm4rtig4n** [comment]
Tu n'aurais pas ce message d'erreur la en cas de dépassement normalement.
Tu peut me donner ton config.yaml stp que je teste avec ta config ?

**Comment by foXaCe** [comment]
tu la dans le discord

**Comment by LittleBigDev** [comment]
Salut @alexbelgium et @m4dm4rtig4n ,

J'ai mis à jour, et ça continue de crash. J'ai été voir le contenu de la table `config` : elle est vide.

Les logs :
```
[13:41:10] INFO: Starting the app
 
2021-11-18 12:41:10.521673 - INFO  : ####################################################################################
2021-11-18 12:41:10.521715 - INFO  : MQTT
2021-11-18 12:41:10.521726 - INFO  :  - host : 192.168.X.XX
2021-11-18 12:41:10.521735 - INFO  :  - port : 1883
2021-11-18 12:41:10.521743 - INFO  :  - username : <mon username mqtt>
2021-11-18 12:41:10.521750 - INFO  :  - password : ** hidden **
2021-11-18 12:41:10.521757 - INFO  :  - prefix : enedis_gateway
2021-11-18 12:41:10.521764 - INFO  :  - client_id : enedis_gateway
2021-11-18 12:41:10.521779 - INFO  :  - retain : True
2021-11-18 12:41:10.521792 - INFO  :  - qos : 0
2021-11-18 12:41:10.521805 - INFO  : ####################################################################################
2021-11-18 12:41:10.521821 - INFO  : Home Assistant
2021-11-18 12:41:10.521840 - INFO  :  - discovery : False
2021-11-18 12:41:10.521854 - INFO  :  - discovery_prefix : homeassistant
2021-11-18 12:41:10.521872 - INFO  :  - card_myenedis : True
2021-11-18 12:41:10.521888 - INFO  : ####################################################################################
2021-11-18 12:41:10.521897 - INFO  : InfluxDB
2021-11-18 12:41:10.521911 - INFO  :  - host : 192.168.X.XX
2021-11-18 12:41:10.521918 - INFO  :  - port : 8086
2021-11-18 12:41:10.521926 - INFO  :  - token : ** hidden **
2021-11-18 12:41:10.521935 - INFO  :  - org : -
2021-11-18 12:41:10.521946 - INFO  :  - bucket : home_assistant/autogen
2021-11-18 12:41:10.521954 - INFO  : ####################################################################################
2021-11-18 12:41:10.521961 - INFO  : Enedis Gateway
2021-11-18 12:41:10.521969 - INFO  :  - XXXXXXXXXXXXXX (mon PDL)
2021-11-18 12:41:10.521976 - INFO  :      token : ** hidden **
2021-11-18 12:41:10.521983 - INFO  :      plan : BASE
2021-11-18 12:41:10.521990 - INFO  :      consumption : True
2021-11-18 12:41:10.521998 - INFO  :      consumption_detail : True
2021-11-18 12:41:10.522012 - INFO  :      consumption_price_hc : 0.136
2021-11-18 12:41:10.522025 - INFO  :      consumption_price_hp : 0.1821
2021-11-18 12:41:10.522034 - INFO  :      consumption_price_base : 0.1605
2021-11-18 12:41:10.522041 - INFO  :      production : False
2021-11-18 12:41:10.522048 - INFO  :      production_detail : False
2021-11-18 12:41:10.522055 - INFO  :      addresses : True
2021-11-18 12:41:10.522063 - INFO  :      offpeak_hours : None
2021-11-18 12:41:10.522070 - INFO  :      refresh_contract : False
2021-11-18 12:41:10.522077 - INFO  :      refresh_addresses : False
2021-11-18 12:41:10.522084 - INFO  : ####################################################################################
2021-11-18 12:41:10.522096 - INFO  : Check database/cache
2021-11-18 12:41:10.522157 - INFO  :  => Init SQLite Database
2021-11-18 12:41:10.544354 - INFO  : ####################################################################################
2021-11-18 12:41:10.544424 - INFO  : MQTT Connect
2021-11-18 12:41:10.545351 - INFO  :  => Connected to MQTT Broker!
2021-11-18 12:41:10.545723 - INFO  : ####################################################################################
2021-11-18 12:41:10.545845 - INFO  : InfluxDB connect :
2021-11-18 12:41:10.548951 - INFO  :  => Connection success
2021-11-18 12:41:10.549398 - INFO  : ####################################################################################
2021-11-18 12:41:10.549430 - INFO  : #                                XXXXXXXXXXXXXX (<- mon PDL)              #
2021-11-18 12:41:10.549448 - INFO  : ####################################################################################
2021-11-18 12:41:10.549463 - INFO  : Get contract :
2021-11-18 12:41:10.549885 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 622, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 185, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 108, in apiRequest
    query_result = json.loads(query_result[0][1])
IndexError: list index out of range
[12:41:10] FATAL: The app has crashed. Are you sure you entered the correct config options?
```
`query_result = json.loads(query_result[0][1])` génère l'erreur "IndexError: list index out of range"
=> normal ; la table `config` est vide !

Je veux bien un exemple de config.yaml complet, pour que je compare avec le mien (j'ai toujours des doutes sur les quotes, et sur la manière de saisir les données doubles, genre user/password ou database/retention...

**Comment by m4dm4rtig4n** [comment]
Soucis de mon coté, fix dans la 0.7.5.

**Comment by alexbelgium** [comment]
ok je mets à jour l'addon

**Comment by LittleBigDev** [comment]
Je dois me recentrer sur le taf là, je suis trop dispersé. Je vous fais un retour ce soir :)

**Comment by foXaCe** [comment]
avec la 0.7.5dev

2021-11-18 13:53:28.083555 - INFO  : Get contract :
2021-11-18 13:53:28.083792 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 624, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 251, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}",
headers=headers, data=json.dumps(data))
  File "/app/function.py", line 107, in apiRequest
    query_result = json.loads(query_result[0][1])
IndexError: list index out of range
[13:53:28] FATAL: The app has crashed. Are you sure you entered the
correct config options?


Le jeu. 18 nov. 2021 à 14:40, Bastien Bieri ***@***.***> a
écrit :

**Comment by m4dm4rtig4n** [comment]
J'ai oublier de préciser qu'il faut reset le cache.

**Comment by Mushu77** [comment]
Bonjour m4dm4rtig4n,
même erreur que FoXaCe sur une install fresh et wipe cache activé dans la config :-(

2021-11-18 15:17:26.180751 - INFO  : Get contract :
Traceback (most recent call last):
  File "/app/main.py", line 624, in <module>
2021-11-18 15:17:26.181149 - INFO  :  => Query API
    run(pdl, pdl_config)
  File "/app/main.py", line 251, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 107, in apiRequest
    query_result = json.loads(query_result[0][1])
IndexError: list index out of range
[15:17:26] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by alexbelgium** [comment]
yep erreur de ma part j'ai pushé sur 0.7.5dev au lieu de 0.7.5
j'ai mis une nouvelle version à l'instant

**Comment by alexbelgium** [comment]
je pense que je vais passer sur "latest" pour éviter ça, et utiliser le numéro de version pour informer HA qu'il faut rebuild le addon (donc mettre à jour sur la dernière version du latest)

**Comment by Mushu77** [comment]
ah yes merci @alexbelgium ça fonctionne maintenant :-)

**Comment by foXaCe** [comment]
pareil pour moi

merci @alexbelgium et @m4dm4rtig4n

**Comment by m4dm4rtig4n** [comment]
@alexbelgium tu peut effectivement te base sur les nouveau build latest, normalement il sera tjr sur la dernière version de l'application.

**Comment by m4dm4rtig4n** [comment]
Pour le soucis de désynchro je viens d'appliquer un petit check de consistance sur la bdd, qui reset automatiquement le cache si il détecte un soucis.

**Comment by LittleBigDev** [comment]
Mis à jour, relancé, et cette fois je n'ai plus d'erreurs de config ou autre, j'ai tout un tas d'import de data :
```
2021-11-18 14:53:04.866473 - INFO  : Load 2020-12-31 => 2021-01-07
2021-11-18 14:53:04.867022 - INFO  : Data is missing between 2020-12-31 / 2021-01-07
2021-11-18 14:53:04.867059 - INFO  :  => Load data from API
```
En revanche je suis allé voir dans les tables et je ne vois rien. C'est normal ? `consumption_detail`, `consumption_dayly`, `contracts`, `addresses` tout est vide. J'ai juste `config` qui a une entrée "lastUpdate"

J'ai accédé à ces données avec "DB Brower for SQLite", en tapant sur `/config/enedisgateway2mqtt/enedisgateway.db` via samba.

**Comment by alexbelgium** [comment]
C'est confirmé ? La database reste vide ?

**Comment by LittleBigDev** [comment]
@alexbelgium toujours vide. Même `config`.

**Comment by LittleBigDev** [comment]
Chaque fois que je redémarre l'addon, j'ai le même log sur la database :
```
2021-11-18 18:48:44.216209 - INFO  : Check database/cache
2021-11-18 18:48:44.216270 - INFO  :  => Connect to SQLite Database
2021-11-18 18:48:44.221470 - INFO  : =====> ERROR : Exception <======
2021-11-18 18:48:44.221510 - INFO  : table production_detail has 5 columns but 6 values were supplied
2021-11-18 18:48:44.221529 - INFO  : <!> Database structure is invalid <!>
2021-11-18 18:48:44.221542 - INFO  :  => Reset database
2021-11-18 18:48:44.221830 - INFO  :  => Reconnect
2021-11-18 18:48:44.240429 - INFO  : 
```

**Comment by LittleBigDev** [comment]
Après màj à la toute dernière version 0.7.6, je n'ai plus le souci de DB. Et la table config a quelques entrées (pas grand chose, mais quelque chose (un objet json avec call_numbern max_call, etc...)

Malheureusement, limite dépassée. 
```
####################################################################################
2021-11-18 19:54:34.435561 - INFO  : Get contract :
2021-11-18 19:54:34.435849 - INFO  :  => Query API
2021-11-18 19:54:34.634129 - INFO  :  Limite de 50 demandes par jour atteinte. Merci de mettre à jour vos intégrations afin de réduire  le nombre de demandes par jour
2021-11-18 19:54:34.635078 - INFO  : -- Stop import --
2021-11-18 19:54:34.635141 - INFO  : ####################################################################################
2021-11-18 19:54:34.635411 - INFO  : IMPORT FINISH
2021-11-18 19:54:34.635438 - INFO  : ####################################################################################
```
Donc  pour le reste on verra demain :)

**Comment by alexbelgium** [comment]
En tout cas j'ai vérifié il n'y a qu'une db... Donc a priori le symlink fonctionne et tout ce qui est écrit par l'app devrait s'y retrouver !

**Comment by LittleBigDev** [comment]
@alexbelgium c'est bon, les données arrivent dans la base !
J'ai un autre problème, mais ça sera côté enedisgateway2mqtt (pour la config du dashboard grafana)

**Comment by alexbelgium** [comment]
Super, merci pour le feedbak!
