### ISSUE TITLE
🐛 [Nextcloud] Addon i cant set trusted_domains ("PDO" error)

### ISSUE THREAD

**Issue by chertvl** [alexbelgium/hassio-addons#902]
### Description

An every addon start I have same errors in addon log, and "trusted_domains:" field not added in configuration.
What im doing wrong?

If i do initial configuration with "homeassistant:8099" then my "192.168.1.2:8099 isnt trusted domain",
if i do initial from "192.168.1.2:8099" - then my "homeassistant:port" isnt trusted.

Using Intel NUC10 with pure HAOS, my addon configuration:

```
Full_Text_Search: false
OCR: false
OCRLANG: rus
PGID: 1000
PUID: 1000
additional_apps: inotify-tools, nextcloud
certfile: fullchain.pem
elasticsearch_server: <ip:port>
keyfile: privkey.pem
trusted_domains: "homeassistant, 192.168.1.2"
use_own_certs: false
```

Thank you!

### Reproduction steps

```bash
1. Add a domains in "trusted_domains"
2. Restart addon
```

### Addon Logs

```bash
[12:37:47] INFO: Currently set trusted domains :

An unhandled exception has been thrown:
Error: Class "PDO" not found in /data/config/www/nextcloud/lib/private/DB/Connection.php:156
Stack trace:
#0 /data/config/www/nextcloud/lib/private/AppConfig.php(415): OC\DB\Connection->getQueryBuilder()
#1 /data/config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#2 /data/config/www/nextcloud/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
#3 /data/config/www/nextcloud/lib/private/legacy/OC_App.php(803): OC\AppConfig->getValues()
#4 /data/config/www/nextcloud/lib/private/Server.php(733): OC_App::getAppVersions()
#5 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#6 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#8 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#9 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#10 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#11 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#14 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#15 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#16 /data/config/www/nextcloud/lib/private/Server.php(1115): OC\AppFramework\Utility\SimpleContainer->get()
#17 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#18 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#20 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#21 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#22 /data/config/www/nextcloud/lib/private/Server.php(2067): OC\AppFramework\Utility\SimpleContainer->get()
#23 /data/config/www/nextcloud/lib/private/Files/View.php(106): OC\Server->getLockingProvider()
#24 /data/config/www/nextcloud/lib/private/Server.php(467): OC\Files\View->__construct()
#25 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#26 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#27 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#28 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#29 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#30 /data/config/www/nextcloud/lib/private/Server.php(1469): OC\AppFramework\Utility\SimpleContainer->get()
#31 /data/config/www/nextcloud/lib/base.php(631): OC\Server->boot()
#32 /data/config/www/nextcloud/lib/base.php(1173): OC::init()
#33 /data/config/www/nextcloud/console.php(48): require_once('...')
#34 /data/config/www/nextcloud/occ(11): require_once('...')

[12:37:47] INFO: No trusted domain set yet. The first one will be set when doing initial configuration
[12:37:47] INFO: Trusted domains set in the configuration. Refreshing domains.
[12:37:47] INFO: ... removing previously added trusted domain (except for first one created)

#35 {main}An unhandled exception has been thrown:
Error: Class "PDO" not found in /data/config/www/nextcloud/lib/private/DB/Connection.php:156
Stack trace:
#0 /data/config/www/nextcloud/lib/private/AppConfig.php(415): OC\DB\Connection->getQueryBuilder()
#1 /data/config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#2 /data/config/www/nextcloud/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
#3 /data/config/www/nextcloud/lib/private/legacy/OC_App.php(803): OC\AppConfig->getValues()
#4 /data/config/www/nextcloud/lib/private/Server.php(733): OC_App::getAppVersions()
#5 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#6 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#8 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#9 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#10 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#11 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#14 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#15 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#16 /data/config/www/nextcloud/lib/private/Server.php(1115): OC\AppFramework\Utility\SimpleContainer->get()
#17 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#18 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#20 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#21 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#22 /data/config/www/nextcloud/lib/private/Server.php(2067): OC\AppFramework\Utility\SimpleContainer->get()
#23 /data/config/www/nextcloud/lib/private/Files/View.php(106): OC\Server->getLockingProvider()
#24 /data/config/www/nextcloud/lib/private/Server.php(467): OC\Files\View->__construct()
#25 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#26 /data/config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#27 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#28 /data/config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#29 /data/config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#30 /data/config/www/nextcloud/lib/private/Server.php(1469): OC\AppFramework\Utility\SimpleContainer->get()
#31 /data/config/www/nextcloud/lib/base.php(631): OC\Server->boot()
#32 /data/config/www/nextcloud/lib/base.php(1173): OC::init()
#33 /data/config/www/nextcloud/console.php(48): require_once('...')
#34 /data/config/www/nextcloud/occ(11): require_once('...')
#35 {main}Setting resolver to  127.0.0.11
Setting worker_processes to 4
using keys found in /data/config/keys
```

### OS

HAos

**Comment by chertvl** [comment]
Reinstalled addon 10-15 times last several days, and now its ok, domains adds when is starts. Thank you, ill need to close issue for now.

**Comment by alexbelgium** [comment]
Hi, thanks that's very strange... Well at least it is working then. The lsio logic has changed so I'll have to push a new version soon which perhaps could prevent reoccurrance

**Comment by chertvl** [comment]
> Hi, thanks that's very strange... Well at least it is working then. The lsio logic has changed so I'll have to push a new version soon which perhaps could prevent reoccurrance

Thank you again.
Idk what I did wrong, after that Ive reistalled addon several times, learned how to modify config.php with VIM in portainer, and i didnt see that error anymore. All works perfect. <3
