### ISSUE TITLE
🐛 [MyElectricalData] Bad text encoding when using ingress view

### ISSUE THREAD

**Issue by Bobdugrand8** [alexbelgium/hassio-addons#914]
### Description

There is an issue with ingress view for MyElectricalData that doesn't appear when connecting directly to the page.
The issue is only with Firefox, not Chrominium based browers. 

![image](https://github.com/alexbelgium/hassio-addons/assets/72624889/ca6a3b87-d11f-4c14-bd96-ba49daf0675b)

### Reproduction steps

```bash
1. Go to the MyElectricalData ingress page with Firefox (any plateform)
2. The page has not the good encoding so all special characters are not well render.
```

### Addon Logs

```bash
2023-07-23 10:37:15.912 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:15.958 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:15.959 -     INFO :  [XXXX] STATUT DU COMPTE.
2023-07-23 10:37:15.959 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:15.998 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:15.999 -     INFO :   FINISH
2023-07-23 10:37:16.000 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.048 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.049 -     INFO :  [XXXX] EXPORTATION DE DONNÉES DANS MQTT.
2023-07-23 10:37:16.049 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.050 -     INFO : Génération des messages du contrat
2023-07-23 10:37:16.076 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.077 -     INFO :   FINISH
2023-07-23 10:37:16.077 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.127 -     INFO : Génération des messages d'addresse
2023-07-23 10:37:16.154 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.155 -     INFO :   FINISH
2023-07-23 10:37:16.156 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:16.233 -     INFO : Génération des données annuelles
2023-07-23 10:37:17.021 -     INFO : 127.0.0.1:54892 - "GET / HTTP/1.1" 200
2023-07-23 10:37:21.129 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:21.129 -     INFO :   FINISH
2023-07-23 10:37:21.130 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:21.184 -     INFO : Génération des données linéaires journalières.
2023-07-23 10:37:21.946 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:21.946 -     INFO :   FINISH
2023-07-23 10:37:21.947 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:21.996 -     INFO : Génération des données annuelles détaillé.
2023-07-23 10:37:22.634 -     INFO : 127.0.0.1:50692 - "GET / HTTP/1.1" 200
2023-07-23 10:37:27.995 -     INFO : 127.0.0.1:50700 - "GET / HTTP/1.1" 200
2023-07-23 10:37:33.447 -     INFO : 127.0.0.1:39884 - "GET / HTTP/1.1" 200
2023-07-23 10:37:38.849 -     INFO : 127.0.0.1:39892 - "GET / HTTP/1.1" 200
2023-07-23 10:37:44.335 -     INFO : 127.0.0.1:39692 - "GET / HTTP/1.1" 200
2023-07-23 10:37:49.812 -     INFO : 127.0.0.1:39706 - "GET / HTTP/1.1" 200
2023-07-23 10:37:54.821 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:54.822 -     INFO :   FINISH
2023-07-23 10:37:54.822 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:37:54.877 -     INFO : Génération des données linéaires détaillées
2023-07-23 10:37:55.251 -     INFO : 127.0.0.1:40358 - "GET / HTTP/1.1" 200
2023-07-23 10:38:00.823 -     INFO : 127.0.0.1:48850 - "GET / HTTP/1.1" 200
2023-07-23 10:38:06.717 -     INFO : 127.0.0.1:48852 - "GET / HTTP/1.1" 200
2023-07-23 10:38:08.458 -     INFO :  => Finish
2023-07-23 10:38:08.509 -     INFO : Génération des données de puissance max journalières.
2023-07-23 10:38:08.649 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:38:08.650 -     INFO :   EXPORT TERMINÉ
2023-07-23 10:38:08.650 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:38:08.651 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:38:08.652 -     INFO :   EXPORTATION HOME ASSISTANT
2023-07-23 10:38:08.652 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:38:08.707 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:38:08.708 -     INFO :  [XXXX] EXPORTATION DES DONNÉES DANS HOME ASSISTANT (VIA MQTT)
2023-07-23 10:38:08.708 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-23 10:38:08.822 -     INFO : current_week
2023-07-23 10:38:08.850 -     INFO :  75085
2023-07-23 10:38:08.851 -     INFO : last_week
2023-07-23 10:38:08.874 -     INFO :  99127
2023-07-23 10:38:08.875 -     INFO : current_week_last_year
2023-07-23 10:38:08.899 -     INFO :  30715
2023-07-23 10:38:08.900 -     INFO : last_month
2023-07-23 10:38:08.925 -     INFO :  => 201434
2023-07-23 10:38:08.926 -     INFO : current_month
2023-07-23 10:38:08.950 -     INFO :  => 226549
2023-07-23 10:38:08.951 -     INFO : current_month_last_year
2023-07-23 10:38:08.976 -     INFO :  => 43506
2023-07-23 10:38:08.977 -     INFO : last_month_last_year
2023-07-23 10:38:09.003 -     INFO :  => 0
2023-07-23 10:38:09.003 -     INFO : current_year
2023-07-23 10:38:09.046 -     INFO :  => 1576510
2023-07-23 10:38:09.046 -     INFO : current_year_last_year
2023-07-23 10:38:09.090 -     INFO :  => 43506
2023-07-23 10:38:09.091 -     INFO : last_year
2023-07-23 10:38:09.117 -     INFO :  => 0
2023-07-23 10:38:09.117 -     INFO : yesterday_hp / yesterday_hc
2023-07-23 10:38:09.200 -     INFO :  => HC : 1698.0
2023-07-23 10:38:09.201 -     INFO :  => HP : 2845.0
2023-07-23 10:38:09.201 -     INFO : peak_offpeak_percent_hp VS peak_offpeak_percent_hc
2023-07-23 10:38:12.263 -     INFO :  => 44.6407595711012
2023-07-23 10:38:12.264 -     INFO : current_week_evolution
2023-07-23 10:38:12.264 -     INFO :  -24.253735107488367
2023-07-23 10:38:12.265 -     INFO : current_month_evolution
2023-07-23 10:38:12.265 -     INFO :  => 420.730473957615
2023-07-23 10:38:12.266 -     INFO : yesterday_evolution
2023-07-23 10:38:12.266 -     INFO : yesterday
2023-07-23 10:38:12.311 -     INFO :  4543
2023-07-23 10:38:12.311 -     INFO : yesterday_1
2023-07-23 10:38:12.340 -     INFO : 127.0.0.1:43416 - "GET / HTTP/1.1" 200
2023-07-23 10:38:12.346 -     INFO :  11530
2023-07-23 10:38:12.348 -     INFO :  -60.59843885516045
2023-07-23 10:38:12.348 -     INFO : monthly_evolution
2023-07-23 10:38:12.350 -     INFO : last_month
2023-07-23 10:38:12.381 -     INFO :  => 402868
2023-07-23 10:38:12.382 -     INFO : last_month_last_year
2023-07-23 10:38:12.408 -     INFO :  => 0
2023-07-23 10:38:12.409 -     INFO :  => 0
2023-07-23 10:38:12.409 -     INFO : yearly_evolution
2023-07-23 10:38:12.410 -     INFO : current_year
2023-07-23 10:38:12.454 -     INFO :  => 3153020
2023-07-23 10:38:12.454 -     INFO : current_year_last_year
2023-07-23 10:38:12.497 -     INFO :  => 87012
2023-07-23 10:38:12.498 -     INFO :  => 0
```

### Architecture

armv7

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, now that is quite strange. @m4dm4rtig4n are all characters encoding UTF-8 ?

I'll try to duplicate

**Comment by Jib-san** [comment]
Hi,

Same for me with ingress view.

Home Assistant 2023.7.3 
Supervisor 2023.07.1 
Operating System 10.3 
Interface utilisateur : 20230705.1 - latest
MyElectricalData : 0.9.0

**Comment by m4dm4rtig4n** [comment]
With 0.9.0 i have migrate to framework FastAPI, it's possible encoding have change.
I check on it.

**Comment by Bobdugrand8** [comment]
For information : the issue was already there with version 0.8.16.

**Comment by alexbelgium** [comment]
If I remember well there was a way to start the app without an account ? I can't make it work again to check the issue

**Comment by m4dm4rtig4n** [comment]
Try with this config.yaml file :
```
debug: true
tempo:
  enable: false
home_assistant:
  enable: false
influxdb:
  enable: false
mqtt:
  enable: false
myelectricaldata:
  "MON_PDL_1":
    enable: 'true'
    token: TOKEN_DE_MON_PDL_1
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.145907'
    consumption_price_hc: '0.124364'
    consumption_price_hp: '0.164915'
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 22H00-6H00               # LUNDI
    offpeak_hours_1: 22H00-6H00               # MARDI
    offpeak_hours_2: 22H00-6H00               # MERCREDI
    offpeak_hours_3: 22H00-6H00               # JEUDI
    offpeak_hours_4: 22H00-6H00               # VENDREDI
    offpeak_hours_5: 22H00-6H00;12H00-14H00   # SAMEDI
    offpeak_hours_6: 22H00-6H00;12H00-14H00   # DIMANCHE
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
```

**Comment by m4dm4rtig4n** [comment]
I can try to add this line in next 0.9.1 (0.9.1-beta10) :
```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

**Comment by alexbelgium** [comment]
> Try with this config.yaml file :
> 
> ```
> debug: true
> tempo:
>   enable: false
> home_assistant:
>   enable: false
> influxdb:
>   enable: false
> mqtt:
>   enable: false
> myelectricaldata:
>   "MON_PDL_1":
>     enable: 'true'
>     token: TOKEN_DE_MON_PDL_1
>     name: "Maison"
>     addresses: 'true'
>     cache: 'true'
>     consumption: 'true'
>     consumption_detail: 'true'
>     consumption_price_base: '0.145907'
>     consumption_price_hc: '0.124364'
>     consumption_price_hp: '0.164915'
>     consumption_max_date: "2021-06-01"
>     consumption_detail_max_date: "2021-06-01"
>     offpeak_hours_0: 22H00-6H00               # LUNDI
>     offpeak_hours_1: 22H00-6H00               # MARDI
>     offpeak_hours_2: 22H00-6H00               # MERCREDI
>     offpeak_hours_3: 22H00-6H00               # JEUDI
>     offpeak_hours_4: 22H00-6H00               # VENDREDI
>     offpeak_hours_5: 22H00-6H00;12H00-14H00   # SAMEDI
>     offpeak_hours_6: 22H00-6H00;12H00-14H00   # DIMANCHE
>     plan: HC/HP
>     production: 'false'
>     production_detail: 'false'
>     production_price: '0.0'
>     production_max_date: "2021-06-01"
>     production_detail_max_date: "2021-06-01"
>     refresh_addresse: 'false'
>     refresh_contract: 'false'
> ```

J'ai un soucis pour me connecter avec cette config. Voici le résultat : 

<details>
  <summary>Click me</summary>
  
  ```bash
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
[20:43:12] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery...
[20:43:12] FATAL: No internal MQTT service found. Please install Mosquitto broker
/etc/cont-init.d/91-mqtt_autodiscover.sh: exiting 1
/etc/cont-init.d/99-run.sh: executing
creating symlink
[20:43:12] INFO: Using database file found in /config/myelectricaldata
[20:43:12] INFO: Using config file found in /config/myelectricaldata/config.yaml
Config file is a valid yaml
 
[20:43:12] INFO: Starting nginx
 
 
[20:43:12] INFO: Starting the app
2023-07-27 20:43:12.579 -     INFO : Display configuration :
2023-07-27 20:43:12.579 -     INFO :   cycle: 14400
2023-07-27 20:43:12.579 -     INFO :   debug: False
2023-07-27 20:43:12.579 -     INFO :   home_assistant:
2023-07-27 20:43:12.579 -     INFO :     discovery_prefix: homeassistant
2023-07-27 20:43:12.579 -     INFO :     enable: False
2023-07-27 20:43:12.579 -     INFO :   influxdb:
2023-07-27 20:43:12.579 -     INFO :     bucket: myelectricaldata
2023-07-27 20:43:12.579 -     INFO :     enable: False
2023-07-27 20:43:12.579 -     INFO :     hostname: influxdb
2023-07-27 20:43:12.579 -     INFO :     method: synchronous
2023-07-27 20:43:12.579 -     INFO :     org: myelectricaldata
2023-07-27 20:43:12.579 -     INFO :     port: 8086
2023-07-27 20:43:12.579 -     INFO :     token: ** hidden **
2023-07-27 20:43:12.579 -     INFO :   mqtt:
2023-07-27 20:43:12.579 -     INFO :     client_id: myelectricaldata
2023-07-27 20:43:12.579 -     INFO :     enable: False
2023-07-27 20:43:12.579 -     INFO :     hostname: X.X.X.X
2023-07-27 20:43:12.579 -     INFO :     password: ** hidden **
2023-07-27 20:43:12.579 -     INFO :     port: 1883
2023-07-27 20:43:12.579 -     INFO :     prefix: myelectricaldata
2023-07-27 20:43:12.579 -     INFO :     qos: 0
2023-07-27 20:43:12.579 -     INFO :     retain: True
2023-07-27 20:43:12.580 -     INFO :     username: 
2023-07-27 20:43:12.580 -     INFO :   myelectricaldata:
2023-07-27 20:43:12.580 -     INFO :     aaaaaaaaaaaaaa:
2023-07-27 20:43:12.580 -     INFO :       activation_date_daily: 
2023-07-27 20:43:12.580 -     INFO :       activation_date_detail: 
2023-07-27 20:43:12.580 -     INFO :       cache: True
2023-07-27 20:43:12.580 -     INFO :       consumption: True
2023-07-27 20:43:12.580 -     INFO :       consumption_detail: True
2023-07-27 20:43:12.580 -     INFO :       consumption_detail_max_date: 
2023-07-27 20:43:12.580 -     INFO :       consumption_max_date: 
2023-07-27 20:43:12.580 -     INFO :       consumption_price_base: 0
2023-07-27 20:43:12.580 -     INFO :       consumption_price_hc: 0
2023-07-27 20:43:12.580 -     INFO :       consumption_price_hp: 0
2023-07-27 20:43:12.580 -     INFO :       enable: True
2023-07-27 20:43:12.580 -     INFO :       name: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_0: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_1: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_2: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_3: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_4: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_5: 
2023-07-27 20:43:12.580 -     INFO :       offpeak_hours_6: 
2023-07-27 20:43:12.580 -     INFO :       plan: BASE
2023-07-27 20:43:12.580 -     INFO :       production: False
2023-07-27 20:43:12.580 -     INFO :       production_detail: False
2023-07-27 20:43:12.580 -     INFO :       production_detail_max_date: 
2023-07-27 20:43:12.580 -     INFO :       production_max_date: 
2023-07-27 20:43:12.580 -     INFO :       production_price: 0
2023-07-27 20:43:12.580 -     INFO :       refresh_addresse: False
2023-07-27 20:43:12.580 -     INFO :       refresh_contract: False
2023-07-27 20:43:12.580 -     INFO :       token: ** hidden **
2023-07-27 20:43:12.580 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-27 20:43:12.581 -     INFO : Check config.yaml :
2023-07-27 20:43:12.581 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-07-27 20:43:12.581 -     INFO :   CONFIG VALID
2023-07-27 20:43:12.581 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 0b59c59dad3c -> 28b7a00bae70, add tempo
INFO  [alembic.runtime.migration] Running upgrade 28b7a00bae70 -> 158de49caa38, recreate statistique
INFO  [alembic.runtime.migration] Running upgrade 158de49caa38 -> b3505740913d, add ecowatt
2023-07-27 20:43:15.743 -     INFO : Configure Databases
2023-07-27 20:43:15.754 -     INFO :  => day
2023-07-27 20:43:16.113 -     INFO :  => call_number
2023-07-27 20:43:16.115 -     INFO :  => max_call
2023-07-27 20:43:16.116 -     INFO :  => version
2023-07-27 20:43:16.347 -     INFO :  => lock
2023-07-27 20:43:16.351 -     INFO :  => lastUpdate
2023-07-27 20:43:16.351 -     INFO :  Success
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from routers import account
  File "/app/routers/account.py", line 3, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 8, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 7, in <module>
    from models.export_home_assistant import HomeAssistant
  File "/app/models/export_home_assistant.py", line 9, in <module>
    from init import MQTT, DB, CONFIG
ImportError: cannot import name 'MQTT' from 'init' (/app/init.py)
[20:43:16] FATAL: The app has crashed. Are you sure you entered the correct config options?
  ```
</details>

**Comment by m4dm4rtig4n** [comment]
Tu est sur quelle version ? 0.9.0 ?
Si oui normal, il y a un bug quand tu disable MQTT :/

Le plus simple est de tester sur la 0.9.1-beta9.

**Comment by alexbelgium** [comment]
Mmh j'ai tenté de forcer le charset UTF-8 sans succès sur nginx. Pas clair quel est l'origine du problème lorsque les data passent via nginx...

**Comment by alexbelgium** [comment]
not stale

**Comment by alexbelgium** [comment]
Please let me know if the latest version works

**Comment by Bobdugrand8** [comment]
The latest version is now OK for me. Thank you.

**Comment by alexbelgium** [comment]
Thanks, can we close the issue report?

**Comment by Bobdugrand8** [comment]
Yes we can
