### ISSUE TITLE
🐛 [Addon name] myelectricaldata

### ISSUE THREAD

**Issue by yroffin** [alexbelgium/hassio-addons#926]
### Description

with the last version i've

```
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from routers import account
  File "/app/routers/account.py", line 3, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 8, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 7, in <module>
    from models.export_home_assistant import HomeAssistant
  File "/app/models/export_home_assistant.py", line 9, in <module>
    from init import MQTT, DB, CONFIG
ImportError: cannot import name 'MQTT' from 'init' (/app/init.py)
```

any idea to this missing import ?

### Reproduction steps

```bash
1. Go to addon
2. And start it
```

### Addon Logs

```bash
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from routers import account
  File "/app/routers/account.py", line 3, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 8, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 7, in <module>
    from models.export_home_assistant import HomeAssistant
  File "/app/models/export_home_assistant.py", line 9, in <module>
    from init import MQTT, DB, CONFIG
ImportError: cannot import name 'MQTT' from 'init' (/app/init.py)
```

### Architecture

armv7

### OS

HAos

**Comment by alexbelgium** [comment]
Hi, mqtt needs to be configured for the add-on to work. I had the same issue here : https://github.com/alexbelgium/hassio-addons/issues/914#issuecomment-1654229783
