### ISSUE TITLE
❓ [Immich] database "immich" does not exist

### ISSUE THREAD

**Issue by swap83** [alexbelgium/hassio-addons#990]
I have this error "database "immich" does not exist".
I started this addon before and after I installed posgres

**Comment by alexbelgium** [comment]
Hi, thanks this is indeed subliminal thought it should be created automatically. Could you please post your full startup log ? Thanks

**Comment by swap83** [comment]
Sorry, i don't know docker. How and Where put that command?
I have HassOS

**Comment by alexbelgium** [comment]
Hi, I see this error code : 
```
psql: error: connection to server at "homeassistant.local" (172.30.32.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```

Have you installed the postgres addon and started it with this port exposed ? You could also try to use your real homeassistant local ip instead of homeassistant.local. Sorry if this was not in the readme, I can review the instructions later

99-database.sh actually comes from the upstream container while 99-run.sh comes from my custom code so it is normal to run sequentially : the idea is that my scripts are run before the upstream container to allow to bridge the container developer by imagegenius to homeassistant

**Comment by Crown421** [comment]
I was wondering about that part too. 

I do not have the postgres addon, all I did was hit "install" in the addon shop after adding this repo. I initially set some custom config, but have since reset back to the default. 
The port number (5432) is set in the `DB_...` config. 

Am I understanding correctly that I need to install the postgres addon separately?

**Comment by Crown421** [comment]
Indeed, that was the issue. At least for me it is now working. Thank you!

**Comment by alexbelgium** [comment]
Thanks, then I close this issue as it is confirmed to work! Thanks!

**Comment by EnderDragonEP** [comment]
I just start using this addon and I keeps getting this error:
```log
[Nest] 2537  - 02/04/2025, 1:58:42 PM   ERROR [ExceptionHandler] database "immich" does not exist
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
api worker exited with code 1
Starting api worker
```

Do I need to mentally create a database or I'm I missing something else?

**Comment by alexbelgium** [comment]
Thanks! I think initially I had set an automatic database creation but it created some issue so I had removed it. I'll look to reimplement this as some users less tech-savy than you might be a bit lost with that part

Argh and I just see that corrected the "mentally create a database" to "manually" so I can't even joke on that ;-)
Ender Dragon, is that name based on Orson Scott Card's book Ender's Game ? I love that book

**Comment by alexbelgium** [comment]
Actually it is still in the code : 

https://github.com/alexbelgium/hassio-addons/blob/0b3c9878bfd64d5c25e7d61460ec180a4425e73c/immich/rootfs/etc/cont-init.d/99-run.sh#L98-L102

I'll do some tests on my side

**Comment by EnderDragonEP** [comment]
> Thanks! I think initially I had set an automatic database creation but it created some issue so I had removed it. I'll look to reimplement this as some users less tech-savy than you might be a bit lost with that part
> 
> Argh and I just see that you corrected the "mentally create a database" to "manually" so I can't even joke on that ;-) Ender Dragon, is that name based on Orson Scott Card's book Ender's Game ? It's a book I like a lot

Thank you for your kind reply! And I'm sorry for the incorrect wording 😭 English is not my mother tongue and I didn't see the mistake before I send it.

I got my name from the boss of a game called Minecraft. But I also love the film Ender's game! The  guy was so cool and I love the soundtracks 👍

I'm using this addon on my Raspberry Pie 5 right now and it great! It will be great if the addon has automatic database creation and I think everyone will be very grateful for it!  Thank you and the contributors for this amazing addon

**Comment by alexbelgium** [comment]
Ahahah of course no worry english is not my mother tongue neither ;-) it's just that I had the image in my mind of someone with telekinetic power that could create a database mentally by thinking about it and was telling myself it would be quite an interesting skill!

If you loved the film you should try the book ; it's written in quite a nice way and it goes even beyond the movie! Although the movie has also impressive visual effects of course

For the automatic database creation I'll try to have a look - all those addons take quite a lot of time to look at especially as I don't use most of them so it's more when I have the time or a specific interest that I take the time to look ;-) But fully agree Immich is a great app! Photoprism is also quite great - I was never able to decide which one I liked best

**Comment by EnderDragonEP** [comment]
Thanks you for your effort! I didn't know that there were books of that movie, I'll be sure to go look for it! 😉
